import type { Faction, Unit, Detachment } from "./types";

// =============================================
// SPACE MARINES — Full Roster
// =============================================

export const SM_UNITS: Unit[] = [
  // ========== CHARACTERS — HQ ==========
  {
    id: "sm-captain",
    name: "Captain",
    faction: "space-marines",
    keywords: ["Infantry", "Character", "Captain"],
    factionKeywords: ["Adeptus Astartes"],
    stats: { movement: "6\"", toughness: 4, save: "3+", wounds: 5, leadership: "6+", oc: 1 },
    weapons: [
      { name: "Master-crafted Power Sword", range: "Melee", attacks: "5", skill: "2+", strength: 5, ap: -3, damage: "2", abilities: [] },
      { name: "Plasma Pistol (standard)", range: "12\"", attacks: "1", skill: "2+", strength: 7, ap: -2, damage: "1", abilities: ["Pistol"] },
      { name: "Plasma Pistol (supercharge)", range: "12\"", attacks: "1", skill: "2+", strength: 8, ap: -3, damage: "2", abilities: ["Hazardous", "Pistol"] },
    ],
    abilities: [
      { name: "Rites of Battle", description: "While this unit is on the battlefield, once per turn you can re-roll one Hit roll, one Wound roll, or one Damage roll made for a friendly Adeptus Astartes unit within 6\"." },
      { name: "Iron Halo", description: "This unit has a 4+ invulnerable save." },
    ],
    invulnSave: "4+",
    isCharacter: true,
    points: 80,
    baseSize: "40mm round",
    models: 1,
  },
  {
    id: "sm-captain-terminator",
    name: "Captain in Terminator Armour",
    faction: "space-marines",
    keywords: ["Infantry", "Character", "Terminator", "Captain"],
    factionKeywords: ["Adeptus Astartes"],
    stats: { movement: "5\"", toughness: 5, save: "2+", wounds: 6, leadership: "6+", oc: 1 },
    weapons: [
      { name: "Master-crafted Power Weapon", range: "Melee", attacks: "6", skill: "2+", strength: 6, ap: -2, damage: "2", abilities: [] },
      { name: "Combi-weapon (bolter)", range: "24\"", attacks: "2", skill: "2+", strength: 4, ap: 0, damage: "1", abilities: [] },
      { name: "Combi-weapon (melta)", range: "12\"", attacks: "1", skill: "2+", strength: 9, ap: -4, damage: "D6", abilities: ["Melta 2"] },
    ],
    abilities: [
      { name: "Rites of Battle", description: "While this unit is on the battlefield, once per turn you can re-roll one Hit roll, one Wound roll, or one Damage roll made for a friendly Adeptus Astartes unit within 6\"." },
      { name: "Iron Halo", description: "This unit has a 4+ invulnerable save." },
      { name: "Deep Strike", description: "During deployment, you can set up this unit in Strategic Reserve." },
    ],
    invulnSave: "4+",
    isCharacter: true,
    points: 100,
    baseSize: "40mm round",
    models: 1,
  },
  {
    id: "sm-captain-phobos",
    name: "Captain in Phobos Armour",
    faction: "space-marines",
    keywords: ["Infantry", "Character", "Phobos", "Captain"],
    factionKeywords: ["Adeptus Astartes"],
    stats: { movement: "6\"", toughness: 4, save: "3+", wounds: 5, leadership: "6+", oc: 1 },
    weapons: [
      { name: "Master-crafted Instigator Bolt Carbine", range: "30\"", attacks: "2", skill: "2+", strength: 4, ap: -2, damage: "2", abilities: ["Precision"] },
      { name: "Paired Combat Blades", range: "Melee", attacks: "6", skill: "2+", strength: 4, ap: -1, damage: "1", abilities: ["Twin-linked"] },
    ],
    abilities: [
      { name: "Rites of Battle", description: "While this unit is on the battlefield, once per turn you can re-roll one Hit roll, one Wound roll, or one Damage roll made for a friendly Adeptus Astartes unit within 6\"." },
      { name: "Iron Halo", description: "This unit has a 4+ invulnerable save." },
      { name: "Clandestine Infiltration", description: "At the start of your first turn, if this model is on the battlefield, it can make a Normal move of up to 6\". In addition, enemy units within 12\" of this model subtract 1 from their Objective Control characteristic." },
    ],
    invulnSave: "4+",
    isCharacter: true,
    points: 90,
    baseSize: "40mm round",
    models: 1,
  },
  {
    id: "sm-captain-jump",
    name: "Captain with Jump Pack",
    faction: "space-marines",
    keywords: ["Infantry", "Character", "Jump Pack", "Fly", "Captain"],
    factionKeywords: ["Adeptus Astartes"],
    stats: { movement: "12\"", toughness: 4, save: "3+", wounds: 5, leadership: "6+", oc: 1 },
    weapons: [
      { name: "Master-crafted Power Weapon", range: "Melee", attacks: "5", skill: "2+", strength: 6, ap: -2, damage: "2", abilities: [] },
      { name: "Plasma Pistol (standard)", range: "12\"", attacks: "1", skill: "2+", strength: 7, ap: -2, damage: "1", abilities: ["Pistol"] },
    ],
    abilities: [
      { name: "Rites of Battle", description: "While this unit is on the battlefield, once per turn you can re-roll one Hit roll, one Wound roll, or one Damage roll made for a friendly Adeptus Astartes unit within 6\"." },
      { name: "Iron Halo", description: "This unit has a 4+ invulnerable save." },
      { name: "Assault Doctrine", description: "This unit is eligible to charge in a turn in which it Advanced." },
    ],
    invulnSave: "4+",
    isCharacter: true,
    points: 90,
    baseSize: "40mm round",
    models: 1,
  },
  {
    id: "sm-librarian",
    name: "Librarian",
    faction: "space-marines",
    keywords: ["Infantry", "Character", "Psyker", "Librarian"],
    factionKeywords: ["Adeptus Astartes"],
    stats: { movement: "6\"", toughness: 4, save: "3+", wounds: 5, leadership: "6+", oc: 1 },
    weapons: [
      { name: "Force Weapon", range: "Melee", attacks: "4", skill: "3+", strength: 6, ap: -1, damage: "D3", abilities: ["Psychic"] },
      { name: "Bolt Pistol", range: "12\"", attacks: "1", skill: "3+", strength: 4, ap: 0, damage: "1", abilities: ["Pistol"] },
    ],
    abilities: [
      { name: "Psychic Hood", description: "Once per turn, when an enemy Psyker unit within 12\" of this unit takes a Psychic test, you can subtract 1 from the result." },
      { name: "Smite", description: "Psychic ability: Target one enemy unit within 18\". Roll one D6 for each model in this unit; each result of 4+ inflicts 1 mortal wound on the target." },
    ],
    invulnSave: "4+",
    isCharacter: true,
    points: 75,
    baseSize: "40mm round",
    models: 1,
  },
  {
    id: "sm-chaplain",
    name: "Chaplain",
    faction: "space-marines",
    keywords: ["Infantry", "Character", "Chaplain"],
    factionKeywords: ["Adeptus Astartes"],
    stats: { movement: "6\"", toughness: 4, save: "3+", wounds: 4, leadership: "5+", oc: 1 },
    weapons: [
      { name: "Crozius Arcanum", range: "Melee", attacks: "4", skill: "2+", strength: 6, ap: -1, damage: "2", abilities: [] },
      { name: "Bolt Pistol", range: "12\"", attacks: "1", skill: "2+", strength: 4, ap: 0, damage: "1", abilities: ["Pistol"] },
    ],
    abilities: [
      { name: "Litanies of Battle", description: "If this unit is on the battlefield at the start of your Command phase, roll one D6: on a 3+, select one of the following Litanies of Battle to be in effect until the start of your next Command phase. Friendly Adeptus Astartes units within 6\" of this unit benefit from the active Litany." },
      { name: "Righteous Zeal (Litany)", description: "Add 3\" to the Move characteristic of units affected." },
      { name: "Mantra of Strength (Litany)", description: "Add 2 to the Strength of melee weapons of units affected." },
    ],
    invulnSave: "4+",
    isCharacter: true,
    points: 65,
    baseSize: "40mm round",
    models: 1,
  },
  {
    id: "sm-lieutenant",
    name: "Lieutenant",
    faction: "space-marines",
    keywords: ["Infantry", "Character", "Lieutenant"],
    factionKeywords: ["Adeptus Astartes"],
    stats: { movement: "6\"", toughness: 4, save: "3+", wounds: 5, leadership: "6+", oc: 1 },
    weapons: [
      { name: "Master-crafted Bolt Rifle", range: "24\"", attacks: "2", skill: "2+", strength: 4, ap: -1, damage: "1", abilities: ["Precision"] },
      { name: "Power Weapon", range: "Melee", attacks: "4", skill: "2+", strength: 5, ap: -2, damage: "1", abilities: [] },
    ],
    abilities: [
      { name: "Tactical Precision", description: "While this unit is on the battlefield, once per turn, friendly Adeptus Astartes units within 6\" can re-roll one Wound roll." },
    ],
    invulnSave: "4+",
    isCharacter: true,
    points: 65,
    baseSize: "40mm round",
    models: 1,
  },
  {
    id: "sm-techmarine",
    name: "Techmarine",
    faction: "space-marines",
    keywords: ["Infantry", "Character", "Techmarine"],
    factionKeywords: ["Adeptus Astartes"],
    stats: { movement: "6\"", toughness: 4, save: "2+", wounds: 4, leadership: "6+", oc: 1 },
    weapons: [
      { name: "Servo-arm", range: "Melee", attacks: "2", skill: "3+", strength: 8, ap: -2, damage: "2", abilities: [] },
      { name: "Bolter", range: "24\"", attacks: "2", skill: "3+", strength: 4, ap: 0, damage: "1", abilities: [] },
    ],
    abilities: [
      { name: "Blessing of the Omnissiah", description: "At the start of your Command phase, select one friendly Adeptus Astartes Vehicle within 3\". That vehicle regains up to D3 lost wounds." },
      { name: "Mechadendrite Harness", description: "While this unit is within 3\" of a friendly Vehicle, improve this unit's Save by 1 (to a minimum of 2+)." },
    ],
    isCharacter: true,
    points: 65,
    baseSize: "40mm round",
    models: 1,
  },
  {
    id: "sm-ancient",
    name: "Ancient",
    faction: "space-marines",
    keywords: ["Infantry", "Character", "Ancient"],
    factionKeywords: ["Adeptus Astartes"],
    stats: { movement: "6\"", toughness: 4, save: "3+", wounds: 4, leadership: "6+", oc: 1 },
    weapons: [
      { name: "Bolt Pistol", range: "12\"", attacks: "1", skill: "3+", strength: 4, ap: 0, damage: "1", abilities: ["Pistol"] },
      { name: "Astartes Chainsword", range: "Melee", attacks: "4", skill: "3+", strength: 4, ap: -1, damage: "1", abilities: [] },
    ],
    abilities: [
      { name: "Chapter Banner", description: "While this unit is on the battlefield, once per turn, when a friendly Adeptus Astartes unit within 6\" would fail a Battle-shock or Leadership test, that unit can re-roll the test." },
    ],
    isCharacter: true,
    points: 50,
    baseSize: "40mm round",
    models: 1,
  },
  {
    id: "sm-apothecary",
    name: "Apothecary",
    faction: "space-marines",
    keywords: ["Infantry", "Character", "Apothecary"],
    factionKeywords: ["Adeptus Astartes"],
    stats: { movement: "6\"", toughness: 4, save: "3+", wounds: 4, leadership: "6+", oc: 1 },
    weapons: [
      { name: "Absolvor Bolt Pistol", range: "18\"", attacks: "1", skill: "3+", strength: 5, ap: -1, damage: "2", abilities: ["Pistol"] },
      { name: "Reductor Pistol", range: "3\"", attacks: "1", skill: "3+", strength: 4, ap: -4, damage: "2", abilities: ["Pistol"] },
    ],
    abilities: [
      { name: "Narthecium", description: "At the start of your Command phase, select one friendly Adeptus Astartes Infantry unit within 3\". One destroyed model from that unit (excluding Characters) is returned to the unit with all its wounds restored." },
      { name: "Feel No Pain 5+", description: "Friendly Adeptus Astartes units within 6\" of this model have the Feel No Pain 5+ ability." },
    ],
    isCharacter: true,
    points: 55,
    baseSize: "40mm round",
    models: 1,
  },
  {
    id: "sm-marneus-calgar",
    name: "Marneus Calgar",
    faction: "space-marines",
    keywords: ["Infantry", "Character", "Epic Hero", "Terminator", "Captain", "Marneus Calgar"],
    factionKeywords: ["Adeptus Astartes", "Ultramarines"],
    stats: { movement: "5\"", toughness: 5, save: "2+", wounds: 8, leadership: "5+", oc: 1 },
    weapons: [
      { name: "Gauntlets of Ultramar", range: "Melee", attacks: "10", skill: "2+", strength: 8, ap: -3, damage: "2", abilities: ["Twin-linked"] },
    ],
    abilities: [
      { name: "God of War", description: "Once per battle round, when a friendly Adeptus Astartes unit within 6\" would fail a Battle-shock test, that unit automatically passes the test instead." },
      { name: "Adept of the Codex", description: "Once per Command phase, this unit can be given a free Stratagem (0CP) that it satisfies the requirements for." },
      { name: "Iron Resolve", description: "This unit has a 4+ invulnerable save." },
    ],
    invulnSave: "4+",
    isCharacter: true,
    isEpicHero: true,
    points: 200,
    baseSize: "40mm round",
    models: 1,
  },
  {
    id: "roboute-guilliman",
    name: "Roboute Guilliman",
    faction: "space-marines",
    keywords: ["Infantry", "Character", "Epic Hero", "Primarch", "Psyker", "Roboute Guilliman"],
    factionKeywords: ["Adeptus Astartes", "Ultramarines"],
    stats: { movement: "6\"", toughness: 6, save: "2+", wounds: 12, leadership: "5+", oc: 3 },
    weapons: [
      { name: "Emperor's Sword", range: "Melee", attacks: "9", skill: "2+", strength: 10, ap: -4, damage: "3", abilities: ["Devastating Wounds"] },
      { name: "Hand of Dominion", range: "24\"", attacks: "6", skill: "2+", strength: 9, ap: -4, damage: "2", abilities: ["Assault"] },
    ],
    abilities: [
      { name: "Primarch of the Ultramarines", description: "Friendly Adeptus Astartes units within 6\" can always use Stratagems as if it were your turn." },
      { name: "Nobility Made Manifest", description: "At the start of your Command phase, you gain D3 Command Points." },
      { name: "Armour Indomitus", description: "This unit has a 3+ invulnerable save. Each time this model would lose a wound, roll one D6: on a 3+, that wound is not lost." },
    ],
    invulnSave: "3+",
    feelNoPain: "3+",
    isCharacter: true,
    isEpicHero: true,
    damagedProfile: { wounds: 4, description: "While this model has 1–4 wounds remaining, subtract 2 from its Attacks characteristic." },
    points: 380,
    baseSize: "60mm round",
    models: 1,
  },

  // ========== BATTLELINE ==========
  {
    id: "sm-intercessors",
    name: "Intercessors",
    faction: "space-marines",
    keywords: ["Infantry", "Battleline", "Intercessors"],
    factionKeywords: ["Adeptus Astartes"],
    stats: { movement: "6\"", toughness: 4, save: "3+", wounds: 2, leadership: "6+", oc: 2 },
    weapons: [
      { name: "Auto Bolt Rifle", range: "24\"", attacks: "3", skill: "3+", strength: 4, ap: 0, damage: "1", abilities: ["Assault"] },
      { name: "Bolt Rifle", range: "30\"", attacks: "2", skill: "3+", strength: 4, ap: -1, damage: "1", abilities: ["Heavy"] },
      { name: "Stalker Bolt Rifle", range: "36\"", attacks: "1", skill: "3+", strength: 4, ap: -2, damage: "2", abilities: ["Heavy"] },
      { name: "Close Combat Weapon", range: "Melee", attacks: "2", skill: "3+", strength: 4, ap: 0, damage: "1", abilities: [] },
    ],
    abilities: [
      { name: "Objective Secured", description: "While this unit is within range of an objective marker, it controls that objective marker even if an equal number of enemy models are also within range." },
    ],
    points: 100, // 5 models
    models: 5,
    maxModels: 10,
    baseSize: "32mm round",
  },
  {
    id: "sm-assault-intercessors",
    name: "Assault Intercessors",
    faction: "space-marines",
    keywords: ["Infantry", "Battleline", "Intercessors"],
    factionKeywords: ["Adeptus Astartes"],
    stats: { movement: "6\"", toughness: 4, save: "3+", wounds: 2, leadership: "6+", oc: 2 },
    weapons: [
      { name: "Heavy Bolt Pistol", range: "18\"", attacks: "1", skill: "3+", strength: 4, ap: -1, damage: "1", abilities: ["Pistol"] },
      { name: "Astartes Chainsword", range: "Melee", attacks: "4", skill: "3+", strength: 4, ap: -1, damage: "1", abilities: [] },
    ],
    abilities: [
      { name: "Objective Secured", description: "While this unit is within range of an objective marker, it controls that objective marker even if an equal number of enemy models are also within range." },
    ],
    points: 95, // 5 models
    models: 5,
    maxModels: 10,
    baseSize: "32mm round",
  },
  {
    id: "sm-tactical-squad",
    name: "Tactical Squad",
    faction: "space-marines",
    keywords: ["Infantry", "Battleline", "Tactical Squad"],
    factionKeywords: ["Adeptus Astartes"],
    stats: { movement: "6\"", toughness: 4, save: "3+", wounds: 2, leadership: "6+", oc: 2 },
    weapons: [
      { name: "Boltgun", range: "24\"", attacks: "2", skill: "3+", strength: 4, ap: 0, damage: "1", abilities: [] },
      { name: "Bolt Pistol", range: "12\"", attacks: "1", skill: "3+", strength: 4, ap: 0, damage: "1", abilities: ["Pistol"] },
      { name: "Close Combat Weapon", range: "Melee", attacks: "2", skill: "3+", strength: 4, ap: 0, damage: "1", abilities: [] },
    ],
    abilities: [
      { name: "Objective Secured", description: "While this unit is within range of an objective marker, it controls that objective marker even if an equal number of enemy models are also within range." },
      { name: "Combat Squads", description: "Before deployment, this unit can be split into two units of 5 models." },
    ],
    points: 90, // 5 models
    models: 5,
    maxModels: 10,
    baseSize: "32mm round",
  },
  {
    id: "sm-scout-squad",
    name: "Scout Squad",
    faction: "space-marines",
    keywords: ["Infantry", "Battleline", "Scout Squad"],
    factionKeywords: ["Adeptus Astartes"],
    stats: { movement: "6\"", toughness: 4, save: "4+", wounds: 2, leadership: "6+", oc: 2 },
    weapons: [
      { name: "Bolt Pistol", range: "12\"", attacks: "1", skill: "3+", strength: 4, ap: 0, damage: "1", abilities: ["Pistol"] },
      { name: "Boltgun", range: "24\"", attacks: "2", skill: "3+", strength: 4, ap: 0, damage: "1", abilities: [] },
      { name: "Astartes Shotgun", range: "12\"", attacks: "2", skill: "3+", strength: 4, ap: 0, damage: "1", abilities: ["Assault", "Lethal Hits"] },
      { name: "Sniper Rifle", range: "36\"", attacks: "1", skill: "3+", strength: 4, ap: -2, damage: "D3", abilities: ["Heavy", "Lethal Hits", "Precision"] },
      { name: "Close Combat Weapon", range: "Melee", attacks: "2", skill: "3+", strength: 4, ap: 0, damage: "1", abilities: [] },
    ],
    abilities: [
      { name: "Scouts 6\"", description: "After deployment, this unit can make a Normal move of up to 6\" before the battle begins." },
      { name: "Camouflage Cloaks", description: "Each time a ranged attack targets this unit, if this unit is not within 6\" of any other Adeptus Astartes units, the attacker's Hit rolls suffer a -1 penalty." },
    ],
    points: 75, // 5 models
    models: 5,
    maxModels: 10,
    baseSize: "25mm round",
  },

  // ========== ELITE INFANTRY ==========
  {
    id: "sm-terminators",
    name: "Terminators",
    faction: "space-marines",
    keywords: ["Infantry", "Terminator"],
    factionKeywords: ["Adeptus Astartes"],
    stats: { movement: "5\"", toughness: 5, save: "2+", wounds: 3, leadership: "6+", oc: 1 },
    weapons: [
      { name: "Storm Bolter", range: "24\"", attacks: "2", skill: "3+", strength: 4, ap: 0, damage: "1", abilities: ["Rapid Fire 2"] },
      { name: "Power Fist", range: "Melee", attacks: "3", skill: "4+", strength: 8, ap: -2, damage: "2", abilities: [] },
    ],
    abilities: [
      { name: "Teleport Strike", description: "During deployment, this unit can be placed in Strategic Reserves. When deployed from Strategic Reserves, it can be placed anywhere on the battlefield that is more than 9\" from all enemy models." },
    ],
    invulnSave: "4+",
    points: 150, // 5 models
    models: 5,
    maxModels: 10,
    baseSize: "40mm round",
  },
  {
    id: "sm-assault-terminators",
    name: "Assault Terminators",
    faction: "space-marines",
    keywords: ["Infantry", "Terminator"],
    factionKeywords: ["Adeptus Astartes"],
    stats: { movement: "5\"", toughness: 5, save: "2+", wounds: 3, leadership: "6+", oc: 1 },
    weapons: [
      { name: "Thunder Hammer", range: "Melee", attacks: "3", skill: "4+", strength: 10, ap: -2, damage: "3", abilities: ["Devastating Wounds"] },
      { name: "Storm Shield", range: "Melee", attacks: "3", skill: "3+", strength: 6, ap: -1, damage: "1", abilities: [] },
      { name: "Lightning Claws (pair)", range: "Melee", attacks: "5", skill: "3+", strength: 6, ap: -2, damage: "1", abilities: ["Lethal Hits", "Twin-linked"] },
    ],
    abilities: [
      { name: "Teleport Strike", description: "During deployment, this unit can be placed in Strategic Reserves." },
    ],
    invulnSave: "4+",
    points: 175, // 5 models
    models: 5,
    maxModels: 10,
    baseSize: "40mm round",
  },
  {
    id: "sm-bladeguard-veterans",
    name: "Bladeguard Veterans",
    faction: "space-marines",
    keywords: ["Infantry", "Bladeguard Veterans"],
    factionKeywords: ["Adeptus Astartes"],
    stats: { movement: "6\"", toughness: 4, save: "3+", wounds: 3, leadership: "6+", oc: 1 },
    weapons: [
      { name: "Master-crafted Power Sword", range: "Melee", attacks: "4", skill: "3+", strength: 5, ap: -3, damage: "2", abilities: [] },
      { name: "Heavy Bolt Pistol", range: "18\"", attacks: "1", skill: "3+", strength: 4, ap: -1, damage: "1", abilities: ["Pistol"] },
    ],
    abilities: [
      { name: "Deathwing Shield", description: "This unit has a 4+ invulnerable save. Each time a model in this unit is allocated a wound, roll one D6: on a 6, that wound is not lost." },
    ],
    invulnSave: "4+",
    feelNoPain: "6+",
    points: 75, // 3 models
    models: 3,
    maxModels: 6,
    baseSize: "40mm round",
  },
  {
    id: "sm-sternguard-veterans",
    name: "Sternguard Veterans",
    faction: "space-marines",
    keywords: ["Infantry", "Sternguard Veterans"],
    factionKeywords: ["Adeptus Astartes"],
    stats: { movement: "6\"", toughness: 4, save: "3+", wounds: 2, leadership: "6+", oc: 1 },
    weapons: [
      { name: "Combi-weapon (bolter)", range: "24\"", attacks: "2", skill: "2+", strength: 4, ap: -1, damage: "1", abilities: [] },
      { name: "Combi-weapon (melta)", range: "12\"", attacks: "1", skill: "2+", strength: 9, ap: -4, damage: "D6", abilities: ["Melta 2"] },
      { name: "Combi-weapon (flamer)", range: "12\"", attacks: "D6", skill: "2+", strength: 5, ap: 0, damage: "1", abilities: ["Torrent"] },
      { name: "Astartes Chainsword", range: "Melee", attacks: "3", skill: "2+", strength: 4, ap: -1, damage: "1", abilities: [] },
    ],
    abilities: [
      { name: "Relentless Hunters", description: "Each time a model in this unit makes a ranged attack, re-roll a Hit roll of 1. If this unit was set up using Strategic Reserve this turn, re-roll all Hit rolls instead." },
    ],
    points: 90, // 5 models
    models: 5,
    maxModels: 10,
    baseSize: "32mm round",
  },
  {
    id: "sm-vanguard-veterans",
    name: "Vanguard Veterans",
    faction: "space-marines",
    keywords: ["Infantry", "Jump Pack", "Fly", "Vanguard Veterans"],
    factionKeywords: ["Adeptus Astartes"],
    stats: { movement: "12\"", toughness: 4, save: "3+", wounds: 2, leadership: "6+", oc: 1 },
    weapons: [
      { name: "Relic Blade", range: "Melee", attacks: "3", skill: "2+", strength: 6, ap: -3, damage: "2", abilities: [] },
      { name: "Power Fist", range: "Melee", attacks: "3", skill: "3+", strength: 8, ap: -2, damage: "2", abilities: [] },
      { name: "Lightning Claw", range: "Melee", attacks: "4", skill: "2+", strength: 5, ap: -2, damage: "1", abilities: ["Lethal Hits"] },
    ],
    abilities: [
      { name: "Assault Doctrine", description: "This unit is eligible to charge in a turn in which it Advanced." },
    ],
    invulnSave: "5+",
    points: 100, // 5 models
    models: 5,
    maxModels: 10,
    baseSize: "32mm round",
  },
  {
    id: "sm-eradicators",
    name: "Eradicators",
    faction: "space-marines",
    keywords: ["Infantry", "Phobos", "Eradicators"],
    factionKeywords: ["Adeptus Astartes"],
    stats: { movement: "5\"", toughness: 4, save: "3+", wounds: 3, leadership: "6+", oc: 1 },
    weapons: [
      { name: "Melta Rifle", range: "18\"", attacks: "1", skill: "3+", strength: 9, ap: -4, damage: "D6", abilities: ["Melta 2"] },
      { name: "Multi-melta", range: "18\"", attacks: "2", skill: "3+", strength: 9, ap: -4, damage: "D6", abilities: ["Melta 2"] },
    ],
    abilities: [
      { name: "Total Obliteration", description: "Each time this unit makes a ranged attack that targets a Monster or Vehicle unit, add 1 to the Wound roll." },
    ],
    points: 95, // 3 models
    models: 3,
    maxModels: 6,
    baseSize: "40mm round",
  },
  {
    id: "sm-hellblasters",
    name: "Hellblasters",
    faction: "space-marines",
    keywords: ["Infantry", "Hellblasters"],
    factionKeywords: ["Adeptus Astartes"],
    stats: { movement: "6\"", toughness: 4, save: "3+", wounds: 2, leadership: "6+", oc: 1 },
    weapons: [
      { name: "Plasma Incinerator (standard)", range: "30\"", attacks: "2", skill: "3+", strength: 7, ap: -3, damage: "2", abilities: [] },
      { name: "Plasma Incinerator (supercharge)", range: "30\"", attacks: "2", skill: "3+", strength: 8, ap: -4, damage: "3", abilities: ["Hazardous"] },
    ],
    abilities: [
      { name: "Fervent Acclamation", description: "Each time this unit is selected to shoot, if the unit is within range of an objective marker, add 1 to all Wound rolls for this unit's ranged attacks." },
    ],
    points: 95, // 5 models
    models: 5,
    maxModels: 10,
    baseSize: "32mm round",
  },
  {
    id: "sm-aggressors",
    name: "Aggressors",
    faction: "space-marines",
    keywords: ["Infantry", "Aggressors"],
    factionKeywords: ["Adeptus Astartes"],
    stats: { movement: "5\"", toughness: 5, save: "3+", wounds: 3, leadership: "6+", oc: 1 },
    weapons: [
      { name: "Auto Boltstorm Gauntlets", range: "18\"", attacks: "6", skill: "3+", strength: 4, ap: 0, damage: "1", abilities: ["Assault"] },
      { name: "Fragstorm Grenade Launcher", range: "18\"", attacks: "D6", skill: "3+", strength: 4, ap: 0, damage: "1", abilities: ["Blast"] },
      { name: "Powered Fists", range: "Melee", attacks: "3", skill: "3+", strength: 8, ap: -2, damage: "2", abilities: [] },
    ],
    abilities: [
      { name: "Relentless Advance", description: "This unit can shoot even if it Advanced this turn." },
    ],
    points: 90, // 3 models
    models: 3,
    maxModels: 6,
    baseSize: "40mm round",
  },
  {
    id: "sm-inceptors",
    name: "Inceptors",
    faction: "space-marines",
    keywords: ["Infantry", "Jump Pack", "Fly", "Inceptors"],
    factionKeywords: ["Adeptus Astartes"],
    stats: { movement: "12\"", toughness: 5, save: "3+", wounds: 3, leadership: "6+", oc: 1 },
    weapons: [
      { name: "Assault Bolters", range: "18\"", attacks: "6", skill: "3+", strength: 5, ap: -1, damage: "1", abilities: ["Pistol"] },
      { name: "Plasma Exterminators (standard)", range: "18\"", attacks: "4", skill: "3+", strength: 7, ap: -2, damage: "1", abilities: ["Pistol"] },
    ],
    abilities: [
      { name: "Crushing Impact", description: "Each time this unit makes a Charge move, at the end of the Charge move, select one enemy unit it made a Charge move against. Roll one D6 for each model in this unit: for each result of 4+, that enemy unit suffers 1 mortal wound." },
    ],
    points: 90, // 3 models
    models: 3,
    maxModels: 6,
    baseSize: "40mm round",
  },
  {
    id: "sm-infiltrators",
    name: "Infiltrators",
    faction: "space-marines",
    keywords: ["Infantry", "Phobos", "Infiltrators"],
    factionKeywords: ["Adeptus Astartes"],
    stats: { movement: "6\"", toughness: 4, save: "3+", wounds: 2, leadership: "6+", oc: 2 },
    weapons: [
      { name: "Marksman Bolt Carbine", range: "24\"", attacks: "2", skill: "3+", strength: 4, ap: -1, damage: "1", abilities: [] },
      { name: "Close Combat Weapon", range: "Melee", attacks: "2", skill: "3+", strength: 4, ap: 0, damage: "1", abilities: [] },
    ],
    abilities: [
      { name: "Concealed Position", description: "Infiltrators can be set up anywhere on the battlefield that is more than 9\" away from the enemy deployment zone and any enemy models." },
      { name: "Omni-scramblers", description: "Enemy units that are set up as Reinforcements cannot be set up within 12\" of this unit." },
    ],
    points: 100, // 5 models
    models: 5,
    maxModels: 10,
    baseSize: "32mm round",
  },
  {
    id: "sm-incursors",
    name: "Incursors",
    faction: "space-marines",
    keywords: ["Infantry", "Phobos", "Incursors"],
    factionKeywords: ["Adeptus Astartes"],
    stats: { movement: "6\"", toughness: 4, save: "3+", wounds: 2, leadership: "6+", oc: 2 },
    weapons: [
      { name: "Occulus Bolt Carbine", range: "24\"", attacks: "2", skill: "3+", strength: 4, ap: 0, damage: "1", abilities: ["Ignores Cover"] },
      { name: "Paired Combat Blades", range: "Melee", attacks: "3", skill: "3+", strength: 4, ap: 0, damage: "1", abilities: ["Twin-linked"] },
    ],
    abilities: [
      { name: "Scouts 6\"", description: "After deployment, this unit can make a Normal move of up to 6\" before the battle begins." },
    ],
    points: 100, // 5 models
    models: 5,
    maxModels: 10,
    baseSize: "32mm round",
  },
  {
    id: "sm-eliminators",
    name: "Eliminators",
    faction: "space-marines",
    keywords: ["Infantry", "Phobos", "Eliminators"],
    factionKeywords: ["Adeptus Astartes"],
    stats: { movement: "6\"", toughness: 4, save: "3+", wounds: 2, leadership: "6+", oc: 1 },
    weapons: [
      { name: "Eliminator Bolt Sniper Rifle (Executioner)", range: "36\"", attacks: "1", skill: "3+", strength: 5, ap: -3, damage: "3", abilities: ["Heavy", "Lethal Hits", "Precision"] },
      { name: "Eliminator Bolt Sniper Rifle (Mortis)", range: "36\"", attacks: "1", skill: "3+", strength: 5, ap: -2, damage: "2", abilities: ["Heavy", "Precision", "Devastating Wounds"] },
    ],
    abilities: [
      { name: "Camo Cloaks", description: "Each time a ranged attack targets this unit, the attacker's Hit rolls suffer a -1 penalty if this unit is not within 6\" of any friendly Adeptus Astartes units." },
      { name: "Surgical Strike", description: "Each time this unit shoots a Character unit, you can re-roll the Wound roll." },
    ],
    points: 75, // 3 models
    models: 3,
    maxModels: 6,
    baseSize: "32mm round",
  },
  {
    id: "sm-suppressors",
    name: "Suppressors",
    faction: "space-marines",
    keywords: ["Infantry", "Jump Pack", "Fly", "Phobos", "Suppressors"],
    factionKeywords: ["Adeptus Astartes"],
    stats: { movement: "12\"", toughness: 4, save: "3+", wounds: 2, leadership: "6+", oc: 1 },
    weapons: [
      { name: "Accelerator Autocannon", range: "48\"", attacks: "4", skill: "3+", strength: 7, ap: -1, damage: "2", abilities: ["Heavy"] },
    ],
    abilities: [
      { name: "Suppressing Fire", description: "Each time this unit destroys an enemy unit with a ranged attack, until the end of the battle round, that enemy unit's player cannot use Stratagems to affect the next unit they activate." },
    ],
    points: 75, // 3 models
    models: 3,
    maxModels: 3,
    baseSize: "32mm round",
  },
  {
    id: "sm-reivers",
    name: "Reivers",
    faction: "space-marines",
    keywords: ["Infantry", "Phobos", "Reivers"],
    factionKeywords: ["Adeptus Astartes"],
    stats: { movement: "8\"", toughness: 4, save: "3+", wounds: 2, leadership: "6+", oc: 1 },
    weapons: [
      { name: "Heavy Bolt Pistol", range: "18\"", attacks: "1", skill: "3+", strength: 4, ap: -1, damage: "1", abilities: ["Pistol"] },
      { name: "Combat Knife", range: "Melee", attacks: "4", skill: "3+", strength: 4, ap: -1, damage: "1", abilities: [] },
    ],
    abilities: [
      { name: "Terror Troops", description: "Each time this unit makes a Charge move, select one enemy unit it made a Charge move against. That unit must take a Battle-shock test." },
      { name: "Grapnel Launcher", description: "This unit has the Scouts 6\" and Deep Strike abilities." },
    ],
    points: 75, // 5 models
    models: 5,
    maxModels: 10,
    baseSize: "32mm round",
  },
  {
    id: "sm-outriders",
    name: "Outriders",
    faction: "space-marines",
    keywords: ["Mounted", "Outriders"],
    factionKeywords: ["Adeptus Astartes"],
    stats: { movement: "12\"", toughness: 5, save: "3+", wounds: 4, leadership: "6+", oc: 2 },
    weapons: [
      { name: "Twin Bolt Rifle", range: "30\"", attacks: "4", skill: "3+", strength: 4, ap: -1, damage: "1", abilities: ["Twin-linked"] },
      { name: "Astartes Chainsword", range: "Melee", attacks: "4", skill: "3+", strength: 4, ap: -1, damage: "1", abilities: [] },
    ],
    abilities: [
      { name: "Turbo-boost", description: "Each time this unit Advances, add 6\" to its Move characteristic for that move instead of rolling a dice." },
    ],
    points: 90, // 3 models
    models: 3,
    maxModels: 3,
    baseSize: "75mm oval",
  },
  {
    id: "sm-devastator-squad",
    name: "Devastator Squad",
    faction: "space-marines",
    keywords: ["Infantry", "Devastator Squad"],
    factionKeywords: ["Adeptus Astartes"],
    stats: { movement: "6\"", toughness: 4, save: "3+", wounds: 2, leadership: "6+", oc: 1 },
    weapons: [
      { name: "Heavy Bolter", range: "36\"", attacks: "3", skill: "3+", strength: 5, ap: -1, damage: "2", abilities: ["Sustained Hits 1", "Heavy"] },
      { name: "Lascannon", range: "48\"", attacks: "1", skill: "3+", strength: 12, ap: -3, damage: "D6+1", abilities: ["Heavy"] },
      { name: "Missile Launcher (frag)", range: "48\"", attacks: "D6", skill: "3+", strength: 5, ap: 0, damage: "1", abilities: ["Blast", "Heavy"] },
      { name: "Missile Launcher (krak)", range: "48\"", attacks: "1", skill: "3+", strength: 9, ap: -2, damage: "D6", abilities: ["Heavy"] },
    ],
    abilities: [
      { name: "Signum", description: "Once per Shooting phase, one model in this unit can use a Signum. If it does, one other model in the unit adds 1 to their Hit roll for the rest of the phase." },
    ],
    points: 95, // 5 models
    models: 5,
    maxModels: 10,
    baseSize: "32mm round",
  },

  // ========== VEHICLES ==========
  {
    id: "sm-rhino",
    name: "Rhino",
    faction: "space-marines",
    keywords: ["Vehicle", "Transport", "Rhino"],
    factionKeywords: ["Adeptus Astartes"],
    stats: { movement: "12\"", toughness: 9, save: "3+", wounds: 10, leadership: "6+", oc: 2 },
    weapons: [
      { name: "Storm Bolter", range: "24\"", attacks: "2", skill: "3+", strength: 4, ap: 0, damage: "1", abilities: ["Rapid Fire 2"] },
    ],
    abilities: [
      { name: "Smoke Launchers", description: "Once per game, at the start of your opponent's Shooting phase, this vehicle can use its Smoke Launchers. If it does, until the end of the phase, ranged attacks against this model suffer a -1 penalty to their Hit rolls." },
      { name: "Power of the Machine Spirit", description: "This vehicle is not subject to the penalty for moving and firing Heavy weapons." },
      { name: "Transport", description: "This vehicle can transport 10 Adeptus Astartes Infantry models." },
    ],
    damagedProfile: { wounds: 4, description: "While this model has 1–4 wounds remaining, each time this model makes a move, subtract 2\" from its Move characteristic." },
    points: 75,
    baseSize: "105mm oval",
    models: 1,
  },
  {
    id: "sm-predator-annihilator",
    name: "Predator Annihilator",
    faction: "space-marines",
    keywords: ["Vehicle", "Predator"],
    factionKeywords: ["Adeptus Astartes"],
    stats: { movement: "10\"", toughness: 10, save: "3+", wounds: 11, leadership: "6+", oc: 3 },
    weapons: [
      { name: "Twin Lascannon", range: "48\"", attacks: "2", skill: "3+", strength: 12, ap: -3, damage: "D6+1", abilities: ["Heavy", "Twin-linked"] },
      { name: "Lascannon (sponson)", range: "48\"", attacks: "1", skill: "3+", strength: 12, ap: -3, damage: "D6+1", abilities: ["Heavy"] },
    ],
    abilities: [
      { name: "Hunter of Hunters", description: "Each time this unit makes a ranged attack against a Monster or Vehicle unit, add 1 to the Hit roll." },
    ],
    damagedProfile: { wounds: 4, description: "While this model has 1–4 wounds remaining, subtract 4 from its Move characteristic and subtract 1 from its Hit rolls." },
    points: 130,
    baseSize: "105mm oval",
    models: 1,
  },
  {
    id: "sm-predator-destructor",
    name: "Predator Destructor",
    faction: "space-marines",
    keywords: ["Vehicle", "Predator"],
    factionKeywords: ["Adeptus Astartes"],
    stats: { movement: "10\"", toughness: 10, save: "3+", wounds: 11, leadership: "6+", oc: 3 },
    weapons: [
      { name: "Predator Autocannon", range: "48\"", attacks: "4", skill: "3+", strength: 7, ap: -1, damage: "3", abilities: ["Heavy", "Twin-linked"] },
      { name: "Heavy Bolter (sponson)", range: "36\"", attacks: "3", skill: "3+", strength: 5, ap: -1, damage: "2", abilities: ["Sustained Hits 1", "Heavy"] },
    ],
    abilities: [
      { name: "Armoured Superiority", description: "Each time this unit makes a ranged attack, an unmodified Hit roll of 6 scores one additional hit." },
    ],
    damagedProfile: { wounds: 4, description: "While this model has 1–4 wounds remaining, subtract 4 from its Move characteristic and subtract 1 from its Hit rolls." },
    points: 110,
    baseSize: "105mm oval",
    models: 1,
  },
  {
    id: "sm-land-raider",
    name: "Land Raider",
    faction: "space-marines",
    keywords: ["Vehicle", "Transport", "Land Raider"],
    factionKeywords: ["Adeptus Astartes"],
    stats: { movement: "10\"", toughness: 12, save: "2+", wounds: 16, leadership: "6+", oc: 5 },
    weapons: [
      { name: "Twin Heavy Bolter", range: "36\"", attacks: "6", skill: "3+", strength: 5, ap: -1, damage: "2", abilities: ["Sustained Hits 1"] },
      { name: "Twin Lascannon", range: "48\"", attacks: "2", skill: "3+", strength: 12, ap: -3, damage: "D6+1", abilities: ["Twin-linked"] },
    ],
    abilities: [
      { name: "Assault Ramp", description: "Units can disembark from this vehicle after it makes any kind of move." },
      { name: "Power of the Machine Spirit", description: "This vehicle is not subject to the penalty for moving and firing Heavy weapons." },
      { name: "Transport", description: "This vehicle can transport 10 Adeptus Astartes Infantry or Mounted models." },
    ],
    invulnSave: "5+",
    damagedProfile: { wounds: 6, description: "While this model has 1–6 wounds remaining, subtract 4 from its Move characteristic and subtract 1 from all Hit rolls." },
    points: 235,
    baseSize: "130mm oval",
    models: 1,
  },
  {
    id: "sm-land-raider-crusader",
    name: "Land Raider Crusader",
    faction: "space-marines",
    keywords: ["Vehicle", "Transport", "Land Raider"],
    factionKeywords: ["Adeptus Astartes"],
    stats: { movement: "10\"", toughness: 12, save: "2+", wounds: 16, leadership: "6+", oc: 5 },
    weapons: [
      { name: "Hurricane Bolter", range: "24\"", attacks: "12", skill: "3+", strength: 4, ap: 0, damage: "1", abilities: ["Rapid Fire 6"] },
      { name: "Twin Assault Cannon", range: "24\"", attacks: "12", skill: "3+", strength: 6, ap: 0, damage: "1", abilities: ["Devastating Wounds", "Twin-linked"] },
    ],
    abilities: [
      { name: "Frag Assault Launchers", description: "Each time a unit disembarks from this vehicle and declares a Charge, the unit can re-roll its Charge roll." },
      { name: "Transport", description: "This vehicle can transport 16 Adeptus Astartes Infantry models." },
    ],
    invulnSave: "5+",
    damagedProfile: { wounds: 6, description: "While this model has 1–6 wounds remaining, subtract 4 from its Move characteristic." },
    points: 250,
    baseSize: "130mm oval",
    models: 1,
  },
  {
    id: "sm-redemptor-dreadnought",
    name: "Redemptor Dreadnought",
    faction: "space-marines",
    keywords: ["Monster", "Walker", "Dreadnought"],
    factionKeywords: ["Adeptus Astartes"],
    stats: { movement: "8\"", toughness: 10, save: "2+", wounds: 12, leadership: "6+", oc: 3 },
    weapons: [
      { name: "Macro Plasma Incinerator (standard)", range: "36\"", attacks: "D6+2", skill: "3+", strength: 8, ap: -4, damage: "2", abilities: ["Blast"] },
      { name: "Macro Plasma Incinerator (supercharge)", range: "36\"", attacks: "D6+2", skill: "3+", strength: 9, ap: -5, damage: "3", abilities: ["Blast", "Hazardous"] },
      { name: "Onslaught Gatling Cannon", range: "24\"", attacks: "12", skill: "3+", strength: 6, ap: -1, damage: "1", abilities: [] },
      { name: "Redemptor Fist", range: "Melee", attacks: "5", skill: "3+", strength: 12, ap: -3, damage: "D6+1", abilities: [] },
    ],
    abilities: [
      { name: "Fury of the Ancients", description: "Each time this unit makes an attack, re-roll a Hit roll of 1." },
    ],
    invulnSave: "4+",
    damagedProfile: { wounds: 4, description: "While this model has 1–4 wounds remaining, subtract 4 from its Move characteristic and subtract 1 from its Weapon Skill." },
    points: 155,
    baseSize: "90mm oval",
    models: 1,
  },
  {
    id: "sm-brutalis-dreadnought",
    name: "Brutalis Dreadnought",
    faction: "space-marines",
    keywords: ["Monster", "Walker", "Dreadnought"],
    factionKeywords: ["Adeptus Astartes"],
    stats: { movement: "8\"", toughness: 10, save: "2+", wounds: 12, leadership: "6+", oc: 3 },
    weapons: [
      { name: "Brutalis Fists", range: "Melee", attacks: "6", skill: "3+", strength: 14, ap: -3, damage: "D6+1", abilities: ["Anti-Monster 4+", "Anti-Vehicle 4+"] },
      { name: "Brutalis Claws", range: "Melee", attacks: "6", skill: "3+", strength: 8, ap: -2, damage: "2", abilities: ["Anti-Infantry 4+"] },
      { name: "Multi-melta", range: "18\"", attacks: "2", skill: "3+", strength: 9, ap: -4, damage: "D6", abilities: ["Melta 2"] },
    ],
    abilities: [
      { name: "Brutally Efficient", description: "Each time this unit fights, if it made a Charge move this turn, add 1 to the Attacks characteristic of its weapons." },
    ],
    invulnSave: "4+",
    damagedProfile: { wounds: 4, description: "While this model has 1–4 wounds remaining, subtract 4 from its Move characteristic." },
    points: 155,
    baseSize: "90mm oval",
    models: 1,
  },
  {
    id: "sm-repulsor",
    name: "Repulsor",
    faction: "space-marines",
    keywords: ["Vehicle", "Transport", "Fly", "Repulsor"],
    factionKeywords: ["Adeptus Astartes"],
    stats: { movement: "10\"", toughness: 12, save: "3+", wounds: 14, leadership: "6+", oc: 3 },
    weapons: [
      { name: "Las-talon", range: "36\"", attacks: "2", skill: "3+", strength: 14, ap: -4, damage: "D6+2", abilities: ["Twin-linked"] },
      { name: "Macro-plasma Incinerator (standard)", range: "36\"", attacks: "D6+2", skill: "3+", strength: 8, ap: -4, damage: "2", abilities: ["Blast"] },
      { name: "Onslaught Gatling Cannon", range: "24\"", attacks: "12", skill: "3+", strength: 6, ap: -1, damage: "1", abilities: [] },
    ],
    abilities: [
      { name: "Hover Tank", description: "This vehicle ignores all terrain that is not Impassable." },
      { name: "Transport", description: "This vehicle can transport 10 Adeptus Astartes Primaris Infantry models." },
    ],
    invulnSave: "5+",
    damagedProfile: { wounds: 5, description: "While this model has 1–5 wounds remaining, subtract 4 from its Move characteristic and subtract 1 from all Hit rolls." },
    points: 210,
    baseSize: "130mm oval",
    models: 1,
  },
  {
    id: "sm-gladiator-lancer",
    name: "Gladiator Lancer",
    faction: "space-marines",
    keywords: ["Vehicle", "Fly", "Gladiator"],
    factionKeywords: ["Adeptus Astartes"],
    stats: { movement: "10\"", toughness: 10, save: "3+", wounds: 12, leadership: "6+", oc: 3 },
    weapons: [
      { name: "Lancer Laser Destroyer", range: "48\"", attacks: "1", skill: "3+", strength: 14, ap: -4, damage: "D6+4", abilities: ["Devastating Wounds", "Heavy"] },
      { name: "Icarus Rocket Pod", range: "24\"", attacks: "D3", skill: "3+", strength: 9, ap: -2, damage: "3", abilities: ["Anti-Fly 2+"] },
    ],
    abilities: [
      { name: "Aquilon Optics", description: "Each time this unit makes a ranged attack, you can ignore any or all penalties to the Hit roll." },
    ],
    invulnSave: "5+",
    damagedProfile: { wounds: 4, description: "While this model has 1–4 wounds remaining, subtract 4 from its Move characteristic." },
    points: 145,
    baseSize: "130mm oval",
    models: 1,
  },
  {
    id: "sm-stormraven",
    name: "Stormraven Gunship",
    faction: "space-marines",
    keywords: ["Vehicle", "Transport", "Fly", "Aircraft"],
    factionKeywords: ["Adeptus Astartes"],
    stats: { movement: "20\"", toughness: 10, save: "3+", wounds: 14, leadership: "6+", oc: 0 },
    weapons: [
      { name: "Twin Heavy Plasma Cannon (standard)", range: "36\"", attacks: "D6+2", skill: "3+", strength: 8, ap: -4, damage: "2", abilities: ["Blast"] },
      { name: "Hurricane Bolter", range: "24\"", attacks: "12", skill: "3+", strength: 4, ap: 0, damage: "1", abilities: ["Rapid Fire 6"] },
      { name: "Stormstrike Missile Launcher", range: "48\"", attacks: "2", skill: "3+", strength: 8, ap: -3, damage: "3", abilities: [] },
    ],
    abilities: [
      { name: "Airborne", description: "This model cannot be targeted by attacks from units that are not within 6\" of the target, unless they have Fly or the Skyfire special rule." },
      { name: "Hover", description: "At the start of the Movement phase, this model can switch to Hover mode. Until the start of your next Movement phase, treat it as a Vehicle without Fly and with a Move of 20\"." },
      { name: "Transport", description: "This vehicle can transport 12 Adeptus Astartes Infantry or Dreadnought models." },
    ],
    invulnSave: "5+",
    points: 260,
    baseSize: "120mm oval",
    models: 1,
  },
  {
    id: "sm-drop-pod",
    name: "Drop Pod",
    faction: "space-marines",
    keywords: ["Vehicle", "Transport", "Drop Pod"],
    factionKeywords: ["Adeptus Astartes"],
    stats: { movement: "0\"", toughness: 9, save: "3+", wounds: 8, leadership: "6+", oc: 0 },
    weapons: [
      { name: "Storm Bolter", range: "24\"", attacks: "2", skill: "3+", strength: 4, ap: 0, damage: "1", abilities: ["Rapid Fire 2"] },
    ],
    abilities: [
      { name: "Assault Vehicle", description: "Units that disembark from this vehicle in the same turn it arrives from Strategic Reserves can still declare a charge." },
      { name: "Transport", description: "This vehicle can transport 10 Adeptus Astartes Infantry models. Models cannot embark or disembark after the Drop Pod has landed." },
    ],
    points: 70,
    baseSize: "90mm oval",
    models: 1,
  },
];

// =============================================
// SPACE MARINES DETACHMENTS
// =============================================

export const GLADIUS_DETACHMENT: Detachment = {
  id: "gladius-task-force",
  name: "Gladius Task Force",
  faction: "space-marines",
  rule: {
    name: "Oath of Moment",
    description: "At the start of your Command phase, select one enemy unit on the battlefield. Until the start of your next Command phase, each time a friendly Adeptus Astartes unit makes an attack that targets that enemy unit, you can re-roll the Hit roll and you can re-roll the Wound roll.",
  },
  stratagems: [
    { name: "Adaptive Strategy", cost: 1, phase: "Command", when: "Your Command phase", target: "Your Warlord", effect: "Change your Oath of Moment target to a different enemy unit.", detachment: "gladius-task-force" },
    { name: "Transhuman Physiology", cost: 1, phase: "Any", when: "Your opponent's Shooting or your Fight phase", target: "One Adeptus Astartes Infantry unit", effect: "Until the end of the phase, each time an attack targets that unit, if the Strength of that attack is equal to or less than the Toughness of that unit, the Wound roll fails automatically.", detachment: "gladius-task-force" },
    { name: "Rapid Redeployment", cost: 1, phase: "Movement", when: "End of your Movement phase", target: "One Adeptus Astartes unit that did not make a Normal move or Advance this turn", effect: "Remove that unit from the battlefield. You can redeploy it anywhere wholly within your deployment zone.", detachment: "gladius-task-force" },
    { name: "Honour the Chapter", cost: 1, phase: "Fight", when: "Your Fight phase", target: "One Adeptus Astartes unit", effect: "Until the end of the phase, add 1 to the Attacks characteristic of models in that unit.", detachment: "gladius-task-force" },
    { name: "Only in Death Does Duty End", cost: 2, phase: "Any", when: "Your opponent's Shooting or Fight phase, just after an Adeptus Astartes unit has been destroyed", target: "The destroyed unit", effect: "That unit immediately shoots or fights as if it were your turn, but only using weapons with the Pistol ability if shooting.", detachment: "gladius-task-force" },
    { name: "Storm of Fire", cost: 1, phase: "Shooting", when: "Your Shooting phase", target: "One Adeptus Astartes unit", effect: "Until the end of the phase, each time a model in that unit makes a ranged attack, a successful Hit roll of 5+ scores one additional hit.", detachment: "gladius-task-force" },
  ],
  enhancements: [
    { name: "Adept of the Codex", points: 25, description: "The bearer can use one additional Stratagem each turn (not exceeding once per Stratagem per turn)." },
    { name: "The Honour Vehement", points: 20, description: "Add 1 to the bearer's Attacks characteristic. Each time the bearer makes a melee attack, add 1 to the Wound roll." },
    { name: "Artificer Armour", points: 10, description: "Improve the bearer's Save by 1 (to a minimum of 2+). The bearer has a 5+ invulnerable save." },
    { name: "Fire Discipline", points: 15, description: "While the bearer is on the battlefield, once per turn, when a friendly Adeptus Astartes unit within 6\" is selected to shoot, that unit can be treated as Stationary for the purposes of Heavy weapons." },
  ],
};

// =============================================
// SPACE MARINES FACTION
// =============================================

export const SPACE_MARINES_FACTION: Faction = {
  id: "space-marines",
  name: "Space Marines",
  color: "#3b82f6",
  secondaryColor: "#93c5fd",
  lore: "The Adeptus Astartes — genetically enhanced super-soldiers, the Emperor's finest warriors. Each Chapter fields a thousand warriors of extraordinary capability, equipped with the finest weapons and armour the Imperium can produce. Organized into companies and squads, they serve as the sword of the Imperium, striking at the enemies of Mankind across the galaxy.",
  playstyle: "Balanced and versatile. Oath of Moment provides consistent rerolls. Strong shooting and melee, excellent vehicle support. Adaptable to any playstyle.",
  detachments: [GLADIUS_DETACHMENT],
  units: SM_UNITS,
};
