import type { Unit, Faction, Detachment } from "./types";

export const SM_UNITS: Unit[] = [
  // ─── CHARACTERS ───────────────────────────────────────────────────
  {
    id: "sm-marneus-calgar",
    name: "Marneus Calgar",
    role: "Character",
    category: "HQ",
    isEpicHero: true,
    stats: { movement: '6"', toughness: 4, save: "2+/4++", wounds: 8, leadership: "5+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 160,
    weapons: [
      { name: "Gauntlets of Ultramar", type: "Ranged", range: '18"', attacks: "6", skill: "BS2+", strength: "4", ap: "-1", damage: "1" },
      { name: "Gauntlets of Ultramar", type: "Melee", attacks: "8", skill: "WS2+", strength: "8", ap: "-2", damage: "2" },
    ],
    abilities: [
      { name: "Chapter Master", description: "Re-roll hit and wound rolls of 1 for friendly Ultramarines CORE units within 6\"." },
      { name: "Adept of the Codex", description: "Once per battle, can be used to gain 1 additional Command Point." },
    ],
    keywords: ["Infantry", "Character", "Epic Hero", "Terminator", "Chapter Master", "Marneus Calgar"],
    factionKeywords: ["Adeptus Astartes", "Ultramarines"],
    canLeadUnits: ["sm-intercessors", "sm-tactical-squad", "sm-heavy-intercessors", "sm-bladeguard", "sm-sternguard", "sm-terminators", "sm-eradicators", "sm-hellblasters"],
  },
  {
    id: "sm-chief-librarian-tigurius",
    name: "Chief Librarian Tigurius",
    role: "Character",
    category: "HQ",
    isEpicHero: true,
    stats: { movement: '6"', toughness: 4, save: "3+/5++", wounds: 5, leadership: "5+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 95,
    weapons: [
      { name: "Force Sword", type: "Melee", attacks: "5", skill: "WS2+", strength: "6", ap: "-2", damage: "D3" },
      { name: "Bolt Pistol", type: "Pistol", range: '12"', attacks: "1", skill: "BS2+", strength: "4", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Psyker", description: "Can attempt to manifest 2 psychic powers per turn and deny 2 witchfire attempts." },
      { name: "Prescience", description: "Friendly CORE Ultramarines unit within 18\" can re-roll one dice per activation." },
    ],
    keywords: ["Infantry", "Character", "Epic Hero", "Psyker", "Librarian"],
    factionKeywords: ["Adeptus Astartes", "Ultramarines"],
    canLeadUnits: ["sm-intercessors", "sm-tactical-squad", "sm-heavy-intercessors", "sm-hellblasters"],
  },
  {
    id: "sm-captain",
    name: "Captain",
    role: "Character",
    category: "HQ",
    stats: { movement: '6"', toughness: 4, save: "3+/4++", wounds: 5, leadership: "5+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 80,
    weapons: [
      { name: "Master-Crafted Power Weapon", type: "Melee", attacks: "5", skill: "WS2+", strength: "5", ap: "-2", damage: "2" },
      { name: "Neo-volkite Pistol", type: "Pistol", range: '12"', attacks: "2", skill: "BS2+", strength: "5", ap: "0", damage: "2" },
    ],
    abilities: [
      { name: "Rites of Battle", description: "Re-roll hit rolls of 1 for friendly CORE Space Marine units within 6\"." },
      { name: "Lead from the Front", description: "Once per Fight phase, after this model fights, select one friendly unit within 6\" to fight next." },
    ],
    keywords: ["Infantry", "Character", "Captain"],
    factionKeywords: ["Adeptus Astartes"],
    wargearOptions: [
      { description: "May replace Neo-volkite Pistol with a Plasma Pistol (+5pts) or Combi-weapon (+10pts)." },
      { description: "May replace Master-Crafted Power Weapon with a Thunder Hammer (+10pts) or Power Fist (+5pts)." },
      { description: "May take a Storm Shield (+15pts) for a 4++ invulnerable save." },
    ],
    canLeadUnits: ["sm-intercessors", "sm-tactical-squad", "sm-heavy-intercessors", "sm-bladeguard", "sm-sternguard", "sm-terminators", "sm-eradicators", "sm-hellblasters"],
  },
  {
    id: "sm-librarian",
    name: "Librarian",
    role: "Character",
    category: "HQ",
    stats: { movement: '6"', toughness: 4, save: "3+/5++", wounds: 4, leadership: "5+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 75,
    weapons: [
      { name: "Force Weapon", type: "Melee", attacks: "4", skill: "WS3+", strength: "6", ap: "-1", damage: "D3" },
      { name: "Bolt Pistol", type: "Pistol", range: '12"', attacks: "1", skill: "BS3+", strength: "4", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Psyker", description: "Can attempt to manifest 1 psychic power per turn and deny 1 witchfire attempt." },
      { name: "Psychic Hood", description: "+1 to Deny attempts against Psykers within 12\"." },
    ],
    keywords: ["Infantry", "Character", "Psyker", "Librarian"],
    factionKeywords: ["Adeptus Astartes"],
    canLeadUnits: ["sm-intercessors", "sm-tactical-squad", "sm-heavy-intercessors", "sm-hellblasters"],
  },
  {
    id: "sm-chaplain",
    name: "Chaplain",
    role: "Character",
    category: "HQ",
    stats: { movement: '6"', toughness: 4, save: "3+", wounds: 4, leadership: "5+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 65,
    weapons: [
      { name: "Crozius Arcanum", type: "Melee", attacks: "4", skill: "WS2+", strength: "6", ap: "-1", damage: "2" },
      { name: "Absolvor Bolt Pistol", type: "Pistol", range: '18"', attacks: "1", skill: "BS2+", strength: "5", ap: "-1", damage: "2" },
    ],
    abilities: [
      { name: "Litany of Hate", description: "Re-roll hit rolls in Fight phase for friendly CORE units within 6\"." },
      { name: "Spiritual Leaders", description: "Friendly CORE units within 6\" never have to take Battleshock tests." },
    ],
    keywords: ["Infantry", "Character", "Chaplain"],
    factionKeywords: ["Adeptus Astartes"],
    canLeadUnits: ["sm-intercessors", "sm-tactical-squad", "sm-heavy-intercessors", "sm-bladeguard", "sm-terminators"],
  },
  {
    id: "sm-techmarine",
    name: "Techmarine",
    role: "Character",
    category: "HQ",
    stats: { movement: '6"', toughness: 4, save: "2+", wounds: 4, leadership: "5+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 65,
    weapons: [
      { name: "Servo-arm", type: "Melee", attacks: "2", skill: "WS3+", strength: "8", ap: "-2", damage: "3" },
      { name: "Servo-harness Plasma Cutter", type: "Melee", attacks: "2", skill: "WS3+", strength: "6", ap: "-2", damage: "2" },
      { name: "Bolt Pistol", type: "Pistol", range: '12"', attacks: "1", skill: "BS2+", strength: "4", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Blessing of the Omnissiah", description: "At the start of your Command Phase, can repair one friendly VEHICLE model within 3\", restoring up to D3 lost wounds." },
    ],
    keywords: ["Infantry", "Character", "Techmarine"],
    factionKeywords: ["Adeptus Astartes"],
  },
  {
    id: "sm-lieutenant",
    name: "Lieutenant",
    role: "Character",
    category: "HQ",
    stats: { movement: '6"', toughness: 4, save: "3+", wounds: 4, leadership: "5+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 70,
    weapons: [
      { name: "Master-Crafted Power Weapon", type: "Melee", attacks: "4", skill: "WS2+", strength: "5", ap: "-2", damage: "2" },
      { name: "Bolt Pistol", type: "Pistol", range: '12"', attacks: "1", skill: "BS2+", strength: "4", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Tactical Precision", description: "Wound rolls of 6+ for friendly CORE units within 6\" are critical wounds (AP -4)." },
    ],
    keywords: ["Infantry", "Character", "Lieutenant"],
    factionKeywords: ["Adeptus Astartes"],
    canLeadUnits: ["sm-intercessors", "sm-tactical-squad", "sm-heavy-intercessors", "sm-eradicators", "sm-hellblasters", "sm-bike-squad", "sm-inceptors"],
  },
  // ─── BATTLELINE ───────────────────────────────────────────────────
  {
    id: "sm-intercessors",
    name: "Intercessor Squad",
    role: "Infantry",
    category: "Battleline",
    stats: { movement: '6"', toughness: 4, save: "3+", wounds: 2, leadership: "6+", oc: 2 },
    models: { min: 5, max: 10 },
    points: 90,
    weapons: [
      { name: "Auto Bolt Rifle", type: "Assault", range: '24"', attacks: "2", skill: "BS3+", strength: "4", ap: "0", damage: "1" },
      { name: "Bolt Rifle", type: "Rapid Fire", range: '30"', attacks: "1", skill: "BS3+", strength: "4", ap: "-1", damage: "1" },
      { name: "Stalker Bolt Rifle", type: "Heavy", range: '36"', attacks: "1", skill: "BS3+", strength: "4", ap: "-2", damage: "2" },
      { name: "Close Combat Weapon", type: "Melee", attacks: "3", skill: "WS3+", strength: "4", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Objective Secured", description: "While this unit controls an objective marker, it is treated as having double the number of models for the purpose of that marker." },
    ],
    keywords: ["Infantry", "Core", "Battleline", "Intercessors"],
    factionKeywords: ["Adeptus Astartes"],
    wargearOptions: [
      { description: "All models may replace Bolt Rifle with Auto Bolt Rifle or Stalker Bolt Rifle." },
      { description: "Sergeant may take a Thunder Hammer, Power Fist, or Power Weapon." },
    ],
  },
  {
    id: "sm-tactical-squad",
    name: "Tactical Squad",
    role: "Infantry",
    category: "Battleline",
    stats: { movement: '6"', toughness: 4, save: "3+", wounds: 1, leadership: "6+", oc: 2 },
    models: { min: 5, max: 10 },
    points: 75,
    weapons: [
      { name: "Boltgun", type: "Rapid Fire", range: '24"', attacks: "1", skill: "BS3+", strength: "4", ap: "0", damage: "1" },
      { name: "Close Combat Weapon", type: "Melee", attacks: "2", skill: "WS3+", strength: "4", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Objective Secured", description: "While this unit controls an objective marker, it is treated as having double the number of models for the purpose of that marker." },
      { name: "Combat Squads", description: "Before deployment, can split into two 5-man units." },
    ],
    keywords: ["Infantry", "Core", "Battleline", "Tactical Squad"],
    factionKeywords: ["Adeptus Astartes"],
    wargearOptions: [
      { description: "One model may take a Special Weapon (Flamer, Meltagun, Plasma Gun)." },
      { description: "One model may take a Heavy Weapon (Heavy Bolter, Lascannon, Missile Launcher)." },
      { description: "Sergeant may take a Power Weapon, Plasma Pistol, or Combi-weapon." },
    ],
  },
  {
    id: "sm-heavy-intercessors",
    name: "Heavy Intercessor Squad",
    role: "Infantry",
    category: "Battleline",
    stats: { movement: '5"', toughness: 5, save: "3+", wounds: 3, leadership: "6+", oc: 2 },
    models: { min: 5, max: 10 },
    points: 100,
    weapons: [
      { name: "Heavy Bolt Rifle", type: "Heavy", range: '36"', attacks: "1", skill: "BS3+", strength: "5", ap: "-1", damage: "2" },
      { name: "Executor Bolt Rifle", type: "Heavy", range: '42"', attacks: "1", skill: "BS3+", strength: "5", ap: "-2", damage: "3" },
      { name: "Close Combat Weapon", type: "Melee", attacks: "3", skill: "WS3+", strength: "5", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Objective Secured", description: "While this unit controls an objective marker, it is treated as having double the number of models for the purpose of that marker." },
    ],
    keywords: ["Infantry", "Core", "Battleline", "Heavy Intercessors"],
    factionKeywords: ["Adeptus Astartes"],
  },
  // ─── ELITES ───────────────────────────────────────────────────────
  {
    id: "sm-terminators",
    name: "Terminator Squad",
    role: "Infantry",
    category: "Elites",
    canDeepStrike: true,
    stats: { movement: '5"', toughness: 5, save: "2+", wounds: 3, leadership: "6+", oc: 1 },
    models: { min: 5, max: 10 },
    points: 175,
    weapons: [
      { name: "Storm Bolter", type: "Rapid Fire", range: '24"', attacks: "2", skill: "BS3+", strength: "4", ap: "0", damage: "1" },
      { name: "Power Fist", type: "Melee", attacks: "3", skill: "WS3+", strength: "8", ap: "-2", damage: "2" },
    ],
    abilities: [
      { name: "Deep Strike", description: "Can be set up in Strategic Reserves. Can be set up anywhere more than 9\" from enemy models." },
      { name: "Teleport Homer", description: "Friendly Terminator units arriving from Deep Strike can be set up within 6\" of this unit." },
    ],
    keywords: ["Infantry", "Core", "Terminator", "Terminator Squad"],
    factionKeywords: ["Adeptus Astartes"],
    wargearOptions: [
      { description: "One model per 5 may replace Storm Bolter + Power Fist with Assault Cannon + Power Fist." },
      { description: "One model per 5 may replace Storm Bolter with a Heavy Flamer." },
      { description: "Sergeant may take a Thunder Hammer + Storm Shield." },
    ],
  },
  {
    id: "sm-sternguard",
    name: "Sternguard Veteran Squad",
    role: "Infantry",
    category: "Elites",
    stats: { movement: '6"', toughness: 4, save: "3+", wounds: 2, leadership: "6+", oc: 1 },
    models: { min: 5, max: 10 },
    points: 95,
    weapons: [
      { name: "Sternguard Bolt Rifle", type: "Assault", range: '30"', attacks: "2", skill: "BS2+", strength: "4", ap: "-2", damage: "1" },
      { name: "Close Combat Weapon", type: "Melee", attacks: "3", skill: "WS3+", strength: "4", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Veteran Marksmen", description: "This unit's ranged weapons have the Precision keyword." },
    ],
    keywords: ["Infantry", "Core", "Sternguard Veterans"],
    factionKeywords: ["Adeptus Astartes"],
  },
  {
    id: "sm-company-heroes",
    name: "Company Heroes",
    role: "Infantry",
    category: "Elites",
    stats: { movement: '6"', toughness: 4, save: "3+", wounds: 2, leadership: "6+", oc: 1 },
    models: { min: 5, max: 5 },
    points: 75,
    weapons: [
      { name: "Bolt Pistol", type: "Pistol", range: '12"', attacks: "1", skill: "BS3+", strength: "4", ap: "0", damage: "1" },
      { name: "Close Combat Weapon", type: "Melee", attacks: "3", skill: "WS3+", strength: "4", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Bodyguard", description: "While the unit this model is leading is targeted, roll a D6 each time a saving throw is failed. On a 4+, a Company Heroes model suffers the wound instead." },
    ],
    keywords: ["Infantry", "Core", "Company Heroes"],
    factionKeywords: ["Adeptus Astartes"],
  },
  {
    id: "sm-apothecary",
    name: "Apothecary",
    role: "Character",
    category: "Elites",
    stats: { movement: '6"', toughness: 4, save: "3+", wounds: 4, leadership: "5+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 55,
    weapons: [
      { name: "Absolvor Bolt Pistol", type: "Pistol", range: '18"', attacks: "1", skill: "BS2+", strength: "5", ap: "-1", damage: "2" },
      { name: "Close Combat Weapon", type: "Melee", attacks: "3", skill: "WS3+", strength: "4", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Narthecium", description: "Once per turn, at the end of your Movement Phase, one model in the unit this model leads regains up to D3 lost wounds, OR one slain model is returned." },
    ],
    keywords: ["Infantry", "Character", "Apothecary"],
    factionKeywords: ["Adeptus Astartes"],
    canLeadUnits: ["sm-intercessors", "sm-tactical-squad", "sm-heavy-intercessors", "sm-bladeguard", "sm-terminators"],
  },
  {
    id: "sm-bladeguard",
    name: "Bladeguard Veteran Squad",
    role: "Infantry",
    category: "Elites",
    stats: { movement: '6"', toughness: 4, save: "3+/4++", wounds: 3, leadership: "6+", oc: 1 },
    models: { min: 3, max: 6 },
    points: 115,
    weapons: [
      { name: "Master-Crafted Power Sword", type: "Melee", attacks: "4", skill: "WS2+", strength: "5", ap: "-3", damage: "2" },
      { name: "Heavy Bolt Pistol", type: "Pistol", range: '18"', attacks: "1", skill: "BS3+", strength: "4", ap: "-1", damage: "1" },
    ],
    abilities: [
      { name: "Bladeguard", description: "Each model in this unit has a Storm Shield, giving it a 4++ invulnerable save." },
    ],
    keywords: ["Infantry", "Core", "Bladeguard Veterans"],
    factionKeywords: ["Adeptus Astartes"],
  },
  // ─── FAST ATTACK ──────────────────────────────────────────────────
  {
    id: "sm-assault-marines",
    name: "Assault Marine Squad",
    role: "Infantry",
    category: "Fast Attack",
    stats: { movement: '12"', toughness: 4, save: "3+", wounds: 2, leadership: "6+", oc: 1 },
    models: { min: 5, max: 10 },
    points: 95,
    canFly: true,
    weapons: [
      { name: "Bolt Pistol", type: "Pistol", range: '12"', attacks: "1", skill: "BS3+", strength: "4", ap: "0", damage: "1" },
      { name: "Close Combat Weapon", type: "Melee", attacks: "3", skill: "WS3+", strength: "4", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Fly", description: "When this unit moves it can move over models and terrain, though it cannot end its move on top of another model." },
      { name: "Jump Pack Assault", description: "Each time this unit makes a charge move, do not roll for charge distance; instead this unit can move up to 6\" when it declares a charge." },
    ],
    keywords: ["Infantry", "Core", "Jump Pack", "Fly", "Assault Marines"],
    factionKeywords: ["Adeptus Astartes"],
    wargearOptions: [
      { description: "One model per 5 may take a Flamer or Plasma Pistol." },
      { description: "Sergeant may take a Power Weapon, Plasma Pistol, or Thunder Hammer." },
    ],
  },
  {
    id: "sm-bike-squad",
    name: "Outrider Squad",
    role: "Mounted",
    category: "Fast Attack",
    stats: { movement: '14"', toughness: 5, save: "3+", wounds: 4, leadership: "6+", oc: 2 },
    models: { min: 3, max: 6 },
    points: 130,
    weapons: [
      { name: "Outrider Bike Bolters", type: "Rapid Fire", range: '24"', attacks: "4", skill: "BS3+", strength: "4", ap: "0", damage: "1" },
      { name: "Close Combat Weapon", type: "Melee", attacks: "4", skill: "WS3+", strength: "5", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Turbo-boost", description: "When this unit Advances, add 6\" to its Move characteristic instead of rolling." },
    ],
    keywords: ["Mounted", "Core", "Outriders"],
    factionKeywords: ["Adeptus Astartes"],
  },
  {
    id: "sm-inceptors",
    name: "Inceptor Squad",
    role: "Infantry",
    category: "Fast Attack",
    canFly: true,
    stats: { movement: '10"', toughness: 5, save: "3+", wounds: 3, leadership: "6+", oc: 1 },
    models: { min: 3, max: 6 },
    points: 130,
    weapons: [
      { name: "Assault Bolter", type: "Assault", range: '18"', attacks: "3", skill: "BS3+", strength: "5", ap: "-1", damage: "1" },
      { name: "Close Combat Weapon", type: "Melee", attacks: "3", skill: "WS3+", strength: "5", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Fly", description: "This model can move over models and terrain." },
      { name: "Meteoric Descent", description: "Once per game, this unit can be set up anywhere on the battlefield more than 9\" from enemy models at the start of any Movement Phase." },
    ],
    keywords: ["Infantry", "Core", "Jump Pack", "Fly", "Inceptors"],
    factionKeywords: ["Adeptus Astartes"],
  },
  // ─── HEAVY SUPPORT ────────────────────────────────────────────────
  {
    id: "sm-devastator-squad",
    name: "Devastator Squad",
    role: "Infantry",
    category: "Heavy Support",
    stats: { movement: '6"', toughness: 4, save: "3+", wounds: 2, leadership: "6+", oc: 1 },
    models: { min: 5, max: 10 },
    points: 100,
    weapons: [
      { name: "Boltgun", type: "Rapid Fire", range: '24"', attacks: "1", skill: "BS3+", strength: "4", ap: "0", damage: "1" },
      { name: "Missile Launcher (Frag)", type: "Heavy", range: '48"', attacks: "D6", skill: "BS3+", strength: "5", ap: "0", damage: "1" },
      { name: "Missile Launcher (Krak)", type: "Heavy", range: '48"', attacks: "1", skill: "BS3+", strength: "9", ap: "-2", damage: "D6" },
      { name: "Lascannon", type: "Heavy", range: '48"', attacks: "1", skill: "BS3+", strength: "12", ap: "-3", damage: "D6+1" },
    ],
    abilities: [
      { name: "Signum", description: "One model in this unit can use a Signum. If it does, add 1 to the hit rolls of that unit's Heavy weapons this phase." },
    ],
    keywords: ["Infantry", "Core", "Devastators"],
    factionKeywords: ["Adeptus Astartes"],
    wargearOptions: [
      { description: "Up to 4 models may replace their Boltgun with a Heavy Weapon: Heavy Bolter, Lascannon, Missile Launcher, Multi-melta, Plasma Cannon." },
    ],
  },
  {
    id: "sm-predator-destructor",
    name: "Predator Destructor",
    role: "Vehicle",
    category: "Heavy Support",
    stats: { movement: '10"', toughness: 11, save: "3+", wounds: 11, leadership: "6+", oc: 3 },
    models: { min: 1, max: 1 },
    points: 130,
    weapons: [
      { name: "Predator Autocannon", type: "Heavy", range: '48"', attacks: "4", skill: "BS3+", strength: "9", ap: "-1", damage: "3" },
      { name: "Lascannon", type: "Heavy", range: '48"', attacks: "1", skill: "BS3+", strength: "12", ap: "-3", damage: "D6+1" },
      { name: "Heavy Bolter", type: "Heavy", range: '36"', attacks: "3", skill: "BS3+", strength: "5", ap: "-1", damage: "2" },
      { name: "Armoured Tracks", type: "Melee", attacks: "3", skill: "WS4+", strength: "7", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Smoke", description: "Once per battle, this model can use its smoke launchers. If it does, until the end of your opponent's next turn it gains the benefits of cover." },
    ],
    keywords: ["Vehicle", "Core", "Smoke", "Predator", "Predator Destructor"],
    factionKeywords: ["Adeptus Astartes"],
  },
  {
    id: "sm-land-raider",
    name: "Land Raider",
    role: "Vehicle",
    category: "Heavy Support",
    stats: { movement: '10"', toughness: 13, save: "2+", wounds: 16, leadership: "6+", oc: 4 },
    models: { min: 1, max: 1 },
    points: 245,
    weapons: [
      { name: "Twin Lascannon", type: "Heavy", range: '48"', attacks: "2", skill: "BS3+", strength: "12", ap: "-3", damage: "D6+1" },
      { name: "Multi-melta", type: "Heavy", range: '18"', attacks: "2", skill: "BS3+", strength: "9", ap: "-4", damage: "D6", keywords: ["Melta 2"] },
      { name: "Armoured Tracks", type: "Melee", attacks: "6", skill: "WS4+", strength: "9", ap: "-1", damage: "2" },
    ],
    abilities: [
      { name: "Assault Vehicle", description: "Units can disembark from this model after it has made a Normal Move. Units that do so cannot Charge." },
      { name: "Power of the Machine Spirit", description: "This model can shoot and charge even after Advancing." },
    ],
    keywords: ["Vehicle", "Core", "Smoke", "Transport", "Land Raider"],
    factionKeywords: ["Adeptus Astartes"],
  },
  {
    id: "sm-hellblasters",
    name: "Hellblaster Squad",
    role: "Infantry",
    category: "Heavy Support",
    stats: { movement: '6"', toughness: 4, save: "3+", wounds: 2, leadership: "6+", oc: 1 },
    models: { min: 5, max: 10 },
    points: 110,
    weapons: [
      { name: "Plasma Incinerator (Standard)", type: "Assault", range: '30"', attacks: "1", skill: "BS3+", strength: "7", ap: "-3", damage: "2" },
      { name: "Plasma Incinerator (Supercharge)", type: "Assault", range: '30"', attacks: "1", skill: "BS3+", strength: "8", ap: "-3", damage: "3", keywords: ["Hazardous"] },
      { name: "Close Combat Weapon", type: "Melee", attacks: "2", skill: "WS3+", strength: "4", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Rapid Fire (Plasma Incinerator)", description: "When Rapid Firing, this weapon fires an additional shot." },
    ],
    keywords: ["Infantry", "Core", "Hellblasters"],
    factionKeywords: ["Adeptus Astartes"],
  },
  {
    id: "sm-eradicators",
    name: "Eradicator Squad",
    role: "Infantry",
    category: "Heavy Support",
    stats: { movement: '5"', toughness: 5, save: "3+", wounds: 3, leadership: "6+", oc: 1 },
    models: { min: 3, max: 6 },
    points: 95,
    weapons: [
      { name: "Melta Rifle", type: "Heavy", range: '18"', attacks: "1", skill: "BS3+", strength: "9", ap: "-4", damage: "D6", keywords: ["Melta 2"] },
      { name: "Bolt Pistol", type: "Pistol", range: '12"', attacks: "1", skill: "BS3+", strength: "4", ap: "0", damage: "1" },
      { name: "Close Combat Weapon", type: "Melee", attacks: "3", skill: "WS3+", strength: "5", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Total Obliteration", description: "Each time this unit shoots, if it targets a Monster or Vehicle, add 1 to its attacks." },
    ],
    keywords: ["Infantry", "Core", "Eradicators"],
    factionKeywords: ["Adeptus Astartes"],
  },
  {
    id: "sm-dreadnought",
    name: "Dreadnought",
    role: "Vehicle",
    category: "Elites",
    stats: { movement: '6"', toughness: 9, save: "2+", wounds: 8, leadership: "6+", oc: 3 },
    models: { min: 1, max: 1 },
    points: 100,
    weapons: [
      { name: "Dreadnought Combat Weapon", type: "Melee", attacks: "5", skill: "WS3+", strength: "12", ap: "-2", damage: "3" },
      { name: "Multi-melta", type: "Heavy", range: '18"', attacks: "2", skill: "BS3+", strength: "9", ap: "-4", damage: "D6", keywords: ["Melta 2"] },
      { name: "Heavy Flamer", type: "Heavy", range: '12"', attacks: "D6", skill: "BS-", strength: "5", ap: "-1", damage: "1", keywords: ["Torrent"] },
    ],
    abilities: [
      { name: "Smoke", description: "Once per battle, this model can use its smoke launchers for cover benefit." },
    ],
    keywords: ["Vehicle", "Core", "Smoke", "Walker", "Dreadnought"],
    factionKeywords: ["Adeptus Astartes"],
    wargearOptions: [
      { description: "May replace Multi-melta with Assault Cannon, Heavy Plasma Cannon, or Twin Lascannon." },
      { description: "May replace Heavy Flamer with Storm Bolter." },
    ],
  },
  {
    id: "sm-ballistus-dreadnought",
    name: "Ballistus Dreadnought",
    role: "Vehicle",
    category: "Elites",
    stats: { movement: '8"', toughness: 9, save: "3+", wounds: 9, leadership: "5+", oc: 3 },
    models: { min: 1, max: 1 },
    points: 130,
    weapons: [
      { name: "Twin Lascannon", type: "Heavy", range: '48"', attacks: "2", skill: "BS3+", strength: "12", ap: "-3", damage: "D6+2" },
      { name: "Missile Launcher (Krak)", type: "Heavy", range: '48"', attacks: "2", skill: "BS3+", strength: "8", ap: "-2", damage: "D6" },
      { name: "Missile Launcher (Frag)", type: "Heavy", range: '48"', attacks: "6", skill: "BS3+", strength: "4", ap: "0", damage: "1" },
      { name: "Twin Bolt Rifle", type: "Rapid Fire", range: '24"', attacks: "2", skill: "BS3+", strength: "4", ap: "0", damage: "1" },
      { name: "Armoured Tracks", type: "Melee", attacks: "3", skill: "WS4+", strength: "7", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Lethal Hits", description: "Unmodified hit rolls of 6 with this model's weapons are critical hits." },
      { name: "Smoke", description: "Once per battle, this model can use its smoke launchers for cover benefit." },
    ],
    keywords: ["Vehicle", "Core", "Smoke", "Walker", "Dreadnought", "Ballistus Dreadnought"],
    factionKeywords: ["Adeptus Astartes"],
  },
  {
    id: "sm-brutalis-dreadnought",
    name: "Brutalis Dreadnought",
    role: "Vehicle",
    category: "Elites",
    stats: { movement: '8"', toughness: 10, save: "3+", wounds: 12, leadership: "5+", oc: 3 },
    models: { min: 1, max: 1 },
    points: 170,
    weapons: [
      { name: "Twin Multi-melta", type: "Heavy", range: '18"', attacks: "2", skill: "BS3+", strength: "9", ap: "-4", damage: "D6", keywords: ["Melta 3"] },
      { name: "Twin Bolt Rifle", type: "Rapid Fire", range: '24"', attacks: "2", skill: "BS3+", strength: "4", ap: "0", damage: "1" },
      { name: "Brutalis Fists", type: "Melee", attacks: "5", skill: "WS3+", strength: "12", ap: "-3", damage: "3" },
      { name: "Brutalis Talons", type: "Melee", attacks: "5", skill: "WS3+", strength: "7", ap: "-2", damage: "2" },
    ],
    abilities: [
      { name: "Bludgeon", description: "Unmodified wound rolls of 6 with Brutalis Fists inflict 3 additional mortal wounds." },
      { name: "Inescapable Wrath", description: "This model is eligible to charge even when it Advanced this turn." },
      { name: "Smoke", description: "Once per battle, this model can use its smoke launchers for cover benefit." },
    ],
    keywords: ["Vehicle", "Core", "Smoke", "Walker", "Dreadnought", "Brutalis Dreadnought"],
    factionKeywords: ["Adeptus Astartes"],
    wargearOptions: [
      { description: "May replace Twin Multi-melta with Twin Bolt Rifle." },
    ],
  },
  {
    id: "sm-venerable-dreadnought",
    name: "Venerable Dreadnought",
    role: "Vehicle",
    category: "Elites",
    stats: { movement: '6"', toughness: 9, save: "2+", wounds: 8, leadership: "5+", oc: 3 },
    models: { min: 1, max: 1 },
    points: 155,
    weapons: [
      { name: "Multi-melta", type: "Heavy", range: '18"', attacks: "2", skill: "BS2+", strength: "9", ap: "-4", damage: "D6", keywords: ["Melta 2"] },
      { name: "Lascannon", type: "Heavy", range: '48"', attacks: "1", skill: "BS2+", strength: "12", ap: "-3", damage: "D6+1" },
      { name: "Dreadnought Combat Weapon", type: "Melee", attacks: "5", skill: "WS2+", strength: "12", ap: "-3", damage: "3" },
    ],
    abilities: [
      { name: "Ancient Warrior", description: "Once per phase, re-roll one hit roll and one wound roll for this model's attacks." },
      { name: "Smoke", description: "Once per battle, this model can use its smoke launchers for cover benefit." },
    ],
    keywords: ["Vehicle", "Core", "Smoke", "Walker", "Dreadnought", "Venerable Dreadnought"],
    factionKeywords: ["Adeptus Astartes"],
    wargearOptions: [
      { description: "May replace Multi-melta with Lascannon." },
    ],
  },
  {
    id: "sm-contemptor-dreadnought",
    name: "Contemptor Dreadnought",
    role: "Vehicle",
    category: "Elites",
    stats: { movement: '8"', toughness: 10, save: "2+", wounds: 9, leadership: "5+", oc: 3 },
    models: { min: 1, max: 1 },
    points: 135,
    weapons: [
      { name: "Kheres Assault Cannon", type: "Heavy", range: '24"', attacks: "6", skill: "BS3+", strength: "7", ap: "-1", damage: "2" },
      { name: "Dreadnought Combat Weapon", type: "Melee", attacks: "5", skill: "WS3+", strength: "12", ap: "-2", damage: "3" },
    ],
    abilities: [
      { name: "Smoke", description: "Once per battle, this model can use its smoke launchers for cover benefit." },
    ],
    keywords: ["Vehicle", "Core", "Smoke", "Walker", "Dreadnought", "Contemptor Dreadnought"],
    factionKeywords: ["Adeptus Astartes"],
  },
  {
    id: "sm-ironclad-dreadnought",
    name: "Ironclad Dreadnought",
    role: "Vehicle",
    category: "Heavy Support",
    stats: { movement: '6"', toughness: 10, save: "2+", wounds: 8, leadership: "5+", oc: 3 },
    models: { min: 1, max: 1 },
    points: 150,
    weapons: [
      { name: "Seismic Hammer", type: "Melee", attacks: "3", skill: "WS2+", strength: "14", ap: "-3", damage: "D6" },
      { name: "Hurricane Bolter", type: "Rapid Fire", range: '24"', attacks: "6", skill: "BS4+", strength: "4", ap: "0", damage: "1" },
      { name: "Meltagun", type: "Heavy", range: '9"', attacks: "1", skill: "BS3+", strength: "9", ap: "-4", damage: "D6", keywords: ["Melta 2"] },
      { name: "Dreadnought Combat Weapon", type: "Melee", attacks: "5", skill: "WS3+", strength: "12", ap: "-2", damage: "3" },
    ],
    abilities: [
      { name: "Siege Fighter", description: "This model ignores the effects of difficult terrain and can move through walls of terrain features." },
      { name: "Smoke", description: "Once per battle, this model can use its smoke launchers for cover benefit." },
    ],
    keywords: ["Vehicle", "Core", "Smoke", "Walker", "Dreadnought", "Ironclad Dreadnought"],
    factionKeywords: ["Adeptus Astartes"],
    wargearOptions: [
      { description: "May replace Seismic Hammer + Hurricane Bolter with Dreadnought Combat Weapon + Meltagun." },
    ],
  },
  {
    id: "sm-leviathan-dreadnought",
    name: "Leviathan Dreadnought",
    role: "Vehicle",
    category: "Heavy Support",
    stats: { movement: '6"', toughness: 12, save: "2+/4++", wounds: 14, leadership: "5+", oc: 3 },
    models: { min: 1, max: 1 },
    points: 280,
    weapons: [
      { name: "Storm Cannon Array", type: "Heavy", range: '24"', attacks: "14", skill: "BS3+", strength: "7", ap: "-2", damage: "2" },
      { name: "Siege Drills", type: "Melee", attacks: "4", skill: "WS2+", strength: "16", ap: "-4", damage: "D6+2" },
    ],
    abilities: [
      { name: "Feel No Pain 5+++", description: "Each time a wound is allocated to this model, roll a D6; on a 5+ that wound is ignored." },
      { name: "Smoke", description: "Once per battle, this model can use its smoke launchers for cover benefit." },
    ],
    keywords: ["Vehicle", "Core", "Smoke", "Walker", "Dreadnought", "Leviathan Dreadnought"],
    factionKeywords: ["Adeptus Astartes"],
    wargearOptions: [
      { description: "May replace Storm Cannon Arrays with Siege Drills." },
    ],
  },
  {
    id: "sm-redemptor-dreadnought",
    name: "Redemptor Dreadnought",
    role: "Vehicle",
    category: "Elites",
    stats: { movement: '8"', toughness: 10, save: "3+", wounds: 12, leadership: "5+", oc: 3 },
    models: { min: 1, max: 1 },
    points: 185,
    weapons: [
      { name: "Macro Plasma Incinerator (Standard)", type: "Heavy", range: '36"', attacks: "5", skill: "BS3+", strength: "8", ap: "-3", damage: "3" },
      { name: "Macro Plasma Incinerator (Supercharge)", type: "Heavy", range: '36"', attacks: "5", skill: "BS3+", strength: "9", ap: "-4", damage: "4", keywords: ["Hazardous"] },
      { name: "Onslaught Gatling Cannon", type: "Heavy", range: '24"', attacks: "12", skill: "BS3+", strength: "6", ap: "-1", damage: "2" },
      { name: "Icarus Rocket Pod", type: "Heavy", range: '24"', attacks: "2", skill: "BS3+", strength: "8", ap: "-1", damage: "2" },
      { name: "Redemptor Fist", type: "Melee", attacks: "5", skill: "WS3+", strength: "14", ap: "-3", damage: "D3+3" },
    ],
    abilities: [
      { name: "Smoke", description: "Once per battle, this model can use its smoke launchers for cover benefit." },
    ],
    keywords: ["Vehicle", "Core", "Smoke", "Walker", "Dreadnought", "Redemptor Dreadnought"],
    factionKeywords: ["Adeptus Astartes"],
    wargearOptions: [
      { description: "May replace Macro Plasma Incinerator with Onslaught Gatling Cannon." },
    ],
  },
  // ─── LORD OF WAR ─────────────────────────────────────────────────
  {
    id: "sm-roboute-guilliman",
    name: "Roboute Guilliman",
    role: "Character",
    category: "Lord of War",
    isEpicHero: true,
    isTitanic: false,
    stats: { movement: '6"', toughness: 6, save: "2+/3++", wounds: 9, leadership: "4+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 380,
    weapons: [
      { name: "Hand of Dominion (Shooting)", type: "Ranged", range: '24"', attacks: "6", skill: "BS2+", strength: "6", ap: "-1", damage: "2" },
      { name: "Hand of Dominion (Melee)", type: "Melee", attacks: "6", skill: "WS2+", strength: "8", ap: "-2", damage: "3" },
      { name: "Emperor's Sword", type: "Melee", attacks: "7", skill: "WS2+", strength: "9", ap: "-4", damage: "D6" },
    ],
    abilities: [
      { name: "Primarch of the XIII Legion", description: "Re-roll all hit and wound rolls for friendly Ultramarines CORE units within 12\"." },
      { name: "Supreme Commander", description: "This model can issue 3 orders per turn. Friendly Ultramarines officers can also issue an additional order per turn." },
      { name: "Inspiring Presence", description: "Friendly units within 6\" auto-pass Battleshock tests." },
    ],
    keywords: ["Infantry", "Character", "Epic Hero", "Primarch", "Roboute Guilliman"],
    factionKeywords: ["Adeptus Astartes", "Ultramarines"],
    canLeadUnits: ["sm-intercessors", "sm-tactical-squad", "sm-heavy-intercessors", "sm-bladeguard", "sm-sternguard", "sm-terminators", "sm-eradicators", "sm-hellblasters", "sm-devastator-squad", "sm-assault-marines", "sm-bike-squad", "sm-inceptors"],
  },
];

const GLADIUS_DETACHMENT: Detachment = {
  name: "Gladius Task Force",
  rule: {
    name: "Sons of the Primarch",
    description: "Each time a CORE unit from this detachment shoots or fights, if the unit has not moved this turn, it gets +1 to all hit rolls. If the unit is within 6\" of an officer CHARACTER, it also re-rolls wound rolls of 1.",
  },
  stratagems: [
    {
      name: "Honour the Chapter",
      cost: 1,
      phase: "Fight",
      description: "Use at the start of the Fight phase. One friendly Adeptus Astartes unit within 6\" of a CHARACTER gets +1 Attack until the end of the phase.",
    },
    {
      name: "Adaptive Strategy",
      cost: 1,
      phase: "Command",
      description: "Use at the start of your Command Phase. One friendly CORE unit can discard its current doctrine and immediately gain the benefits of any other doctrine instead.",
    },
    {
      name: "Armour of Contempt",
      cost: 1,
      phase: "Any",
      description: "Use when a friendly Adeptus Astartes CORE unit takes a wound. Roll a D6; on a 5+, that wound is ignored.",
    },
    {
      name: "Rapid Deployment",
      cost: 1,
      phase: "Movement",
      description: "Use at the start of your Movement Phase. One CORE unit that has not yet moved this turn can immediately make a free 6\" Normal Move.",
    },
    {
      name: "Fire Discipline",
      cost: 1,
      phase: "Shooting",
      description: "Use before a CORE unit shoots. That unit's weapons with the Heavy keyword gain the benefit of cover for the remainder of the shooting phase.",
    },
    {
      name: "Orbital Bombardment",
      cost: 2,
      phase: "Command",
      description: "Once per battle, at the start of your Command Phase. Pick one point on the battlefield. Until end of turn, all enemy units within 6\" of that point are -1 to hit with ranged weapons.",
    },
  ],
  enhancements: [
    {
      name: "Artificer Armour",
      points: 10,
      description: "The bearer's save is improved by 1 (e.g. 3+ becomes 2+). Additionally, the bearer has a 5++ invulnerable save.",
      restriction: "Adeptus Astartes CHARACTER",
    },
    {
      name: "The Armour Indomitus",
      points: 20,
      description: "The bearer has a 2+ save and 4++ invulnerable save. When this bearer is targeted by a ranged attack, reduce the AP of the weapon by 1.",
      restriction: "Adeptus Astartes CHARACTER",
    },
    {
      name: "Seal of Oath",
      points: 15,
      description: "At the start of each battle round, pick an enemy unit. Until start of next battle round, friendly Adeptus Astartes units re-roll wound rolls against that unit.",
      restriction: "Adeptus Astartes CHARACTER",
    },
    {
      name: "Warlord Trait: Storm of Fire",
      points: 0,
      description: "Once per battle, at the start of the Shooting phase, friendly Adeptus Astartes CORE units within 6\" of the bearer may re-roll all hit rolls until the end of the phase.",
      restriction: "Adeptus Astartes CHARACTER",
    },
  ],
};

export const SPACE_MARINES_FACTION: Faction = {
  id: "space-marines",
  name: "Space Marines",
  shortName: "SM",
  description: "The Emperor's Angels of Death. Genetically-enhanced superhuman warriors clad in power armour, the Space Marines are humanity's greatest defenders.",
  accentColor: "#1e40af",
  units: SM_UNITS,
  detachments: [GLADIUS_DETACHMENT],
};
