import type { Unit, Faction, Detachment } from "./types";

export const NECRON_UNITS: Unit[] = [
  // ─── CHARACTERS ───────────────────────────────────────────────────
  {
    id: "nec-silent-king",
    name: "The Silent King",
    role: "Monster",
    category: "Lord of War",
    isEpicHero: true,
    isTitanic: false,
    stats: { movement: '8"', toughness: 12, save: "2+/4++", wounds: 18, leadership: "3+", oc: 5 },
    models: { min: 1, max: 1 },
    points: 440,
    weapons: [
      { name: "Sceptre of Eternal Glory", type: "Melee", attacks: "6", skill: "WS2+", strength: "16", ap: "-4", damage: "D6+2" },
      { name: "Annihilator Beam", type: "Heavy", range: '36"', attacks: "3", skill: "BS2+", strength: "16", ap: "-4", damage: "6" },
    ],
    abilities: [
      { name: "Lord of the Necrons", description: "Friendly Necron units on the board re-roll hit rolls of 1 and wound rolls of 1." },
      { name: "Triarch's Will", description: "At the start of your Command Phase, issue one Triarch's Command to any friendly Necron unit within 18\": either Advance and shoot, or fight twice." },
      { name: "Unstoppable Monolith", description: "Each time an attack is made against this model, that attack only wounds this model on an unmodified wound roll of 4+, regardless of the weapon's Strength." },
      { name: "Living Metal", description: "At the start of your Command Phase, this model regains 1 lost wound." },
    ],
    keywords: ["Monster", "Character", "Epic Hero", "Necron Royalty", "The Silent King"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-imotekh",
    name: "Imotekh the Stormlord",
    role: "Character",
    category: "HQ",
    isEpicHero: true,
    stats: { movement: '6"', toughness: 5, save: "2+/4++", wounds: 6, leadership: "3+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 95,
    weapons: [
      { name: "Staff of the Destroyer", type: "Melee", attacks: "5", skill: "WS2+", strength: "7", ap: "-2", damage: "3" },
      { name: "Gauntlet of Fire", type: "Pistol", range: '12"', attacks: "6", skill: "BS-", strength: "5", ap: "-1", damage: "1", keywords: ["Torrent"] },
    ],
    abilities: [
      { name: "Lord of the Sautekh", description: "Friendly Sautekh Necron CORE units within 6\" re-roll hit rolls of 1." },
      { name: "Hyperlogical Strategy", description: "While Imotekh is on the battlefield, all friendly Necron units get +1 to all hit rolls." },
      { name: "Living Metal", description: "At the start of your Command Phase, this model regains 1 lost wound." },
      { name: "Lord of the Storm", description: "Once per battle round, at the start of the Shooting phase, all enemy units on the battlefield suffer 1 mortal wound on a roll of 6+." },
    ],
    keywords: ["Infantry", "Character", "Epic Hero", "Necron Royalty", "Overlord", "Imotekh"],
    factionKeywords: ["Necrons", "Sautekh"],
  },
  {
    id: "nec-overlord",
    name: "Overlord",
    role: "Character",
    category: "HQ",
    stats: { movement: '6"', toughness: 5, save: "2+", wounds: 5, leadership: "3+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 80,
    weapons: [
      { name: "Staff of Light (Ranged)", type: "Assault", range: '18"', attacks: "3", skill: "BS2+", strength: "5", ap: "-2", damage: "1" },
      { name: "Staff of Light (Melee)", type: "Melee", attacks: "3", skill: "WS2+", strength: "5", ap: "-2", damage: "1" },
      { name: "Voidscythe", type: "Melee", attacks: "3", skill: "WS2+", strength: "10", ap: "-3", damage: "3" },
    ],
    abilities: [
      { name: "My Will Be Done", description: "Re-roll hit rolls of 1 and wound rolls of 1 for one friendly Necron CORE unit within 6\" each Command Phase." },
      { name: "Living Metal", description: "At the start of your Command Phase, this model regains 1 lost wound." },
    ],
    keywords: ["Infantry", "Character", "Necron Royalty", "Overlord"],
    factionKeywords: ["Necrons"],
    wargearOptions: [
      { description: "May replace Staff of Light with a Voidscythe." },
      { description: "May take a Resurrection Orb (+15pts): once per battle, at the end of any phase, a friendly Necron INFANTRY unit within 6\" immediately triggers Reanimation Protocols." },
    ],
  },
  {
    id: "nec-cryptek",
    name: "Cryptek",
    role: "Character",
    category: "HQ",
    stats: { movement: '6"', toughness: 4, save: "3+", wounds: 4, leadership: "3+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 55,
    weapons: [
      { name: "Arkana Conduit", type: "Melee", attacks: "3", skill: "WS3+", strength: "5", ap: "-2", damage: "1" },
    ],
    abilities: [
      { name: "Rites of Reanimation", description: "+1 to Reanimation Protocol rolls for a friendly Necron INFANTRY unit within 6\" at the end of each phase." },
      { name: "Technomancer Variant", description: "Friendly Necron VEHICLE units within 6\" regain D3 lost wounds at the start of your Command Phase instead of 1." },
      { name: "Living Metal", description: "At the start of your Command Phase, this model regains 1 lost wound." },
    ],
    keywords: ["Infantry", "Character", "Cryptek", "Technomancer"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-lokhust-lord",
    name: "Lokhust Lord",
    role: "Character",
    category: "HQ",
    canFly: true,
    stats: { movement: '10"', toughness: 6, save: "3+", wounds: 5, leadership: "3+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 75,
    weapons: [
      { name: "Staff of Light (Ranged)", type: "Assault", range: '18"', attacks: "3", skill: "BS2+", strength: "5", ap: "-2", damage: "1" },
      { name: "Warscythe", type: "Melee", attacks: "4", skill: "WS2+", strength: "7", ap: "-2", damage: "2" },
    ],
    abilities: [
      { name: "Relentless March", description: "Friendly Lokhust Destroyer units within 9\" can Advance and shoot as if they had not Advanced." },
      { name: "Fly", description: "This model can move over models and terrain." },
      { name: "Living Metal", description: "At the start of your Command Phase, this model regains 1 lost wound." },
    ],
    keywords: ["Infantry", "Character", "Fly", "Lokhust", "Overlord"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-royal-warden",
    name: "Royal Warden",
    role: "Character",
    category: "HQ",
    stats: { movement: '6"', toughness: 5, save: "2+", wounds: 4, leadership: "3+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 45,
    weapons: [
      { name: "Relic Gauss Blaster", type: "Assault", range: '30"', attacks: "3", skill: "BS2+", strength: "5", ap: "-2", damage: "2" },
      { name: "Close Combat Weapon", type: "Melee", attacks: "2", skill: "WS3+", strength: "5", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Adaptive Strategy", description: "A friendly unit led by the Royal Warden can either fire Pistols in the Fight phase OR make a 6\" Consolidation move after fighting." },
    ],
    keywords: ["Infantry", "Character", "Necron Royalty"],
    factionKeywords: ["Necrons"],
  },
  // ─── BATTLELINE ───────────────────────────────────────────────────
  {
    id: "nec-warriors-flayer",
    name: "Necron Warriors (Gauss Flayer)",
    role: "Infantry",
    category: "Battleline",
    stats: { movement: '6"', toughness: 4, save: "4+", wounds: 1, leadership: "7+", oc: 2 },
    models: { min: 10, max: 20 },
    points: 130,
    weapons: [
      { name: "Gauss Flayer", type: "Rapid Fire", range: '24"', attacks: "1", skill: "BS3+", strength: "4", ap: "-1", damage: "1" },
      { name: "Close Combat Weapon", type: "Melee", attacks: "1", skill: "WS3+", strength: "4", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Reanimation Protocols", description: "At the end of any phase, roll a D6 for each model destroyed. On a 5+, that model is returned with 1 wound remaining. On a 3+, if a friendly CRYPTEK is within 6\"." },
      { name: "Living Metal", description: "At the start of your Command Phase, this unit regains 1 lost wound (one model heals or is partially restored)." },
    ],
    keywords: ["Infantry", "Core", "Battleline", "Necron Warriors"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-warriors-reaper",
    name: "Necron Warriors (Gauss Reaper)",
    role: "Infantry",
    category: "Battleline",
    stats: { movement: '6"', toughness: 4, save: "4+", wounds: 1, leadership: "7+", oc: 2 },
    models: { min: 10, max: 20 },
    points: 130,
    weapons: [
      { name: "Gauss Reaper", type: "Assault", range: '18"', attacks: "2", skill: "BS3+", strength: "5", ap: "-2", damage: "1" },
      { name: "Close Combat Weapon", type: "Melee", attacks: "1", skill: "WS3+", strength: "4", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Reanimation Protocols", description: "At the end of any phase, roll a D6 for each model destroyed. On a 5+, that model is returned with 1 wound remaining. On a 3+, if a friendly CRYPTEK is within 6\"." },
      { name: "Living Metal", description: "At the start of your Command Phase, this unit regains 1 lost wound." },
    ],
    keywords: ["Infantry", "Core", "Battleline", "Necron Warriors"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-immortals-blaster",
    name: "Immortals (Gauss Blaster)",
    role: "Infantry",
    category: "Battleline",
    stats: { movement: '6"', toughness: 4, save: "3+", wounds: 1, leadership: "7+", oc: 1 },
    models: { min: 5, max: 10 },
    points: 85,
    weapons: [
      { name: "Gauss Blaster", type: "Rapid Fire", range: '24"', attacks: "1", skill: "BS3+", strength: "5", ap: "-2", damage: "2" },
      { name: "Close Combat Weapon", type: "Melee", attacks: "1", skill: "WS3+", strength: "4", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Reanimation Protocols", description: "At the end of any phase, roll a D6 for each model destroyed. On a 5+, that model is returned." },
      { name: "Living Metal", description: "Regains 1 wound per Command Phase." },
    ],
    keywords: ["Infantry", "Core", "Battleline", "Immortals"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-immortals-tesla",
    name: "Immortals (Tesla Carbine)",
    role: "Infantry",
    category: "Battleline",
    stats: { movement: '6"', toughness: 4, save: "3+", wounds: 1, leadership: "7+", oc: 1 },
    models: { min: 5, max: 10 },
    points: 85,
    weapons: [
      { name: "Tesla Carbine", type: "Assault", range: '24"', attacks: "2", skill: "BS3+", strength: "5", ap: "0", damage: "1", keywords: ["Sustained Hits 2"] },
      { name: "Close Combat Weapon", type: "Melee", attacks: "1", skill: "WS3+", strength: "4", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Reanimation Protocols", description: "At the end of any phase, roll a D6 for each model destroyed. On a 5+, that model is returned." },
      { name: "Living Metal", description: "Regains 1 wound per Command Phase." },
    ],
    keywords: ["Infantry", "Core", "Battleline", "Immortals"],
    factionKeywords: ["Necrons"],
  },
  // ─── ELITES ───────────────────────────────────────────────────────
  {
    id: "nec-lychguard-warscythes",
    name: "Lychguard (Warscythes)",
    role: "Infantry",
    category: "Elites",
    stats: { movement: '6"', toughness: 5, save: "3+", wounds: 2, leadership: "6+", oc: 1 },
    models: { min: 5, max: 10 },
    points: 95,
    weapons: [
      { name: "Warscythe", type: "Melee", attacks: "3", skill: "WS3+", strength: "7", ap: "-2", damage: "2" },
    ],
    abilities: [
      { name: "Reanimation Protocols", description: "At the end of any phase, roll a D6 for each destroyed model; on a 5+, it is returned." },
      { name: "Living Metal", description: "Regains 1 wound per Command Phase." },
    ],
    keywords: ["Infantry", "Core", "Lychguard"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-lychguard-shields",
    name: "Lychguard (Hyperphase Swords & Dispersion Shields)",
    role: "Infantry",
    category: "Elites",
    stats: { movement: '6"', toughness: 5, save: "3+/4++", wounds: 2, leadership: "6+", oc: 1 },
    models: { min: 5, max: 10 },
    points: 105,
    weapons: [
      { name: "Hyperphase Sword", type: "Melee", attacks: "3", skill: "WS3+", strength: "5", ap: "-2", damage: "1" },
    ],
    abilities: [
      { name: "Dispersion Shield", description: "This unit has a 4++ invulnerable save from Dispersion Shields." },
      { name: "Reanimation Protocols", description: "At the end of any phase, roll a D6 for each destroyed model; on a 5+, it is returned." },
      { name: "Living Metal", description: "Regains 1 wound per Command Phase." },
    ],
    keywords: ["Infantry", "Core", "Lychguard"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-deathmarks",
    name: "Deathmarks",
    role: "Infantry",
    category: "Elites",
    canDeepStrike: true,
    stats: { movement: '6"', toughness: 4, save: "3+", wounds: 1, leadership: "7+", oc: 1 },
    models: { min: 5, max: 10 },
    points: 75,
    weapons: [
      { name: "Synaptic Disintegrator", type: "Heavy", range: '36"', attacks: "1", skill: "BS3+", strength: "5", ap: "-2", damage: "2", keywords: ["Precision"] },
    ],
    abilities: [
      { name: "Ethereal Interception", description: "This unit can be placed in Hyperspace instead of deploying normally. At the start of any turn (including turn 1), they can arrive anywhere on the battlefield more than 9\" from enemy models." },
      { name: "Hunter's Mark", description: "When deployed or at the start of your Shooting phase, choose one visible enemy unit. Until end of phase, this unit's attacks get +1 to wound against that unit." },
      { name: "Reanimation Protocols", description: "At the end of any phase, roll D6 for each destroyed model; on 5+, returned." },
    ],
    keywords: ["Infantry", "Core", "Deathmarks"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-flayed-ones",
    name: "Flayed Ones",
    role: "Infantry",
    category: "Elites",
    canDeepStrike: true,
    stats: { movement: '6"', toughness: 4, save: "4+", wounds: 2, leadership: "7+", oc: 1 },
    models: { min: 5, max: 20 },
    points: 60,
    weapons: [
      { name: "Flayer Claws", type: "Melee", attacks: "4", skill: "WS3+", strength: "4", ap: "-1", damage: "1" },
    ],
    abilities: [
      { name: "Infiltrators", description: "Before the first battle round, this unit can be set up anywhere on the battlefield more than 9\" from the enemy deployment zone and any enemy models." },
      { name: "Terrifying", description: "Enemy units within 3\" of this unit are -1 to hit in the Fight phase." },
      { name: "Reanimation Protocols", description: "At the end of any phase, roll D6 for each destroyed model; on 5+, returned." },
    ],
    keywords: ["Infantry", "Core", "Infiltrators", "Flayed Ones"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-triarch-praetorians",
    name: "Triarch Praetorians (Rods of Covenant)",
    role: "Infantry",
    category: "Elites",
    canFly: true,
    stats: { movement: '8"', toughness: 5, save: "3+/4++", wounds: 2, leadership: "5+", oc: 1 },
    models: { min: 5, max: 10 },
    points: 100,
    weapons: [
      { name: "Rod of Covenant (Ranged)", type: "Assault", range: '12"', attacks: "2", skill: "BS3+", strength: "6", ap: "-2", damage: "2" },
      { name: "Rod of Covenant (Melee)", type: "Melee", attacks: "2", skill: "WS3+", strength: "6", ap: "-2", damage: "2" },
    ],
    abilities: [
      { name: "Fly", description: "This unit can move over models and terrain." },
      { name: "Eternal Covenant", description: "This unit can Heroically Intervene up to 6\" (instead of 3\") and fights before non-Fights First units." },
      { name: "Reanimation Protocols", description: "At the end of any phase, roll D6 for each destroyed model; on 5+, returned." },
    ],
    keywords: ["Infantry", "Core", "Fly", "Triarch Praetorians"],
    factionKeywords: ["Necrons"],
  },
  // ─── HEAVY SUPPORT ────────────────────────────────────────────────
  {
    id: "nec-doomsday-ark",
    name: "Doomsday Ark",
    role: "Vehicle",
    category: "Heavy Support",
    canFly: true,
    stats: { movement: '8"', toughness: 11, save: "3+", wounds: 12, leadership: "6+", oc: 3 },
    models: { min: 1, max: 1 },
    points: 195,
    weapons: [
      { name: "Doomsday Cannon (Stationary)", type: "Heavy", range: '72"', attacks: "1", skill: "BS3+", strength: "20", ap: "-5", damage: "7" },
      { name: "Doomsday Cannon (Moved)", type: "Heavy", range: '72"', attacks: "1", skill: "BS4+", strength: "14", ap: "-4", damage: "5" },
      { name: "Gauss Flayer Arrays", type: "Heavy", range: '24"', attacks: "5", skill: "BS3+", strength: "4", ap: "-1", damage: "1" },
    ],
    abilities: [
      { name: "Hovering", description: "This model can move over models and terrain as if it had the Fly keyword." },
      { name: "Living Metal", description: "At the start of your Command Phase, this model regains 1 lost wound." },
    ],
    keywords: ["Vehicle", "Core", "Fly", "Hover", "Doomsday Ark"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-annihilation-barge",
    name: "Annihilation Barge",
    role: "Vehicle",
    category: "Heavy Support",
    canFly: true,
    stats: { movement: '12"', toughness: 9, save: "3+", wounds: 8, leadership: "6+", oc: 3 },
    models: { min: 1, max: 1 },
    points: 115,
    weapons: [
      { name: "Tesla Destructor", type: "Heavy", range: '24"', attacks: "6", skill: "BS3+", strength: "7", ap: "-2", damage: "2", keywords: ["Sustained Hits 2"] },
      { name: "Gauss Cannon", type: "Heavy", range: '24"', attacks: "2", skill: "BS3+", strength: "6", ap: "-2", damage: "3" },
    ],
    abilities: [
      { name: "Living Metal", description: "At the start of your Command Phase, this model regains 1 lost wound." },
      { name: "Fly", description: "This model can move over models and terrain." },
    ],
    keywords: ["Vehicle", "Core", "Fly", "Annihilation Barge"],
    factionKeywords: ["Necrons"],
  },
  // ─── ADDITIONAL CHARACTERS ────────────────────────────────────────
  {
    id: "nec-hexmark-destroyer",
    name: "Hexmark Destroyer",
    role: "Character",
    category: "HQ",
    isEpicHero: true,
    stats: { movement: '5"', toughness: 5, save: "3+", wounds: 5, leadership: "6+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 85,
    weapons: [
      { name: "Enmitic Disintegrator Pistols (×6)", type: "Pistol", range: '12"', attacks: "6", skill: "BS2+", strength: "5", ap: "-2", damage: "1", keywords: ["Devastating Wounds"] },
      { name: "Hardwired Weapons", type: "Melee", attacks: "3", skill: "WS3+", strength: "5", ap: "-1", damage: "1" },
    ],
    abilities: [
      { name: "Whirling Onslaught", description: "When this model is selected to fight, it makes 1 attack for each enemy model within 1\" of it with each Enmitic Pistol (up to 6 pistol attacks total per model in range), instead of the normal attacks characteristic." },
      { name: "Point Blank Fusillade", description: "Each time an enemy unit Charges this model, before the charge is resolved, this model may immediately shoot at the charging unit (using its pistols)." },
    ],
    keywords: ["Infantry", "Character", "Epic Hero", "Hexmark Destroyer"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-skorpekh-lord",
    name: "Skorpekh Lord",
    role: "Character",
    category: "HQ",
    stats: { movement: '7"', toughness: 6, save: "3+", wounds: 7, leadership: "6+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 100,
    weapons: [
      { name: "Flensing Claw", type: "Melee", attacks: "5", skill: "WS2+", strength: "8", ap: "-3", damage: "2" },
      { name: "Hyperphase Harvester", type: "Melee", attacks: "2", skill: "WS2+", strength: "12", ap: "-4", damage: "D3+1", keywords: ["Devastating Wounds"] },
    ],
    abilities: [
      { name: "Whirling Onslaught (Melee)", description: "Each time this model charges or is charged, it gains +2 Attacks until end of the subsequent Fight phase." },
      { name: "Dirge of Annihilation", description: "Friendly Skorpekh Destroyers within 6\" re-roll wound rolls of 1 in the Fight phase." },
    ],
    keywords: ["Infantry", "Character", "Skorpekh", "Skorpekh Lord"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-transcendent-ctan",
    name: "Transcendent C'tan",
    role: "Monster",
    category: "HQ",
    isEpicHero: true,
    stats: { movement: '8"', toughness: 10, save: "4+/4++", wounds: 12, leadership: "7+", oc: 3 },
    models: { min: 1, max: 1 },
    points: 310,
    weapons: [
      { name: "Fractured Divinity (Melee)", type: "Melee", attacks: "8", skill: "WS2+", strength: "10", ap: "-4", damage: "3", keywords: ["Devastating Wounds"] },
      { name: "Fractured Divinity (Ranged)", type: "Heavy", range: '24"', attacks: "D6+3", skill: "BS2+", strength: "10", ap: "-3", damage: "D3" },
    ],
    abilities: [
      { name: "Writhing Worldscape", description: "All terrain features within 12\" of this model are treated as having the Difficult Ground trait for enemy units." },
      { name: "Necrodermis", description: "This model has a 4++ invulnerable save. The first time this model would be destroyed, roll a D6: on a 4+ it survives with 1 wound remaining." },
      { name: "Cosmic Powers", description: "At the start of your Shooting phase, choose one: (1) Deal D3 mortal wounds to every enemy unit within 12\", or (2) One enemy unit within 24\" must subtract 2 from its Leadership until your next Command phase." },
    ],
    keywords: ["Monster", "Character", "Epic Hero", "C'tan", "Transcendent C'tan"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-chronomancer",
    name: "Chronomancer",
    role: "Character",
    category: "HQ",
    stats: { movement: '5"', toughness: 4, save: "4+", wounds: 4, leadership: "6+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 65,
    weapons: [
      { name: "Aeonstave", type: "Melee", attacks: "3", skill: "WS3+", strength: "5", ap: "-2", damage: "D3", keywords: ["Devastating Wounds"] },
      { name: "Entropic Lance", type: "Heavy", range: '24"', attacks: "1", skill: "BS3+", strength: "9", ap: "-4", damage: "3" },
    ],
    abilities: [
      { name: "Temporal Snares", description: "Enemy units within 6\" of this model cannot Fall Back unless they pass a Leadership test." },
      { name: "Chronometron", description: "Once per turn, this model can cause one friendly Necron unit within 6\" to ignore Modifiers to its move for that phase (it moves as if it did not Advance)." },
    ],
    keywords: ["Infantry", "Character", "Cryptek", "Chronomancer"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-plasmancer",
    name: "Plasmancer",
    role: "Character",
    category: "HQ",
    stats: { movement: '5"', toughness: 4, save: "4+", wounds: 4, leadership: "6+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 65,
    weapons: [
      { name: "Plasmic Lance", type: "Heavy", range: '24"', attacks: "D3+3", skill: "BS3+", strength: "7", ap: "-2", damage: "2", keywords: ["Blast"] },
      { name: "Crackling Tendrils", type: "Melee", attacks: "3", skill: "WS3+", strength: "4", ap: "-1", damage: "1", keywords: ["Devastating Wounds"] },
    ],
    abilities: [
      { name: "Ball of Energy", description: "At the start of your Shooting phase, each enemy unit within 6\" of this model suffers 1 mortal wound on a roll of 4+ (roll separately for each unit)." },
    ],
    keywords: ["Infantry", "Character", "Cryptek", "Plasmancer"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-psychomancer",
    name: "Psychomancer",
    role: "Character",
    category: "HQ",
    stats: { movement: '5"', toughness: 4, save: "4+", wounds: 4, leadership: "6+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 60,
    weapons: [
      { name: "Abyssal Lance", type: "Heavy", range: '24"', attacks: "2", skill: "BS3+", strength: "8", ap: "-3", damage: "D3" },
      { name: "Husk Blade", type: "Melee", attacks: "3", skill: "WS3+", strength: "4", ap: "-1", damage: "D3", keywords: ["Devastating Wounds"] },
    ],
    abilities: [
      { name: "Harbinger of Despair", description: "Enemy units within 12\" of this model must subtract 2 from their Leadership characteristic." },
      { name: "Nightmare Shroud", description: "Once per turn, in the enemy Shooting phase, select one enemy unit within 12\". That unit must re-roll hit rolls of 6 until end of phase." },
    ],
    keywords: ["Infantry", "Character", "Cryptek", "Psychomancer"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-technomancer",
    name: "Technomancer",
    role: "Character",
    category: "HQ",
    stats: { movement: '5"', toughness: 4, save: "4+", wounds: 4, leadership: "6+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 70,
    weapons: [
      { name: "Staff of Light", type: "Heavy", range: '18"', attacks: "3", skill: "BS3+", strength: "5", ap: "-2", damage: "1" },
      { name: "Mechatendrils", type: "Melee", attacks: "3", skill: "WS3+", strength: "4", ap: "-1", damage: "1" },
    ],
    abilities: [
      { name: "Master of Machines", description: "At the start of your Command Phase, select one friendly Necron VEHICLE within 3\": it regains D3 lost wounds OR, if it has been destroyed, on a 5+ it is returned with 1 wound remaining." },
      { name: "Reanimation Protocols Booster", description: "Friendly Necron CORE units within 6\" add +1 to their Reanimation Protocol rolls." },
    ],
    keywords: ["Infantry", "Character", "Cryptek", "Technomancer"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-trazyn",
    name: "Trazyn the Infinite",
    role: "Character",
    category: "HQ",
    isEpicHero: true,
    stats: { movement: '5"', toughness: 4, save: "3+/4++", wounds: 5, leadership: "6+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 90,
    weapons: [
      { name: "Empathic Obliterator", type: "Melee", attacks: "4", skill: "WS2+", strength: "6", ap: "-3", damage: "D3", keywords: ["Precision"] },
    ],
    abilities: [
      { name: "Surrogate Hosts", description: "When this model would be destroyed, roll a D6 for each friendly Necron CHARACTER within 12\": on a 2+, this model is not destroyed and instead 'inhabits' one of those CHARACTER models (remove from play; the CHARACTER becomes Trazyn's host until it is also destroyed)." },
      { name: "Extensive Collection", description: "At the start of the battle, choose one Necron keyword unit in your army other than Trazyn. That unit gains the Relentless keyword and re-rolls all hit rolls of 1 this game." },
    ],
    keywords: ["Infantry", "Character", "Epic Hero", "Overlord", "Trazyn the Infinite"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-orikan",
    name: "Orikan the Diviner",
    role: "Character",
    category: "HQ",
    isEpicHero: true,
    stats: { movement: '5"', toughness: 4, save: "3+/4++", wounds: 5, leadership: "6+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 90,
    weapons: [
      { name: "The Staff of Tomorrow", type: "Melee", attacks: "4", skill: "WS2+", strength: "6", ap: "-2", damage: "2" },
      { name: "Temporal Staff (Ranged)", type: "Heavy", range: '18"', attacks: "2", skill: "BS2+", strength: "5", ap: "-2", damage: "1", keywords: ["Devastating Wounds"] },
    ],
    abilities: [
      { name: "Empowered Form", description: "From the start of battle round 3, this model's stats improve: Attacks +3, Strength +4, Save 2+, Wounds +3. It also gains the Monster keyword." },
      { name: "Stellar Alignment", description: "At the start of each battle round, choose one friendly Necron unit within 12\": until end of round that unit may re-roll one dice roll of your choice." },
    ],
    keywords: ["Infantry", "Character", "Epic Hero", "Cryptek", "Orikan the Diviner"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-illuminor-szeras",
    name: "Illuminor Szeras",
    role: "Character",
    category: "HQ",
    isEpicHero: true,
    stats: { movement: '8"', toughness: 6, save: "3+", wounds: 8, leadership: "6+", oc: 2 },
    models: { min: 1, max: 1 },
    points: 145,
    weapons: [
      { name: "Eldritch Lance", type: "Heavy", range: '36"', attacks: "3", skill: "BS2+", strength: "10", ap: "-4", damage: "D6" },
      { name: "Mechanical Claw", type: "Melee", attacks: "4", skill: "WS2+", strength: "8", ap: "-3", damage: "2" },
    ],
    abilities: [
      { name: "Mechanical Augmentation", description: "At the start of your Command Phase, select one friendly Necron CORE unit within 6\": choose one — that unit gains +1 to its Attacks, Strength or Save characteristic until your next Command Phase." },
      { name: "Gaze of Hyper-Phase", description: "At the start of the Fight phase, all enemy models within 1\" of this model must take a Leadership test: on a failure, they fight last this phase." },
    ],
    keywords: ["Infantry", "Character", "Epic Hero", "Cryptek", "Illuminor Szeras"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-catacomb-command-barge",
    name: "Catacomb Command Barge",
    role: "Vehicle",
    category: "HQ",
    canFly: true,
    stats: { movement: '12"', toughness: 8, save: "3+", wounds: 10, leadership: "6+", oc: 3 },
    models: { min: 1, max: 1 },
    points: 155,
    weapons: [
      { name: "Tesla Cannon", type: "Heavy", range: '24"', attacks: "4", skill: "BS3+", strength: "6", ap: "-1", damage: "1", keywords: ["Sustained Hits 2"] },
      { name: "Gauss Cannon", type: "Heavy", range: '30"', attacks: "3", skill: "BS3+", strength: "6", ap: "-2", damage: "2" },
      { name: "Staff of Light (Mounted)", type: "Melee", attacks: "4", skill: "WS3+", strength: "5", ap: "-2", damage: "1" },
    ],
    abilities: [
      { name: "Dynastic Protocols (Vehicle)", description: "If a friendly Necron OVERLORD is embarked or leading from this model, all friendly Necron CORE units within 6\" re-roll hit rolls of 1." },
      { name: "Living Metal", description: "At the start of your Command Phase, this model regains 1 lost wound." },
      { name: "Fly", description: "This model can move over models and terrain." },
    ],
    keywords: ["Vehicle", "Fly", "Catacomb Command Barge"],
    factionKeywords: ["Necrons"],
  },
  // ─── ELITES ───────────────────────────────────────────────────────
  {
    id: "nec-skorpekh-destroyers",
    name: "Skorpekh Destroyers",
    role: "Infantry",
    category: "Elites",
    stats: { movement: '7"', toughness: 5, save: "3+", wounds: 3, leadership: "6+", oc: 1 },
    models: { min: 3, max: 6 },
    points: 105,
    weapons: [
      { name: "Hyperphase Reap-Blade", type: "Melee", attacks: "3", skill: "WS3+", strength: "7", ap: "-3", damage: "2", keywords: ["Lethal Hits"] },
      { name: "Hyperphase Threshers", type: "Melee", attacks: "4", skill: "WS3+", strength: "6", ap: "-2", damage: "1", keywords: ["Sustained Hits 1"] },
    ],
    abilities: [
      { name: "Whirling Onslaught", description: "Each time this unit Charges, it gains +1 Attack per model until end of the subsequent Fight phase." },
      { name: "Reanimation Protocols", description: "At the start of your Command Phase, roll one D6 for each wound marker on this unit: for each 5+, restore 1 wound." },
    ],
    keywords: ["Infantry", "Core", "Destroyer", "Skorpekh", "Skorpekh Destroyers"],
    factionKeywords: ["Necrons"],
    wargearOptions: [
      { description: "One model per 3 may be a Plasmacyte Carrier (see Canoptek Plasmacyte rules)." },
    ],
  },
  {
    id: "nec-canoptek-plasmacyte",
    name: "Canoptek Plasmacyte",
    role: "Beast",
    category: "Elites",
    stats: { movement: '8"', toughness: 4, save: "4+", wounds: 2, leadership: "8+", oc: 0 },
    models: { min: 1, max: 1 },
    points: 15,
    weapons: [
      { name: "Plasmic Lash", type: "Melee", attacks: "2", skill: "WS4+", strength: "4", ap: "-1", damage: "1" },
    ],
    abilities: [
      { name: "Visceral Infusion", description: "Once per turn, when a friendly Necron DESTROYER unit within 3\" fights in melee, before resolving its attacks, that unit gains +1 Strength and +1 Attack until end of phase." },
      { name: "Canoptek Companion", description: "This model must be set up within 3\" of a friendly Destroyer unit and must stay within 3\"." },
    ],
    keywords: ["Beast", "Canoptek", "Canoptek Plasmacyte"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-cryptothralls",
    name: "Cryptothralls",
    role: "Infantry",
    category: "Elites",
    stats: { movement: '5"', toughness: 4, save: "3+", wounds: 2, leadership: "8+", oc: 1 },
    models: { min: 2, max: 2 },
    points: 40,
    weapons: [
      { name: "Scouring Eye", type: "Assault", range: '12"', attacks: "2", skill: "BS3+", strength: "4", ap: "-1", damage: "1" },
      { name: "Thrall Claws", type: "Melee", attacks: "3", skill: "WS3+", strength: "5", ap: "-1", damage: "1" },
    ],
    abilities: [
      { name: "Cryptek Bodyguard", description: "This unit must be set up within 3\" of a friendly Cryptek model. While a Cryptek model is within 3\" of this unit, each time an attack targets that Cryptek model, you may roll a D6 on a 2+: that attack is resolved against this unit instead." },
      { name: "Reanimation Protocols", description: "At the start of your Command Phase, roll one D6 for each wound marker on this unit: for each 5+, restore 1 wound." },
    ],
    keywords: ["Infantry", "Core", "Canoptek", "Cryptothralls"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-triarch-stalker",
    name: "Triarch Stalker",
    role: "Vehicle",
    category: "Elites",
    stats: { movement: '8"', toughness: 9, save: "3+", wounds: 10, leadership: "6+", oc: 3 },
    models: { min: 1, max: 1 },
    points: 140,
    weapons: [
      { name: "Heat Ray", type: "Heavy", range: '18"', attacks: "D6+1", skill: "BS3+", strength: "8", ap: "-4", damage: "D3" },
      { name: "Particle Shredder", type: "Heavy", range: '36"', attacks: "3", skill: "BS3+", strength: "7", ap: "-1", damage: "D3" },
      { name: "Twin Heavy Gauss Cannon", type: "Heavy", range: '36"', attacks: "4", skill: "BS3+", strength: "9", ap: "-4", damage: "D3+3" },
      { name: "Massive Claws", type: "Melee", attacks: "4", skill: "WS3+", strength: "12", ap: "-3", damage: "D6" },
    ],
    abilities: [
      { name: "Targeting Relay", description: "While this model is within line of sight of a friendly Necron unit, that unit re-rolls hit rolls of 1 against the same target as this model's last attack." },
      { name: "Living Metal", description: "At the start of your Command Phase, this model regains 1 lost wound." },
    ],
    keywords: ["Vehicle", "Walker", "Triarch", "Triarch Stalker"],
    factionKeywords: ["Necrons"],
    wargearOptions: [
      { description: "Replace Heat Ray with Particle Shredder or Twin Heavy Gauss Cannon." },
    ],
  },
  {
    id: "nec-canoptek-spyders",
    name: "Canoptek Spyders",
    role: "Beast",
    category: "Elites",
    stats: { movement: '8"', toughness: 7, save: "3+", wounds: 5, leadership: "7+", oc: 2 },
    models: { min: 1, max: 3 },
    points: 75,
    weapons: [
      { name: "Automaton Claws", type: "Melee", attacks: "4", skill: "WS3+", strength: "8", ap: "-2", damage: "D3" },
      { name: "Particle Projector", type: "Heavy", range: '18"', attacks: "2", skill: "BS3+", strength: "7", ap: "-1", damage: "1" },
    ],
    abilities: [
      { name: "Scarab Hive", description: "At the start of your Command Phase, add D3 Canoptek Scarab Swarm bases to one friendly Canoptek Scarab Swarms unit within 6\" of this model." },
      { name: "Fabricator Claw Array", description: "At the start of your Command Phase, select one friendly Necron VEHICLE within 3\": it regains 1 lost wound." },
    ],
    keywords: ["Beast", "Canoptek", "Canoptek Spyders"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-canoptek-wraiths",
    name: "Canoptek Wraiths",
    role: "Beast",
    category: "Elites",
    stats: { movement: '9"', toughness: 5, save: "4+/4++", wounds: 3, leadership: "7+", oc: 2 },
    models: { min: 3, max: 6 },
    points: 120,
    weapons: [
      { name: "Vicious Claws", type: "Melee", attacks: "3", skill: "WS3+", strength: "7", ap: "-2", damage: "2" },
      { name: "Particle Caster", type: "Pistol", range: '12"', attacks: "2", skill: "BS3+", strength: "6", ap: "-1", damage: "1" },
    ],
    abilities: [
      { name: "Wraith Form", description: "This unit can move through terrain features and models as if they were not there. It has a 4++ invulnerable save." },
      { name: "Phasing Strike", description: "The first time each turn this unit fights in melee, all its attacks have AP -4 instead of AP -2." },
    ],
    keywords: ["Beast", "Canoptek", "Canoptek Wraiths"],
    factionKeywords: ["Necrons"],
    wargearOptions: [
      { description: "Any model may replace Vicious Claws with Whip Coils (Attacks 5, S5, AP-1, D1, Lethal Hits)." },
    ],
  },
  {
    id: "nec-canoptek-reanimator",
    name: "Canoptek Reanimator",
    role: "Vehicle",
    category: "Elites",
    stats: { movement: '8"', toughness: 7, save: "3+", wounds: 8, leadership: "7+", oc: 2 },
    models: { min: 1, max: 1 },
    points: 95,
    weapons: [
      { name: "Atomiser Beam (×2)", type: "Heavy", range: '18"', attacks: "2", skill: "BS3+", strength: "6", ap: "-2", damage: "2" },
      { name: "Reanimator's Claws", type: "Melee", attacks: "3", skill: "WS3+", strength: "6", ap: "-1", damage: "1" },
    ],
    abilities: [
      { name: "Reanimation Beam", description: "At the start of your Command Phase, select one friendly Necron CORE unit within 9\": every model in that unit that has not yet activated Reanimation Protocols this phase immediately rolls for Reanimation Protocols." },
      { name: "Living Metal", description: "At the start of your Command Phase, this model regains 1 lost wound." },
    ],
    keywords: ["Vehicle", "Walker", "Canoptek", "Canoptek Reanimator"],
    factionKeywords: ["Necrons"],
  },
  // ─── FAST ATTACK ──────────────────────────────────────────────────
  {
    id: "nec-canoptek-scarab-swarms",
    name: "Canoptek Scarab Swarms",
    role: "Beast",
    category: "Fast Attack",
    stats: { movement: '10"', toughness: 3, save: "6+", wounds: 3, leadership: "8+", oc: 2 },
    models: { min: 3, max: 9 },
    points: 35,
    weapons: [
      { name: "Feeder Mandibles", type: "Melee", attacks: "4", skill: "WS4+", strength: "2", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Entropic Mandibles", description: "Each time this unit makes a melee attack against a VEHICLE, unmodified wound rolls of 6 cause 1 additional mortal wound." },
      { name: "Swarm", description: "This unit does not take Morale tests." },
    ],
    keywords: ["Beast", "Canoptek", "Canoptek Scarab Swarms"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-lokhust-destroyers",
    name: "Lokhust Destroyers",
    role: "Infantry",
    category: "Fast Attack",
    canFly: true,
    stats: { movement: '10"', toughness: 5, save: "3+", wounds: 3, leadership: "6+", oc: 1 },
    models: { min: 3, max: 6 },
    points: 90,
    weapons: [
      { name: "Gauss Cannon", type: "Heavy", range: '24"', attacks: "2", skill: "BS3+", strength: "6", ap: "-2", damage: "2" },
      { name: "Close Combat Weapon", type: "Melee", attacks: "1", skill: "WS3+", strength: "4", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Reanimation Protocols", description: "At the start of your Command Phase, roll one D6 for each wound marker on this unit: for each 5+, restore 1 wound." },
      { name: "Fly", description: "This model can move over models and terrain." },
    ],
    keywords: ["Infantry", "Core", "Fly", "Destroyer", "Lokhust", "Lokhust Destroyers"],
    factionKeywords: ["Necrons"],
    wargearOptions: [
      { description: "Any model may replace Gauss Cannon with Enmitic Disintegrator (D3 shots, S5, AP-2, D1, Devastating Wounds)." },
    ],
  },
  {
    id: "nec-lokhust-heavy-destroyers",
    name: "Lokhust Heavy Destroyers",
    role: "Infantry",
    category: "Fast Attack",
    canFly: true,
    stats: { movement: '10"', toughness: 6, save: "3+", wounds: 4, leadership: "6+", oc: 1 },
    models: { min: 1, max: 3 },
    points: 60,
    weapons: [
      { name: "Gauss Destructor", type: "Heavy", range: '36"', attacks: "2", skill: "BS3+", strength: "12", ap: "-4", damage: "D6+1" },
      { name: "Close Combat Weapon", type: "Melee", attacks: "2", skill: "WS3+", strength: "6", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Reanimation Protocols", description: "At the start of your Command Phase, roll one D6 for each wound marker on this unit: for each 5+, restore 1 wound." },
      { name: "Fly", description: "This model can move over models and terrain." },
      { name: "Tank Hunters", description: "Re-roll wound rolls against VEHICLE and MONSTER units." },
    ],
    keywords: ["Infantry", "Core", "Fly", "Destroyer", "Lokhust", "Lokhust Heavy Destroyers"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-ophydian-destroyers",
    name: "Ophydian Destroyers",
    role: "Infantry",
    category: "Fast Attack",
    canDeepStrike: true,
    stats: { movement: '8"', toughness: 5, save: "3+", wounds: 3, leadership: "6+", oc: 1 },
    models: { min: 3, max: 6 },
    points: 90,
    weapons: [
      { name: "Hyperphase Reap-Blade", type: "Melee", attacks: "3", skill: "WS3+", strength: "7", ap: "-3", damage: "2", keywords: ["Lethal Hits"] },
      { name: "Ophydian Claws", type: "Melee", attacks: "4", skill: "WS3+", strength: "6", ap: "-2", damage: "1" },
    ],
    abilities: [
      { name: "Burrowing Infiltrators", description: "This unit can be set up underground. At the end of any of your Movement phases, this unit can surface anywhere more than 9\" from enemy models, having Deep Struck from below." },
      { name: "Whirling Onslaught", description: "After this unit Charges, it gains +1 Attack per model until end of the subsequent Fight phase." },
    ],
    keywords: ["Infantry", "Core", "Destroyer", "Skorpekh", "Ophydian Destroyers"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-tomb-blades",
    name: "Tomb Blades",
    role: "Mounted",
    category: "Fast Attack",
    canFly: true,
    stats: { movement: '14"', toughness: 5, save: "3+", wounds: 2, leadership: "6+", oc: 2 },
    models: { min: 3, max: 9 },
    points: 75,
    weapons: [
      { name: "Twin Gauss Blaster", type: "Rapid Fire", range: '24"', attacks: "2", skill: "BS3+", strength: "5", ap: "-1", damage: "1" },
      { name: "Close Combat Weapon", type: "Melee", attacks: "1", skill: "WS4+", strength: "4", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Reanimation Protocols", description: "At the start of your Command Phase, roll one D6 for each wound marker on this unit: for each 5+, restore 1 wound." },
      { name: "Fly", description: "This model can move over models and terrain." },
    ],
    keywords: ["Mounted", "Core", "Fly", "Tomb Blades"],
    factionKeywords: ["Necrons"],
    wargearOptions: [
      { description: "Any model may replace Twin Gauss Blaster with Twin Tesla Carbine (S5, Sustained Hits 2) or Particle Beamer (D3 shots, S6, AP-1)." },
      { description: "Any model may take a Shadowloom (+1 to invulnerable saves) or Nebuloscope (ignore cover bonuses)." },
    ],
  },
  // ─── HEAVY SUPPORT ────────────────────────────────────────────────
  {
    id: "nec-canoptek-doomstalker",
    name: "Canoptek Doomstalker",
    role: "Vehicle",
    category: "Heavy Support",
    stats: { movement: '8"', toughness: 9, save: "3+", wounds: 10, leadership: "7+", oc: 3 },
    models: { min: 1, max: 1 },
    points: 155,
    weapons: [
      { name: "Doomsday Blaster (Low Power)", type: "Heavy", range: '24"', attacks: "D6+1", skill: "BS3+", strength: "8", ap: "-2", damage: "2" },
      { name: "Doomsday Blaster (High Power)", type: "Heavy", range: '24"', attacks: "D3+1", skill: "BS3+", strength: "12", ap: "-5", damage: "D6+2" },
      { name: "Atomiser Beam", type: "Heavy", range: '18"', attacks: "2", skill: "BS3+", strength: "6", ap: "-2", damage: "2" },
      { name: "Doomstalker Claws", type: "Melee", attacks: "3", skill: "WS3+", strength: "8", ap: "-2", damage: "2" },
    ],
    abilities: [
      { name: "Doomsday Cannon Mode", description: "If this model did not move this turn, it fires High Power. If it moved, it fires Low Power only." },
      { name: "Living Metal", description: "At the start of your Command Phase, this model regains 1 lost wound." },
    ],
    keywords: ["Vehicle", "Walker", "Canoptek", "Canoptek Doomstalker"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-convergence-of-dominion",
    name: "Convergence of Dominion",
    role: "Vehicle",
    category: "Heavy Support",
    stats: { movement: '0"', toughness: 8, save: "3+", wounds: 5, leadership: "7+", oc: 0 },
    models: { min: 3, max: 3 },
    points: 120,
    weapons: [
      { name: "Stave of Dominion", type: "Heavy", range: '60"', attacks: "1", skill: "BS3+", strength: "8", ap: "-3", damage: "D3+1", keywords: ["Indirect Fire"] },
    ],
    abilities: [
      { name: "Enduring Will", description: "At the start of your Command Phase, each model in this unit regains 1 lost wound if it lost any." },
      { name: "Territorial Dominance", description: "Friendly Necron units within 6\" of any model in this unit re-roll Objective Control rolls and have +1 OC. Enemy units within 6\" must subtract 2 from their Leadership." },
      { name: "Fortification", description: "This model cannot move after being placed. Units may shelter behind it (counts as Heavy Cover)." },
    ],
    keywords: ["Vehicle", "Fortification", "Convergence of Dominion"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-night-scythe",
    name: "Night Scythe",
    role: "Vehicle",
    category: "Heavy Support",
    canFly: true,
    stats: { movement: '20-50"', toughness: 9, save: "3+", wounds: 12, leadership: "7+", oc: 0 },
    models: { min: 1, max: 1 },
    points: 160,
    weapons: [
      { name: "Twin Tesla Destructor", type: "Heavy", range: '36"', attacks: "8", skill: "BS3+", strength: "7", ap: "-1", damage: "1", keywords: ["Sustained Hits 2"] },
    ],
    abilities: [
      { name: "Transport", description: "This model can transport up to 20 Necron Infantry models." },
      { name: "Aerial Reinforcement", description: "When this model arrives using Hover rules, the unit it transports can disembark anywhere within 6\" even if the Transport has moved more than 3\"." },
      { name: "Airborne", description: "Cannot charge or be charged. Only Fly and Airborne units can target it." },
      { name: "Invasion Beam", description: "Instead of moving normally, this model can perform an Invasion Beam: a friendly Infantry unit on the battlefield can be placed into reserve, then at the end of the Movement phase a friendly unit in reserve arrives within 6\" of this model." },
    ],
    keywords: ["Vehicle", "Aircraft", "Fly", "Transport", "Night Scythe"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-doom-scythe",
    name: "Doom Scythe",
    role: "Vehicle",
    category: "Heavy Support",
    canFly: true,
    stats: { movement: '20-50"', toughness: 9, save: "3+", wounds: 12, leadership: "7+", oc: 0 },
    models: { min: 1, max: 1 },
    points: 175,
    weapons: [
      { name: "Twin Heavy Tesla Cannon", type: "Heavy", range: '36"', attacks: "6", skill: "BS3+", strength: "8", ap: "-2", damage: "2", keywords: ["Sustained Hits 2"] },
      { name: "Death Ray", type: "Heavy", range: '30"', attacks: "D6+2", skill: "BS3+", strength: "14", ap: "-5", damage: "D6" },
    ],
    abilities: [
      { name: "Airborne", description: "Cannot charge or be charged. Only Fly and Airborne units can target it." },
      { name: "Death Ray Sweep", description: "When this model shoots with the Death Ray, select a starting point anywhere within range. Draw a line to any second point within 30\"; all units (friend and foe) under the line take D6 hits." },
    ],
    keywords: ["Vehicle", "Aircraft", "Fly", "Doom Scythe"],
    factionKeywords: ["Necrons"],
  },
  // ─── DEDICATED TRANSPORT ──────────────────────────────────────────
  {
    id: "nec-ghost-ark",
    name: "Ghost Ark",
    role: "Vehicle",
    category: "Dedicated Transport",
    canFly: true,
    stats: { movement: '12"', toughness: 10, save: "3+", wounds: 14, leadership: "7+", oc: 3 },
    models: { min: 1, max: 1 },
    points: 175,
    weapons: [
      { name: "Gauss Flayer Array (×10)", type: "Rapid Fire", range: '24"', attacks: "1", skill: "BS3+", strength: "4", ap: "-1", damage: "1" },
    ],
    abilities: [
      { name: "Transport", description: "This model can transport up to 10 Necron Warriors models." },
      { name: "Repair Barge", description: "At the start of your Command Phase, select one friendly Necron Warriors unit within 6\": up to D3 destroyed models are returned to that unit." },
      { name: "Living Metal", description: "At the start of your Command Phase, this model regains 1 lost wound." },
      { name: "Fly", description: "This model can move over models and terrain." },
    ],
    keywords: ["Vehicle", "Transport", "Fly", "Ghost Ark"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-monolith",
    name: "Monolith",
    role: "Vehicle",
    category: "Lord of War",
    isTitanic: true,
    stats: { movement: '5"', toughness: 12, save: "2+", wounds: 20, leadership: "4+", oc: 8 },
    models: { min: 1, max: 1 },
    points: 400,
    weapons: [
      { name: "Death Ray", type: "Heavy", range: '36"', attacks: "3", skill: "BS3+", strength: "16", ap: "-4", damage: "D3+3" },
      { name: "Gauss Flux Arc ×4", type: "Heavy", range: '24"', attacks: "6", skill: "BS3+", strength: "5", ap: "-2", damage: "1" },
    ],
    abilities: [
      { name: "Titanic", description: "This model is a Titanic unit and cannot have Stratagems used to target it." },
      { name: "Living Metal", description: "At the start of your Command Phase, this model regains D3 lost wounds." },
      { name: "Eternity Gate", description: "Once per turn, in the Movement phase, one friendly Necron INFANTRY unit anywhere on the battlefield can teleport, removing it from the board and placing it within 3\" of this model and more than 9\" from enemy models." },
      { name: "Loom of the Gods", description: "At the start of the enemy Shooting phase, all enemy units within 12\" of this model must take a Battleshock test." },
    ],
    keywords: ["Vehicle", "Titanic", "Monolith"],
    factionKeywords: ["Necrons"],
  },
];

const AWAKENED_DYNASTY: Detachment = {
  name: "Awakened Dynasty",
  rule: {
    name: "Dynastic Protocols",
    description:
      "All Necron units get +1 to Reanimation Protocol rolls. Necron CORE units within 6\" of a friendly OVERLORD gain the Lethal Hits keyword on all unmodified hit rolls of 6.",
  },
  stratagems: [
    {
      name: "Disruption Fields",
      cost: 1,
      phase: "Fight",
      description: "Use at the start of the Fight phase. A friendly Necron CORE unit's melee attacks gain the Sustained Hits 1 keyword until end of phase.",
    },
    {
      name: "Quantum Deflection",
      cost: 1,
      phase: "Any",
      description: "Use when a friendly Necron unit is selected as the target of a ranged attack. Until end of that Shooting phase, that unit has a 5++ invulnerable save against those attacks.",
    },
    {
      name: "Entropic Strike",
      cost: 1,
      phase: "Any",
      description: "Use in the Shooting or Fight phase. A friendly Necron unit's weapons with AP -1 or better gain an additional -1 AP until end of that phase.",
    },
    {
      name: "Emergency Invasion Beam",
      cost: 1,
      phase: "Any",
      description: "Use at the end of any phase. Remove one friendly Necron INFANTRY unit from the battlefield and add it to Strategic Reserves. It may redeploy from reserves next turn using Tactical Reserves rules.",
    },
    {
      name: "Hand of the Phaeron",
      cost: 2,
      phase: "Command",
      description: "Use in the Command Phase. One friendly Necron VEHICLE within 12\" of a friendly OVERLORD automatically passes its Reanimation Protocol roll this turn, restoring it to 1 wound remaining if destroyed.",
    },
    {
      name: "Voltaic Staff",
      cost: 1,
      phase: "Shooting",
      description: "Use at the start of the Shooting phase. A friendly CRYPTEK unit can target enemy units not visible to it with its shooting attacks this phase.",
    },
  ],
  enhancements: [
    {
      name: "Sempiternal Weave",
      points: 20,
      description: "The bearer's Sv characteristic is improved by 1. Additionally, the bearer has a 4+++ Feel No Pain save against mortal wounds.",
      restriction: "Necrons CHARACTER",
    },
    {
      name: "Nanoscarab Casket",
      points: 15,
      description: "The bearer heals 2 wounds from Living Metal instead of 1, and their Reanimation Protocol roll succeeds on a 4+.",
      restriction: "Necrons CHARACTER",
    },
    {
      name: "Voltaic Staff",
      points: 10,
      description: "All of the bearer's shooting weapons gain the Devastating Wounds keyword.",
      restriction: "Necrons CHARACTER",
    },
    {
      name: "The Sovereign Coronal",
      points: 30,
      description: "Aura: Friendly Necron CORE units within 6\" of this model get +1 to their Attacks characteristic in the Fight phase.",
      restriction: "Necrons CHARACTER",
    },
  ],
};

export const NECRONS_FACTION: Faction = {
  id: "necrons",
  name: "Necrons",
  shortName: "Nec",
  description: "Ancient machine-warriors who slumbered in tombs for sixty million years. The Necrons have awoken to reclaim their galaxy, armed with deathless bodies and hyper-advanced technology.",
  accentColor: "#15803d",
  units: NECRON_UNITS,
  detachments: [AWAKENED_DYNASTY],
};
