import type { Unit, Faction, Detachment } from "./types";

export const SM_UNITS: Unit[] = [
  // ─── CHARACTERS ───────────────────────────────────────────────────
  {
    id: "sm-marneus-calgar",
    name: "Marneus Calgar",
    role: "Character",
    category: "HQ",
    isEpicHero: true,
    stats: { movement: '6"', toughness: 4, save: "2+/4++", wounds: 8, leadership: "5+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 160,
    weapons: [
      { name: "Gauntlets of Ultramar", type: "Ranged", range: '18"', attacks: "6", skill: "BS2+", strength: "5", ap: "-2", damage: "2" },
      { name: "Gauntlets of Ultramar", type: "Melee", attacks: "6", skill: "WS2+", strength: "7", ap: "-3", damage: "2" },
    ],
    abilities: [
      { name: "Chapter Master", description: "Re-roll all hit and wound rolls for friendly Adeptus Astartes CORE units within 6\"." },
      { name: "Adept of the Codex", description: "Once per battle, can be used to gain 1 additional Command Point." },
    ],
    keywords: ["Infantry", "Character", "Epic Hero", "Terminator", "Chapter Master", "Marneus Calgar"],
    factionKeywords: ["Adeptus Astartes", "Ultramarines"],
  },
  {
    id: "sm-roboute-guilliman",
    name: "Roboute Guilliman",
    role: "Character",
    category: "Lord of War",
    isEpicHero: true,
    stats: { movement: '6"', toughness: 6, save: "2+/3++", wounds: 9, leadership: "4+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 380,
    weapons: [
      { name: "Hand of Dominion", type: "Ranged", range: '24"', attacks: "6", skill: "BS2+", strength: "6", ap: "-2", damage: "2" },
      { name: "Hand of Dominion", type: "Melee", attacks: "6", skill: "WS2+", strength: "8", ap: "-3", damage: "3" },
      { name: "Gladius Incandor", type: "Melee", attacks: "5", skill: "WS2+", strength: "10", ap: "-4", damage: "D3+3" },
    ],
    abilities: [
      { name: "Primarch of the XIII Legion", description: "Re-roll all hit and wound rolls for friendly Ultramarines CORE units within 12\"." },
      { name: "Lord of Ultramar", description: "Once per battle round, one friendly Adeptus Astartes unit within 6\" can shoot or fight as if it were your Shooting or Fight phase." },
      { name: "Inspiring Presence", description: "Friendly Adeptus Astartes units within 6\" automatically pass Battleshock tests." },
    ],
    keywords: ["Infantry", "Character", "Epic Hero", "Primarch", "Roboute Guilliman"],
    factionKeywords: ["Adeptus Astartes", "Ultramarines"],
  },
  {
    id: "sm-chief-librarian-tigurius",
    name: "Chief Librarian Tigurius",
    role: "Character",
    category: "HQ",
    isEpicHero: true,
    stats: { movement: '6"', toughness: 4, save: "3+/4++", wounds: 5, leadership: "5+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 90,
    weapons: [
      { name: "Force Sword", type: "Melee", attacks: "5", skill: "WS2+", strength: "6", ap: "-2", damage: "D3" },
      { name: "Bolt Pistol", type: "Pistol", range: '12"', attacks: "1", skill: "BS2+", strength: "4", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Psyker", description: "Can attempt to manifest 2 psychic powers per turn and deny 2 witchfire attempts." },
      { name: "Prescience", description: "Friendly Adeptus Astartes CORE unit within 18\" can re-roll all hit rolls until end of phase." },
    ],
    keywords: ["Infantry", "Character", "Epic Hero", "Psyker", "Librarian"],
    factionKeywords: ["Adeptus Astartes", "Ultramarines"],
  },
  {
    id: "sm-captain",
    name: "Captain",
    role: "Character",
    category: "HQ",
    stats: { movement: '6"', toughness: 4, save: "3+/4++", wounds: 5, leadership: "5+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 80,
    weapons: [
      { name: "Master-crafted Power Weapon", type: "Melee", attacks: "5", skill: "WS2+", strength: "5", ap: "-2", damage: "2" },
      { name: "Neo-volkite Pistol", type: "Pistol", range: '12"', attacks: "2", skill: "BS2+", strength: "5", ap: "0", damage: "2" },
    ],
    abilities: [
      { name: "Rites of Battle", description: "Re-roll hit rolls of 1 for friendly Adeptus Astartes CORE units within 6\"." },
      { name: "Lead from the Front", description: "Once per Fight phase, after this model fights, one friendly unit within 6\" can fight next." },
    ],
    keywords: ["Infantry", "Character", "Captain"],
    factionKeywords: ["Adeptus Astartes"],
    wargearOptions: [
      { description: "May replace Neo-volkite Pistol with Plasma Pistol or Combi-weapon." },
      { description: "May replace Master-crafted Power Weapon with Thunder Hammer or Power Fist." },
      { description: "May take a Storm Shield for a 4++ invulnerable save." },
    ],
  },
  {
    id: "sm-captain-terminator",
    name: "Captain in Terminator Armour",
    role: "Character",
    category: "HQ",
    canDeepStrike: true,
    stats: { movement: '5"', toughness: 4, save: "2+/4++", wounds: 6, leadership: "5+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 100,
    weapons: [
      { name: "Storm Bolter", type: "Rapid Fire", range: '24"', attacks: "2", skill: "BS2+", strength: "4", ap: "0", damage: "1" },
      { name: "Power Fist", type: "Melee", attacks: "4", skill: "WS2+", strength: "8", ap: "-2", damage: "2" },
    ],
    abilities: [
      { name: "Rites of Battle", description: "Re-roll hit rolls of 1 for friendly Adeptus Astartes CORE units within 6\"." },
      { name: "Deep Strike", description: "Can be set up in Strategic Reserves anywhere more than 9\" from enemy models." },
    ],
    keywords: ["Infantry", "Character", "Terminator", "Captain"],
    factionKeywords: ["Adeptus Astartes"],
    wargearOptions: [
      { description: "May replace Storm Bolter + Power Fist with Thunder Hammer + Storm Shield." },
    ],
  },
  {
    id: "sm-captain-phobos",
    name: "Captain in Phobos Armour",
    role: "Character",
    category: "HQ",
    stats: { movement: '6"', toughness: 4, save: "3+", wounds: 5, leadership: "5+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 70,
    weapons: [
      { name: "Master-crafted Instigator Bolt Carbine", type: "Heavy", range: '30"', attacks: "3", skill: "BS2+", strength: "4", ap: "-2", damage: "3", keywords: ["Precision"] },
      { name: "Teeth of Terra", type: "Melee", attacks: "5", skill: "WS2+", strength: "5", ap: "-2", damage: "2" },
    ],
    abilities: [
      { name: "Rites of Battle", description: "Re-roll hit rolls of 1 for friendly Adeptus Astartes CORE units within 6\"." },
      { name: "Guerrilla Tactics", description: "Once per battle, at the end of your opponent's turn, this model can remove itself from the battlefield and be redeployed anywhere more than 9\" from enemy models." },
    ],
    keywords: ["Infantry", "Character", "Phobos", "Captain"],
    factionKeywords: ["Adeptus Astartes"],
  },
  {
    id: "sm-captain-jump-pack",
    name: "Captain with Jump Pack",
    role: "Character",
    category: "HQ",
    canFly: true,
    canDeepStrike: true,
    stats: { movement: '12"', toughness: 4, save: "3+/4++", wounds: 5, leadership: "5+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 90,
    weapons: [
      { name: "Heavy Bolt Pistol", type: "Pistol", range: '18"', attacks: "1", skill: "BS2+", strength: "4", ap: "-1", damage: "1" },
      { name: "Master-crafted Power Weapon", type: "Melee", attacks: "5", skill: "WS2+", strength: "5", ap: "-2", damage: "2" },
    ],
    abilities: [
      { name: "Rites of Battle", description: "Re-roll hit rolls of 1 for friendly Adeptus Astartes CORE units within 6\"." },
      { name: "Fly", description: "This model can move over models and terrain." },
      { name: "Deep Strike", description: "Can be set up in Strategic Reserves anywhere more than 9\" from enemy models." },
    ],
    keywords: ["Infantry", "Character", "Jump Pack", "Fly", "Captain"],
    factionKeywords: ["Adeptus Astartes"],
    wargearOptions: [
      { description: "May replace pistol with Plasma Pistol. May replace melee weapon with Thunder Hammer." },
    ],
  },
  {
    id: "sm-librarian",
    name: "Librarian",
    role: "Character",
    category: "HQ",
    stats: { movement: '6"', toughness: 4, save: "3+/4++", wounds: 4, leadership: "5+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 75,
    weapons: [
      { name: "Force Weapon", type: "Melee", attacks: "4", skill: "WS3+", strength: "6", ap: "-1", damage: "D3" },
      { name: "Bolt Pistol", type: "Pistol", range: '12"', attacks: "1", skill: "BS3+", strength: "4", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Psyker", description: "Can attempt to manifest 1 psychic power per turn and deny 1 witchfire attempt." },
      { name: "Psychic Hood", description: "+1 to Deny attempts against Psykers within 12\"." },
    ],
    keywords: ["Infantry", "Character", "Psyker", "Librarian"],
    factionKeywords: ["Adeptus Astartes"],
  },
  {
    id: "sm-librarian-terminator",
    name: "Librarian in Terminator Armour",
    role: "Character",
    category: "HQ",
    canDeepStrike: true,
    stats: { movement: '5"', toughness: 4, save: "2+/4++", wounds: 4, leadership: "5+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 90,
    weapons: [
      { name: "Force Weapon", type: "Melee", attacks: "4", skill: "WS3+", strength: "6", ap: "-1", damage: "D3" },
      { name: "Storm Bolter", type: "Rapid Fire", range: '24"', attacks: "2", skill: "BS3+", strength: "4", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Psyker", description: "Can attempt to manifest 1 psychic power per turn and deny 1 witchfire attempt." },
      { name: "Psychic Hood", description: "+1 to Deny attempts against Psykers within 12\"." },
      { name: "Deep Strike", description: "Can be set up in Strategic Reserves anywhere more than 9\" from enemy models." },
    ],
    keywords: ["Infantry", "Character", "Terminator", "Psyker", "Librarian"],
    factionKeywords: ["Adeptus Astartes"],
  },
  {
    id: "sm-librarian-phobos",
    name: "Librarian in Phobos Armour",
    role: "Character",
    category: "HQ",
    stats: { movement: '6"', toughness: 4, save: "3+", wounds: 4, leadership: "5+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 75,
    weapons: [
      { name: "Force Sword", type: "Melee", attacks: "4", skill: "WS3+", strength: "6", ap: "-2", damage: "D3" },
      { name: "Bolt Pistol", type: "Pistol", range: '12"', attacks: "1", skill: "BS3+", strength: "4", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Psyker", description: "Can attempt to manifest 1 psychic power per turn and deny 1 witchfire attempt." },
      { name: "Shrouding", description: "Friendly Phobos units within 6\" have the Stealth ability." },
    ],
    keywords: ["Infantry", "Character", "Phobos", "Psyker", "Librarian"],
    factionKeywords: ["Adeptus Astartes"],
  },
  {
    id: "sm-chaplain",
    name: "Chaplain",
    role: "Character",
    category: "HQ",
    stats: { movement: '6"', toughness: 4, save: "3+", wounds: 4, leadership: "5+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 65,
    weapons: [
      { name: "Crozius Arcanum", type: "Melee", attacks: "4", skill: "WS2+", strength: "6", ap: "-1", damage: "2" },
      { name: "Absolvor Bolt Pistol", type: "Pistol", range: '18"', attacks: "1", skill: "BS2+", strength: "5", ap: "-1", damage: "2" },
    ],
    abilities: [
      { name: "Litany of Hate", description: "Re-roll hit rolls in the Fight phase for friendly Adeptus Astartes CORE units within 6\"." },
      { name: "Spiritual Leaders", description: "Friendly Adeptus Astartes CORE units within 6\" never have to take Battleshock tests." },
    ],
    keywords: ["Infantry", "Character", "Chaplain"],
    factionKeywords: ["Adeptus Astartes"],
  },
  {
    id: "sm-chaplain-terminator",
    name: "Chaplain in Terminator Armour",
    role: "Character",
    category: "HQ",
    canDeepStrike: true,
    stats: { movement: '5"', toughness: 4, save: "2+", wounds: 4, leadership: "5+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 70,
    weapons: [
      { name: "Crozius Arcanum", type: "Melee", attacks: "4", skill: "WS2+", strength: "6", ap: "-1", damage: "2" },
      { name: "Storm Bolter", type: "Rapid Fire", range: '24"', attacks: "2", skill: "BS2+", strength: "4", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Litany of Hate", description: "Re-roll hit rolls in Fight phase for friendly Adeptus Astartes CORE units within 6\"." },
      { name: "Deep Strike", description: "Can be set up in Strategic Reserves anywhere more than 9\" from enemy models." },
    ],
    keywords: ["Infantry", "Character", "Terminator", "Chaplain"],
    factionKeywords: ["Adeptus Astartes"],
  },
  {
    id: "sm-chaplain-jump-pack",
    name: "Chaplain with Jump Pack",
    role: "Character",
    category: "HQ",
    canFly: true,
    canDeepStrike: true,
    stats: { movement: '12"', toughness: 4, save: "3+", wounds: 4, leadership: "5+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 75,
    weapons: [
      { name: "Crozius Arcanum", type: "Melee", attacks: "4", skill: "WS2+", strength: "6", ap: "-1", damage: "2" },
      { name: "Absolvor Bolt Pistol", type: "Pistol", range: '18"', attacks: "1", skill: "BS2+", strength: "5", ap: "-1", damage: "2" },
    ],
    abilities: [
      { name: "Litany of Hate", description: "Re-roll hit rolls in Fight phase for friendly Adeptus Astartes CORE units within 6\"." },
      { name: "Fly", description: "This model can move over models and terrain." },
      { name: "Deep Strike", description: "Can be set up in Strategic Reserves anywhere more than 9\" from enemy models." },
    ],
    keywords: ["Infantry", "Character", "Jump Pack", "Fly", "Chaplain"],
    factionKeywords: ["Adeptus Astartes"],
  },
  {
    id: "sm-techmarine",
    name: "Techmarine",
    role: "Character",
    category: "HQ",
    stats: { movement: '6"', toughness: 4, save: "2+", wounds: 4, leadership: "5+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 45,
    weapons: [
      { name: "Servo-arm", type: "Melee", attacks: "2", skill: "WS3+", strength: "8", ap: "-2", damage: "3" },
      { name: "Omnissian Power Axe", type: "Melee", attacks: "3", skill: "WS2+", strength: "6", ap: "-2", damage: "2" },
      { name: "Bolt Pistol", type: "Pistol", range: '12"', attacks: "1", skill: "BS2+", strength: "4", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Blessing of the Omnissiah", description: "At the start of your Command Phase, can repair one friendly Vehicle within 3\", restoring up to D3 lost wounds." },
    ],
    keywords: ["Infantry", "Character", "Techmarine"],
    factionKeywords: ["Adeptus Astartes"],
  },
  {
    id: "sm-lieutenant",
    name: "Lieutenant",
    role: "Character",
    category: "HQ",
    stats: { movement: '6"', toughness: 4, save: "3+", wounds: 4, leadership: "5+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 70,
    weapons: [
      { name: "Master-crafted Power Weapon", type: "Melee", attacks: "4", skill: "WS2+", strength: "5", ap: "-2", damage: "2" },
      { name: "Bolt Pistol", type: "Pistol", range: '12"', attacks: "1", skill: "BS2+", strength: "4", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Tactical Precision", description: "Wound rolls of 6+ for friendly Adeptus Astartes CORE units within 6\" are critical wounds (AP -4)." },
    ],
    keywords: ["Infantry", "Character", "Lieutenant"],
    factionKeywords: ["Adeptus Astartes"],
  },
  {
    id: "sm-lieutenant-phobos",
    name: "Lieutenant in Phobos Armour",
    role: "Character",
    category: "HQ",
    stats: { movement: '6"', toughness: 4, save: "3+", wounds: 4, leadership: "5+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 65,
    weapons: [
      { name: "Master-crafted Occulus Bolt Rifle", type: "Assault", range: '24"', attacks: "2", skill: "BS2+", strength: "4", ap: "-1", damage: "2", keywords: ["Precision"] },
      { name: "Combat Knife", type: "Melee", attacks: "4", skill: "WS2+", strength: "4", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Tactical Precision", description: "Wound rolls of 6+ for friendly Adeptus Astartes CORE units within 6\" are critical wounds." },
      { name: "Concealed Positions", description: "During deployment, friendly Phobos units can be set up anywhere on the battlefield more than 9\" from enemy deployment zone." },
    ],
    keywords: ["Infantry", "Character", "Phobos", "Lieutenant"],
    factionKeywords: ["Adeptus Astartes"],
  },
  {
    id: "sm-lieutenant-jump-pack",
    name: "Lieutenant with Jump Pack",
    role: "Character",
    category: "HQ",
    canFly: true,
    canDeepStrike: true,
    stats: { movement: '12"', toughness: 4, save: "3+", wounds: 4, leadership: "5+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 70,
    weapons: [
      { name: "Master-crafted Power Weapon", type: "Melee", attacks: "4", skill: "WS2+", strength: "5", ap: "-2", damage: "2" },
      { name: "Heavy Bolt Pistol", type: "Pistol", range: '18"', attacks: "1", skill: "BS2+", strength: "4", ap: "-1", damage: "1" },
    ],
    abilities: [
      { name: "Tactical Precision", description: "Wound rolls of 6+ for friendly Adeptus Astartes CORE units within 6\" are critical wounds." },
      { name: "Fly", description: "This model can move over models and terrain." },
      { name: "Deep Strike", description: "Can be set up in Strategic Reserves anywhere more than 9\" from enemy models." },
    ],
    keywords: ["Infantry", "Character", "Jump Pack", "Fly", "Lieutenant"],
    factionKeywords: ["Adeptus Astartes"],
  },
  {
    id: "sm-judiciar",
    name: "Judiciar",
    role: "Character",
    category: "HQ",
    stats: { movement: '6"', toughness: 4, save: "3+", wounds: 4, leadership: "5+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 75,
    weapons: [
      { name: "Executioner Relic Blade", type: "Melee", attacks: "4", skill: "WS2+", strength: "6", ap: "-3", damage: "3" },
      { name: "Absolvor Bolt Pistol", type: "Pistol", range: '18"', attacks: "1", skill: "BS2+", strength: "5", ap: "-1", damage: "2" },
    ],
    abilities: [
      { name: "Martial Exemplar", description: "Enemy units within 6\" of this model cannot use Stratagems in the Fight phase." },
      { name: "Temporal Subjugation", description: "Enemy units within Engagement Range of this model fight last." },
    ],
    keywords: ["Infantry", "Character", "Judiciar"],
    factionKeywords: ["Adeptus Astartes"],
  },
  {
    id: "sm-primaris-apothecary",
    name: "Primaris Apothecary",
    role: "Character",
    category: "Elites",
    stats: { movement: '6"', toughness: 4, save: "3+", wounds: 4, leadership: "5+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 55,
    weapons: [
      { name: "Absolvor Bolt Pistol", type: "Pistol", range: '18"', attacks: "1", skill: "BS2+", strength: "5", ap: "-1", damage: "2" },
      { name: "Reductor Pistol", type: "Pistol", range: '3"', attacks: "1", skill: "BS2+", strength: "4", ap: "-4", damage: "2" },
      { name: "Surgical Saw", type: "Melee", attacks: "3", skill: "WS3+", strength: "5", ap: "-1", damage: "2" },
    ],
    abilities: [
      { name: "Selfless Healer", description: "At the end of each phase, one model in the unit led by this model regains up to D3 lost wounds, OR one slain model is returned on a 4+." },
    ],
    keywords: ["Infantry", "Character", "Apothecary"],
    factionKeywords: ["Adeptus Astartes"],
  },
  {
    id: "sm-chief-apothecary",
    name: "Chief Apothecary",
    role: "Character",
    category: "Elites",
    stats: { movement: '6"', toughness: 4, save: "3+", wounds: 5, leadership: "5+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 75,
    weapons: [
      { name: "Absolvor Bolt Pistol", type: "Pistol", range: '18"', attacks: "1", skill: "BS2+", strength: "5", ap: "-1", damage: "2" },
      { name: "Reductor Pistol", type: "Pistol", range: '3"', attacks: "1", skill: "BS2+", strength: "4", ap: "-4", damage: "2" },
      { name: "Surgical Saw", type: "Melee", attacks: "4", skill: "WS3+", strength: "5", ap: "-1", damage: "2" },
    ],
    abilities: [
      { name: "Selfless Healer", description: "At the end of each phase, one model in the unit led by this model regains up to D3 lost wounds, OR one slain model is returned on a 4+." },
      { name: "Chief Apothecary Aura", description: "Friendly Adeptus Astartes Infantry units within 6\" have Feel No Pain 6+." },
    ],
    keywords: ["Infantry", "Character", "Apothecary"],
    factionKeywords: ["Adeptus Astartes"],
  },
  {
    id: "sm-primaris-ancient",
    name: "Primaris Ancient",
    role: "Character",
    category: "Elites",
    stats: { movement: '6"', toughness: 4, save: "3+", wounds: 4, leadership: "5+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 60,
    weapons: [
      { name: "Bolt Rifle", type: "Rapid Fire", range: '30"', attacks: "1", skill: "BS2+", strength: "4", ap: "-1", damage: "1" },
      { name: "Close Combat Weapon", type: "Melee", attacks: "3", skill: "WS3+", strength: "4", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Astartes Banner", description: "Friendly Adeptus Astartes CORE units within 6\" can re-roll hit rolls of 1." },
      { name: "Ancient's Oath", description: "When this model is destroyed, do not remove it immediately — it continues to fight until end of phase." },
    ],
    keywords: ["Infantry", "Character", "Ancient"],
    factionKeywords: ["Adeptus Astartes"],
  },
  {
    id: "sm-ancient-terminator",
    name: "Ancient in Terminator Armour",
    role: "Character",
    category: "Elites",
    canDeepStrike: true,
    stats: { movement: '5"', toughness: 4, save: "2+", wounds: 4, leadership: "5+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 80,
    weapons: [
      { name: "Storm Bolter", type: "Rapid Fire", range: '24"', attacks: "2", skill: "BS2+", strength: "4", ap: "0", damage: "1" },
      { name: "Power Weapon", type: "Melee", attacks: "3", skill: "WS3+", strength: "5", ap: "-2", damage: "1" },
    ],
    abilities: [
      { name: "Astartes Banner", description: "Friendly Adeptus Astartes CORE units within 6\" can re-roll hit rolls of 1." },
      { name: "Deep Strike", description: "Can be set up in Strategic Reserves anywhere more than 9\" from enemy models." },
    ],
    keywords: ["Infantry", "Character", "Terminator", "Ancient"],
    factionKeywords: ["Adeptus Astartes"],
  },
  {
    id: "sm-company-champion",
    name: "Company Champion",
    role: "Character",
    category: "Elites",
    stats: { movement: '6"', toughness: 4, save: "3+", wounds: 4, leadership: "5+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 45,
    weapons: [
      { name: "Master-crafted Power Sword", type: "Melee", attacks: "4", skill: "WS2+", strength: "5", ap: "-3", damage: "2" },
      { name: "Bolt Pistol", type: "Pistol", range: '12"', attacks: "1", skill: "BS2+", strength: "4", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Hero's Challenge", description: "At the start of the Fight phase, if any enemy Character is in Engagement Range of this model's unit, this model must fight that Character first." },
      { name: "Combat Shield", description: "This model has a 5++ invulnerable save." },
    ],
    keywords: ["Infantry", "Character", "Company Champion"],
    factionKeywords: ["Adeptus Astartes"],
  },
  // ─── BATTLELINE ───────────────────────────────────────────────────
  {
    id: "sm-intercessors",
    name: "Intercessor Squad",
    role: "Infantry",
    category: "Battleline",
    stats: { movement: '6"', toughness: 4, save: "3+", wounds: 2, leadership: "6+", oc: 2 },
    models: { min: 5, max: 10 },
    points: 90,
    weapons: [
      { name: "Bolt Rifle", type: "Rapid Fire", range: '30"', attacks: "1", skill: "BS3+", strength: "4", ap: "-1", damage: "1" },
      { name: "Auto Bolt Rifle", type: "Assault", range: '24"', attacks: "2", skill: "BS3+", strength: "4", ap: "0", damage: "1" },
      { name: "Stalker Bolt Rifle", type: "Heavy", range: '36"', attacks: "1", skill: "BS3+", strength: "4", ap: "-2", damage: "2" },
      { name: "Close Combat Weapon", type: "Melee", attacks: "3", skill: "WS3+", strength: "4", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Objective Secured", description: "While this unit controls an objective marker, it is treated as having double the number of models for that marker." },
    ],
    keywords: ["Infantry", "Core", "Battleline", "Intercessors"],
    factionKeywords: ["Adeptus Astartes"],
    wargearOptions: [
      { description: "All models may replace Bolt Rifle with Auto Bolt Rifle or Stalker Bolt Rifle." },
      { description: "Sergeant may take a Thunder Hammer, Power Fist, or Power Weapon." },
    ],
  },
  {
    id: "sm-assault-intercessors",
    name: "Assault Intercessor Squad",
    role: "Infantry",
    category: "Battleline",
    stats: { movement: '6"', toughness: 4, save: "3+", wounds: 2, leadership: "6+", oc: 2 },
    models: { min: 5, max: 10 },
    points: 85,
    weapons: [
      { name: "Heavy Bolt Pistol", type: "Pistol", range: '18"', attacks: "1", skill: "BS3+", strength: "4", ap: "-1", damage: "1" },
      { name: "Astartes Chainsword", type: "Melee", attacks: "4", skill: "WS3+", strength: "4", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Objective Secured", description: "While this unit controls an objective marker, it is treated as having double the number of models for that marker." },
    ],
    keywords: ["Infantry", "Core", "Battleline", "Assault Intercessors"],
    factionKeywords: ["Adeptus Astartes"],
    wargearOptions: [
      { description: "Sergeant may take a Thunder Hammer (+10pts), Power Fist (+5pts), or Plasma Pistol (+5pts)." },
    ],
  },
  {
    id: "sm-tactical-squad",
    name: "Tactical Squad",
    role: "Infantry",
    category: "Battleline",
    stats: { movement: '6"', toughness: 4, save: "3+", wounds: 1, leadership: "6+", oc: 2 },
    models: { min: 5, max: 10 },
    points: 75,
    weapons: [
      { name: "Boltgun", type: "Rapid Fire", range: '24"', attacks: "1", skill: "BS3+", strength: "4", ap: "0", damage: "1" },
      { name: "Close Combat Weapon", type: "Melee", attacks: "2", skill: "WS3+", strength: "4", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Objective Secured", description: "While this unit controls an objective marker, it is treated as having double the number of models for that marker." },
      { name: "Combat Squads", description: "Before deployment, can split into two 5-man units." },
    ],
    keywords: ["Infantry", "Core", "Battleline", "Tactical Squad"],
    factionKeywords: ["Adeptus Astartes"],
    wargearOptions: [
      { description: "One model may take a Special Weapon (Flamer, Meltagun, Plasma Gun)." },
      { description: "One model may take a Heavy Weapon (Heavy Bolter, Lascannon, Missile Launcher)." },
      { description: "Sergeant may take Power Weapon, Plasma Pistol, or Combi-weapon." },
    ],
  },
  {
    id: "sm-heavy-intercessors",
    name: "Heavy Intercessor Squad",
    role: "Infantry",
    category: "Battleline",
    stats: { movement: '5"', toughness: 5, save: "3+", wounds: 3, leadership: "6+", oc: 2 },
    models: { min: 5, max: 10 },
    points: 100,
    weapons: [
      { name: "Heavy Bolt Rifle", type: "Heavy", range: '36"', attacks: "1", skill: "BS3+", strength: "5", ap: "-1", damage: "2" },
      { name: "Executor Bolt Rifle", type: "Heavy", range: '42"', attacks: "1", skill: "BS3+", strength: "5", ap: "-2", damage: "3" },
      { name: "Close Combat Weapon", type: "Melee", attacks: "3", skill: "WS3+", strength: "5", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Objective Secured", description: "While this unit controls an objective marker, it is treated as having double the number of models for that marker." },
    ],
    keywords: ["Infantry", "Core", "Battleline", "Heavy Intercessors"],
    factionKeywords: ["Adeptus Astartes"],
  },
  // ─── ELITES ───────────────────────────────────────────────────────
  {
    id: "sm-terminators",
    name: "Terminator Squad",
    role: "Infantry",
    category: "Elites",
    canDeepStrike: true,
    stats: { movement: '5"', toughness: 5, save: "2+", wounds: 3, leadership: "6+", oc: 1 },
    models: { min: 5, max: 10 },
    points: 175,
    weapons: [
      { name: "Storm Bolter", type: "Rapid Fire", range: '24"', attacks: "2", skill: "BS3+", strength: "4", ap: "0", damage: "1" },
      { name: "Power Fist", type: "Melee", attacks: "3", skill: "WS3+", strength: "8", ap: "-2", damage: "2" },
    ],
    abilities: [
      { name: "Deep Strike", description: "Can be set up in Strategic Reserves anywhere more than 9\" from enemy models." },
      { name: "Teleport Homer", description: "Friendly Terminator units arriving from Deep Strike can be set up within 6\" of this unit." },
    ],
    keywords: ["Infantry", "Core", "Terminator", "Terminator Squad"],
    factionKeywords: ["Adeptus Astartes"],
    wargearOptions: [
      { description: "One model per 5 may replace Storm Bolter + Power Fist with Assault Cannon + Power Fist." },
      { description: "One model per 5 may replace Storm Bolter with Heavy Flamer." },
      { description: "Sergeant may take Thunder Hammer + Storm Shield." },
    ],
  },
  {
    id: "sm-relic-terminators",
    name: "Relic Terminator Squad",
    role: "Infantry",
    category: "Elites",
    canDeepStrike: true,
    stats: { movement: '5"', toughness: 5, save: "2+", wounds: 3, leadership: "5+", oc: 1 },
    models: { min: 5, max: 10 },
    points: 200,
    weapons: [
      { name: "Combi-bolter", type: "Rapid Fire", range: '24"', attacks: "2", skill: "BS3+", strength: "4", ap: "0", damage: "1" },
      { name: "Power Fist", type: "Melee", attacks: "3", skill: "WS3+", strength: "8", ap: "-2", damage: "2" },
    ],
    abilities: [
      { name: "Deep Strike", description: "Can be set up in Strategic Reserves anywhere more than 9\" from enemy models." },
      { name: "Relics of the Chapter", description: "Add 1 to wound rolls for this unit's melee weapons." },
    ],
    keywords: ["Infantry", "Core", "Terminator", "Relic Terminator Squad"],
    factionKeywords: ["Adeptus Astartes"],
    wargearOptions: [
      { description: "Any model may replace Combi-bolter with Heavy Flamer or Reaper Autocannon." },
      { description: "Any model may replace Power Fist with Chain Fist, Power Maul, or Lightning Claw." },
    ],
  },
  {
    id: "sm-sternguard",
    name: "Sternguard Veteran Squad",
    role: "Infantry",
    category: "Elites",
    stats: { movement: '6"', toughness: 4, save: "3+", wounds: 2, leadership: "6+", oc: 1 },
    models: { min: 5, max: 10 },
    points: 95,
    weapons: [
      { name: "Sternguard Bolt Rifle", type: "Assault", range: '30"', attacks: "2", skill: "BS2+", strength: "4", ap: "-2", damage: "2" },
      { name: "Close Combat Weapon", type: "Melee", attacks: "3", skill: "WS3+", strength: "4", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Veteran Marksmen", description: "This unit's ranged weapons have the Precision keyword." },
    ],
    keywords: ["Infantry", "Core", "Sternguard Veterans"],
    factionKeywords: ["Adeptus Astartes"],
    wargearOptions: [
      { description: "Up to 2 models may take a Heavy Weapon (Lascannon, Multi-melta, Heavy Bolter)." },
    ],
  },
  {
    id: "sm-vanguard-veterans",
    name: "Vanguard Veteran Squad",
    role: "Infantry",
    category: "Elites",
    canFly: true,
    canDeepStrike: true,
    stats: { movement: '12"', toughness: 4, save: "3+", wounds: 2, leadership: "6+", oc: 1 },
    models: { min: 5, max: 10 },
    points: 130,
    weapons: [
      { name: "Heavy Bolt Pistol", type: "Pistol", range: '18"', attacks: "1", skill: "BS2+", strength: "4", ap: "-1", damage: "1" },
      { name: "Astartes Chainsword", type: "Melee", attacks: "4", skill: "WS2+", strength: "4", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Fly", description: "Can move over models and terrain." },
      { name: "Deep Strike", description: "Can be set up in Strategic Reserves anywhere more than 9\" from enemy models." },
    ],
    keywords: ["Infantry", "Core", "Jump Pack", "Fly", "Vanguard Veterans"],
    factionKeywords: ["Adeptus Astartes"],
    wargearOptions: [
      { description: "Any model may replace pistol with Plasma Pistol. Any model may replace Chainsword with Power Weapon, Power Fist, or Thunder Hammer." },
    ],
  },
  {
    id: "sm-bladeguard",
    name: "Bladeguard Veteran Squad",
    role: "Infantry",
    category: "Elites",
    stats: { movement: '6"', toughness: 4, save: "3+/4++", wounds: 3, leadership: "6+", oc: 1 },
    models: { min: 3, max: 6 },
    points: 115,
    weapons: [
      { name: "Master-crafted Power Sword", type: "Melee", attacks: "4", skill: "WS2+", strength: "5", ap: "-3", damage: "2" },
      { name: "Heavy Bolt Pistol", type: "Pistol", range: '18"', attacks: "1", skill: "BS3+", strength: "4", ap: "-1", damage: "1" },
    ],
    abilities: [
      { name: "Storm Shield", description: "Each model in this unit has a Storm Shield, granting a 4++ invulnerable save." },
    ],
    keywords: ["Infantry", "Core", "Bladeguard Veterans"],
    factionKeywords: ["Adeptus Astartes"],
  },
  {
    id: "sm-bladeguard-ancient",
    name: "Bladeguard Ancient",
    role: "Character",
    category: "Elites",
    stats: { movement: '6"', toughness: 4, save: "3+", wounds: 4, leadership: "5+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 65,
    weapons: [
      { name: "Master-crafted Power Sword", type: "Melee", attacks: "4", skill: "WS2+", strength: "5", ap: "-3", damage: "2" },
      { name: "Heavy Bolt Pistol", type: "Pistol", range: '18"', attacks: "1", skill: "BS2+", strength: "4", ap: "-1", damage: "1" },
    ],
    abilities: [
      { name: "Ancient's Banner", description: "Friendly Bladeguard and Bladeguard Veteran units within 6\" re-roll wound rolls of 1." },
    ],
    keywords: ["Infantry", "Character", "Ancient"],
    factionKeywords: ["Adeptus Astartes"],
  },
  {
    id: "sm-victrix-honour-guard",
    name: "Victrix Honour Guard",
    role: "Infantry",
    category: "Elites",
    stats: { movement: '6"', toughness: 4, save: "2+", wounds: 3, leadership: "4+", oc: 1 },
    models: { min: 2, max: 2 },
    points: 75,
    weapons: [
      { name: "Vigil Spear", type: "Melee", attacks: "3", skill: "WS3+", strength: "6", ap: "-2", damage: "2" },
      { name: "Vigil Spear", type: "Ranged", range: '18"', attacks: "2", skill: "BS3+", strength: "5", ap: "-1", damage: "2" },
    ],
    abilities: [
      { name: "Praesidium Shield", description: "Each model in this unit has a 4++ invulnerable save from Praesidium Shields." },
      { name: "Bodyguards of the Primarch", description: "While a friendly Primarch or Chapter Master model is within 3\" of this unit, that model has the Lone Operative ability." },
    ],
    keywords: ["Infantry", "Core", "Victrix Honour Guard"],
    factionKeywords: ["Adeptus Astartes", "Ultramarines"],
  },
  {
    id: "sm-centurion-assault",
    name: "Centurion Assault Squad",
    role: "Infantry",
    category: "Elites",
    stats: { movement: '5"', toughness: 6, save: "2+", wounds: 4, leadership: "6+", oc: 1 },
    models: { min: 3, max: 6 },
    points: 165,
    weapons: [
      { name: "Meltagun", type: "Heavy", range: '12"', attacks: "1", skill: "BS3+", strength: "9", ap: "-4", damage: "D6", keywords: ["Melta 2"] },
      { name: "Flamer", type: "Heavy", range: '12"', attacks: "D6", skill: "BS-", strength: "4", ap: "0", damage: "1", keywords: ["Torrent"] },
      { name: "Siege Drill", type: "Melee", attacks: "2", skill: "WS4+", strength: "14", ap: "-4", damage: "3" },
    ],
    abilities: [
      { name: "Decimator Protocols", description: "Each time this unit shoots, it can target enemy units not visible to it (but with -1 to hit)." },
    ],
    keywords: ["Infantry", "Core", "Centurions"],
    factionKeywords: ["Adeptus Astartes"],
    wargearOptions: [
      { description: "All models may replace Flamers with Hurricane Bolters." },
    ],
  },
  {
    id: "sm-company-heroes",
    name: "Company Heroes",
    role: "Infantry",
    category: "Elites",
    stats: { movement: '6"', toughness: 4, save: "3+", wounds: 2, leadership: "6+", oc: 1 },
    models: { min: 5, max: 5 },
    points: 75,
    weapons: [
      { name: "Bolt Pistol", type: "Pistol", range: '12"', attacks: "1", skill: "BS3+", strength: "4", ap: "0", damage: "1" },
      { name: "Close Combat Weapon", type: "Melee", attacks: "3", skill: "WS3+", strength: "4", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Bodyguard", description: "While the unit this model is leading is targeted, roll D6 each time a saving throw is failed. On 4+, a Company Heroes model suffers the wound instead." },
    ],
    keywords: ["Infantry", "Core", "Company Heroes"],
    factionKeywords: ["Adeptus Astartes"],
  },
  {
    id: "sm-servitors",
    name: "Servitors",
    role: "Infantry",
    category: "Elites",
    stats: { movement: '5"', toughness: 3, save: "4+", wounds: 1, leadership: "8+", oc: 1 },
    models: { min: 4, max: 4 },
    points: 45,
    weapons: [
      { name: "Servo-arm", type: "Melee", attacks: "2", skill: "WS4+", strength: "8", ap: "-2", damage: "2" },
      { name: "Multi-melta", type: "Heavy", range: '18"', attacks: "2", skill: "BS4+", strength: "9", ap: "-4", damage: "D6", keywords: ["Melta 2"] },
    ],
    abilities: [
      { name: "Mindlock", description: "Unless within 6\" of a friendly Techmarine, Servitors must subtract 1 from hit rolls." },
    ],
    keywords: ["Infantry", "Servitors"],
    factionKeywords: ["Adeptus Astartes"],
    wargearOptions: [
      { description: "Up to 2 models may replace Servo-arm with Multi-melta, Heavy Bolter, or Plasma Cannon." },
    ],
  },
  {
    id: "sm-eliminators",
    name: "Eliminator Squad",
    role: "Infantry",
    category: "Elites",
    stats: { movement: '6"', toughness: 4, save: "3+", wounds: 2, leadership: "5+", oc: 1 },
    models: { min: 3, max: 3 },
    points: 75,
    weapons: [
      { name: "Bolt Sniper Rifle", type: "Heavy", range: '36"', attacks: "1", skill: "BS2+", strength: "5", ap: "-2", damage: "3", keywords: ["Precision", "Stealth"] },
      { name: "Bolt Pistol", type: "Pistol", range: '12"', attacks: "1", skill: "BS2+", strength: "4", ap: "0", damage: "1" },
      { name: "Close Combat Weapon", type: "Melee", attacks: "2", skill: "WS3+", strength: "4", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Camo Cloak", description: "While not the closest enemy unit, this unit has the Stealth ability. Each time an attack targets this unit, the attacker suffers -1 to hit." },
      { name: "Covering Fire", description: "Each time this unit shoots, one enemy Infantry unit hit loses the benefit of cover until end of turn." },
    ],
    keywords: ["Infantry", "Core", "Phobos", "Eliminators"],
    factionKeywords: ["Adeptus Astartes"],
    wargearOptions: [
      { description: "All models may replace Bolt Sniper Rifle with Las Fusil (Heavy, R36\", A1, BS2+, S10, AP-4, D3, Precision)." },
    ],
  },
  // ─── FAST ATTACK ──────────────────────────────────────────────────
  {
    id: "sm-assault-marines",
    name: "Assault Marine Squad",
    role: "Infantry",
    category: "Fast Attack",
    canFly: true,
    canDeepStrike: true,
    stats: { movement: '12"', toughness: 4, save: "3+", wounds: 2, leadership: "6+", oc: 1 },
    models: { min: 5, max: 10 },
    points: 75,
    weapons: [
      { name: "Bolt Pistol", type: "Pistol", range: '12"', attacks: "1", skill: "BS3+", strength: "4", ap: "0", damage: "1" },
      { name: "Astartes Chainsword", type: "Melee", attacks: "4", skill: "WS3+", strength: "4", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Fly", description: "Can move over models and terrain." },
      { name: "Deep Strike", description: "Can be set up in Strategic Reserves anywhere more than 9\" from enemy models." },
      { name: "Jump Pack Assault", description: "On a turn this unit makes a Charge move, add 1 to charge rolls." },
    ],
    keywords: ["Infantry", "Core", "Jump Pack", "Fly", "Assault Marines"],
    factionKeywords: ["Adeptus Astartes"],
    wargearOptions: [
      { description: "One model per 5 may take Flamer or Plasma Pistol. Sergeant may take Thunder Hammer or Power Weapon." },
    ],
  },
  {
    id: "sm-outriders",
    name: "Outrider Squad",
    role: "Mounted",
    category: "Fast Attack",
    stats: { movement: '14"', toughness: 5, save: "3+", wounds: 4, leadership: "6+", oc: 2 },
    models: { min: 3, max: 6 },
    points: 130,
    weapons: [
      { name: "Outrider Bike Bolters", type: "Rapid Fire", range: '24"', attacks: "4", skill: "BS3+", strength: "4", ap: "0", damage: "1" },
      { name: "Astartes Chainsword", type: "Melee", attacks: "4", skill: "WS3+", strength: "5", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Turbo-boost", description: "When this unit Advances, add 6\" to its Move instead of rolling." },
      { name: "Scouts 6\"", description: "Before the first battle round, this unit can make a Normal Move of up to 6\"." },
    ],
    keywords: ["Mounted", "Core", "Outriders"],
    factionKeywords: ["Adeptus Astartes"],
  },
  {
    id: "sm-inceptors",
    name: "Inceptor Squad",
    role: "Infantry",
    category: "Fast Attack",
    canFly: true,
    canDeepStrike: true,
    stats: { movement: '10"', toughness: 5, save: "3+", wounds: 3, leadership: "6+", oc: 1 },
    models: { min: 3, max: 6 },
    points: 120,
    weapons: [
      { name: "Assault Bolter", type: "Assault", range: '18"', attacks: "3", skill: "BS3+", strength: "5", ap: "-1", damage: "1" },
      { name: "Close Combat Weapon", type: "Melee", attacks: "3", skill: "WS3+", strength: "5", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Fly", description: "Can move over models and terrain." },
      { name: "Deep Strike", description: "Can be set up in Strategic Reserves anywhere more than 9\" from enemy models." },
    ],
    keywords: ["Infantry", "Core", "Jump Pack", "Fly", "Inceptors"],
    factionKeywords: ["Adeptus Astartes"],
    wargearOptions: [
      { description: "All models may replace Assault Bolters with Plasma Exterminators (Assault, R24\", A2, BS3+, S7, AP-3, D2, Hazardous)." },
    ],
  },
  {
    id: "sm-attack-bikes",
    name: "Attack Bike Squad",
    role: "Mounted",
    category: "Fast Attack",
    stats: { movement: '12"', toughness: 5, save: "3+", wounds: 4, leadership: "6+", oc: 2 },
    models: { min: 1, max: 3 },
    points: 55,
    weapons: [
      { name: "Twin Boltgun", type: "Rapid Fire", range: '24"', attacks: "2", skill: "BS3+", strength: "4", ap: "0", damage: "1" },
      { name: "Multi-melta", type: "Heavy", range: '18"', attacks: "2", skill: "BS3+", strength: "9", ap: "-4", damage: "D6", keywords: ["Melta 2"] },
      { name: "Close Combat Weapon", type: "Melee", attacks: "3", skill: "WS3+", strength: "5", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Turbo-boost", description: "When this unit Advances, add 6\" to its Move instead of rolling." },
    ],
    keywords: ["Mounted", "Core", "Attack Bike"],
    factionKeywords: ["Adeptus Astartes"],
    wargearOptions: [
      { description: "Any model may replace Multi-melta with Heavy Bolter (3 attacks, S5, AP-1, D2)." },
    ],
  },
  {
    id: "sm-land-speeders",
    name: "Land Speeder Squadron",
    role: "Vehicle",
    category: "Fast Attack",
    canFly: true,
    stats: { movement: '14"', toughness: 7, save: "3+", wounds: 6, leadership: "6+", oc: 2 },
    models: { min: 1, max: 3 },
    points: 60,
    weapons: [
      { name: "Multi-melta", type: "Heavy", range: '18"', attacks: "2", skill: "BS3+", strength: "9", ap: "-4", damage: "D6", keywords: ["Melta 2"] },
      { name: "Heavy Bolter", type: "Heavy", range: '36"', attacks: "3", skill: "BS3+", strength: "5", ap: "-1", damage: "2" },
    ],
    abilities: [
      { name: "Fly", description: "Can move over models and terrain." },
      { name: "Hover", description: "This model has the FLY keyword and does not need to land." },
    ],
    keywords: ["Vehicle", "Fly", "Land Speeder"],
    factionKeywords: ["Adeptus Astartes"],
    wargearOptions: [
      { description: "May replace Multi-melta with Assault Cannon. May replace Heavy Bolter with Typhoon Missile Launcher." },
    ],
  },
  {
    id: "sm-storm-speeder-hammerstrike",
    name: "Storm Speeder Hammerstrike",
    role: "Vehicle",
    category: "Fast Attack",
    canFly: true,
    stats: { movement: '14"', toughness: 7, save: "3+", wounds: 8, leadership: "6+", oc: 2 },
    models: { min: 1, max: 1 },
    points: 140,
    weapons: [
      { name: "Melta Destroyer", type: "Heavy", range: '18"', attacks: "2", skill: "BS3+", strength: "9", ap: "-4", damage: "D6", keywords: ["Melta 2"] },
      { name: "Hammerstrike Missile Launcher", type: "Heavy", range: '36"', attacks: "2", skill: "BS3+", strength: "10", ap: "-4", damage: "D6" },
      { name: "Twin Bolt Rifle", type: "Rapid Fire", range: '30"', attacks: "2", skill: "BS3+", strength: "4", ap: "-1", damage: "1" },
    ],
    abilities: [
      { name: "Fly", description: "Can move over models and terrain." },
    ],
    keywords: ["Vehicle", "Fly", "Storm Speeder"],
    factionKeywords: ["Adeptus Astartes"],
  },
  {
    id: "sm-storm-speeder-hailstrike",
    name: "Storm Speeder Hailstrike",
    role: "Vehicle",
    category: "Fast Attack",
    canFly: true,
    stats: { movement: '14"', toughness: 7, save: "3+", wounds: 8, leadership: "6+", oc: 2 },
    models: { min: 1, max: 1 },
    points: 125,
    weapons: [
      { name: "Onslaught Gatling Cannon", type: "Heavy", range: '24"', attacks: "12", skill: "BS3+", strength: "6", ap: "-1", damage: "2" },
      { name: "Icarus Rocket Pod", type: "Heavy", range: '24"', attacks: "D6", skill: "BS3+", strength: "8", ap: "-1", damage: "2", keywords: ["Anti-Fly 2+"] },
      { name: "Twin Bolt Rifle", type: "Rapid Fire", range: '30"', attacks: "2", skill: "BS3+", strength: "4", ap: "-1", damage: "1" },
    ],
    abilities: [
      { name: "Fly", description: "Can move over models and terrain." },
    ],
    keywords: ["Vehicle", "Fly", "Storm Speeder"],
    factionKeywords: ["Adeptus Astartes"],
  },
  {
    id: "sm-storm-speeder-thunderstrike",
    name: "Storm Speeder Thunderstrike",
    role: "Vehicle",
    category: "Fast Attack",
    canFly: true,
    stats: { movement: '14"', toughness: 7, save: "3+", wounds: 8, leadership: "6+", oc: 2 },
    models: { min: 1, max: 1 },
    points: 130,
    weapons: [
      { name: "Thunderstrike Laser", type: "Heavy", range: '48"', attacks: "1", skill: "BS3+", strength: "14", ap: "-4", damage: "D6+4" },
      { name: "Stormfury Missiles", type: "Heavy", range: '24"', attacks: "2D6", skill: "BS3+", strength: "6", ap: "-1", damage: "1", keywords: ["Blast"] },
      { name: "Twin Bolt Rifle", type: "Rapid Fire", range: '30"', attacks: "2", skill: "BS3+", strength: "4", ap: "-1", damage: "1" },
    ],
    abilities: [
      { name: "Fly", description: "Can move over models and terrain." },
    ],
    keywords: ["Vehicle", "Fly", "Storm Speeder"],
    factionKeywords: ["Adeptus Astartes"],
  },
  // ─── HEAVY SUPPORT ────────────────────────────────────────────────
  {
    id: "sm-devastator-squad",
    name: "Devastator Squad",
    role: "Infantry",
    category: "Heavy Support",
    stats: { movement: '6"', toughness: 4, save: "3+", wounds: 2, leadership: "6+", oc: 1 },
    models: { min: 5, max: 10 },
    points: 95,
    weapons: [
      { name: "Boltgun", type: "Rapid Fire", range: '24"', attacks: "1", skill: "BS3+", strength: "4", ap: "0", damage: "1" },
      { name: "Lascannon", type: "Heavy", range: '48"', attacks: "1", skill: "BS3+", strength: "12", ap: "-3", damage: "D6+1" },
      { name: "Multi-melta", type: "Heavy", range: '18"', attacks: "2", skill: "BS3+", strength: "9", ap: "-4", damage: "D6", keywords: ["Melta 2"] },
      { name: "Missile Launcher (Krak)", type: "Heavy", range: '48"', attacks: "1", skill: "BS3+", strength: "9", ap: "-2", damage: "D6" },
    ],
    abilities: [
      { name: "Signum", description: "One model per turn may use Signum: add 1 to hit rolls for this unit's Heavy weapons this phase." },
    ],
    keywords: ["Infantry", "Core", "Devastators"],
    factionKeywords: ["Adeptus Astartes"],
    wargearOptions: [
      { description: "Up to 4 models may replace Boltgun with a Heavy Weapon (Heavy Bolter, Lascannon, Missile Launcher, Multi-melta, Plasma Cannon, Grav-cannon)." },
    ],
  },
  {
    id: "sm-hellblasters",
    name: "Hellblaster Squad",
    role: "Infantry",
    category: "Heavy Support",
    stats: { movement: '6"', toughness: 4, save: "3+", wounds: 2, leadership: "6+", oc: 1 },
    models: { min: 5, max: 10 },
    points: 150,
    weapons: [
      { name: "Plasma Incinerator (Standard)", type: "Rapid Fire", range: '30"', attacks: "1", skill: "BS3+", strength: "7", ap: "-2", damage: "2" },
      { name: "Plasma Incinerator (Supercharge)", type: "Rapid Fire", range: '30"', attacks: "1", skill: "BS3+", strength: "8", ap: "-3", damage: "3", keywords: ["Hazardous"] },
      { name: "Close Combat Weapon", type: "Melee", attacks: "2", skill: "WS3+", strength: "4", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Rapid Fire (Plasma)", description: "When remaining stationary, each model fires one additional shot." },
    ],
    keywords: ["Infantry", "Core", "Hellblasters"],
    factionKeywords: ["Adeptus Astartes"],
  },
  {
    id: "sm-eradicators",
    name: "Eradicator Squad",
    role: "Infantry",
    category: "Heavy Support",
    stats: { movement: '5"', toughness: 5, save: "3+", wounds: 3, leadership: "6+", oc: 1 },
    models: { min: 3, max: 6 },
    points: 95,
    weapons: [
      { name: "Multi-melta", type: "Heavy", range: '18"', attacks: "2", skill: "BS3+", strength: "9", ap: "-4", damage: "D6", keywords: ["Melta 2"] },
      { name: "Close Combat Weapon", type: "Melee", attacks: "3", skill: "WS3+", strength: "5", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Total Obliteration", description: "Add 1 to the Attacks characteristic of this unit's weapons when targeting Monsters or Vehicles." },
    ],
    keywords: ["Infantry", "Core", "Eradicators"],
    factionKeywords: ["Adeptus Astartes"],
    wargearOptions: [
      { description: "Any model may replace Multi-melta with Melta Rifle (Heavy, R24\", A1, BS3+, S9, AP-4, D3, Melta 2)." },
    ],
  },
  {
    id: "sm-aggressors-boltstorm",
    name: "Aggressor Squad (Boltstorm)",
    role: "Infantry",
    category: "Heavy Support",
    stats: { movement: '5"', toughness: 5, save: "3+", wounds: 3, leadership: "6+", oc: 1 },
    models: { min: 3, max: 6 },
    points: 120,
    weapons: [
      { name: "Boltstorm Gauntlet", type: "Pistol", range: '18"', attacks: "3", skill: "BS3+", strength: "4", ap: "0", damage: "1" },
      { name: "Boltstorm Gauntlet", type: "Melee", attacks: "3", skill: "WS3+", strength: "7", ap: "-1", damage: "2" },
      { name: "Fragstorm Grenade Launcher", type: "Assault", range: '18"', attacks: "D6", skill: "BS3+", strength: "4", ap: "0", damage: "1", keywords: ["Blast"] },
    ],
    abilities: [
      { name: "Fire Storm", description: "Each time this unit shoots, if it did not move in the preceding Movement phase, add 1 to all hit rolls." },
    ],
    keywords: ["Infantry", "Core", "Aggressors"],
    factionKeywords: ["Adeptus Astartes"],
  },
  {
    id: "sm-aggressors-flamestorm",
    name: "Aggressor Squad (Flamestorm)",
    role: "Infantry",
    category: "Heavy Support",
    stats: { movement: '5"', toughness: 5, save: "3+", wounds: 3, leadership: "6+", oc: 1 },
    models: { min: 3, max: 6 },
    points: 125,
    weapons: [
      { name: "Flamestorm Gauntlet", type: "Heavy", range: '12"', attacks: "D6", skill: "BS-", strength: "6", ap: "-2", damage: "2", keywords: ["Torrent"] },
      { name: "Flamestorm Gauntlet", type: "Melee", attacks: "3", skill: "WS3+", strength: "7", ap: "-1", damage: "2" },
    ],
    abilities: [
      { name: "Fire Storm", description: "Each time this unit shoots, if it did not move in the preceding Movement phase, add 1 to all hit rolls." },
    ],
    keywords: ["Infantry", "Core", "Aggressors"],
    factionKeywords: ["Adeptus Astartes"],
  },
  {
    id: "sm-predator-destructor",
    name: "Predator Destructor",
    role: "Vehicle",
    category: "Heavy Support",
    stats: { movement: '10"', toughness: 11, save: "3+", wounds: 11, leadership: "6+", oc: 3 },
    models: { min: 1, max: 1 },
    points: 110,
    weapons: [
      { name: "Predator Autocannon", type: "Heavy", range: '48"', attacks: "4", skill: "BS3+", strength: "9", ap: "-1", damage: "3" },
      { name: "Heavy Bolter", type: "Heavy", range: '36"', attacks: "3", skill: "BS3+", strength: "5", ap: "-1", damage: "2" },
      { name: "Armoured Tracks", type: "Melee", attacks: "3", skill: "WS4+", strength: "7", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Smoke", description: "Once per battle, this model can use smoke launchers: until end of opponent's next turn, gains benefit of cover." },
    ],
    keywords: ["Vehicle", "Core", "Smoke", "Predator"],
    factionKeywords: ["Adeptus Astartes"],
    wargearOptions: [
      { description: "May replace Heavy Bolter sponsons with Lascannon sponsons (+10pts each)." },
    ],
  },
  {
    id: "sm-predator-annihilator",
    name: "Predator Annihilator",
    role: "Vehicle",
    category: "Heavy Support",
    stats: { movement: '10"', toughness: 11, save: "3+", wounds: 11, leadership: "6+", oc: 3 },
    models: { min: 1, max: 1 },
    points: 130,
    weapons: [
      { name: "Twin Lascannon", type: "Heavy", range: '48"', attacks: "2", skill: "BS3+", strength: "12", ap: "-3", damage: "D6+1" },
      { name: "Lascannon", type: "Heavy", range: '48"', attacks: "1", skill: "BS3+", strength: "12", ap: "-3", damage: "D6+1" },
      { name: "Armoured Tracks", type: "Melee", attacks: "3", skill: "WS4+", strength: "7", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Smoke", description: "Once per battle, this model can use smoke launchers for cover benefit." },
    ],
    keywords: ["Vehicle", "Core", "Smoke", "Predator"],
    factionKeywords: ["Adeptus Astartes"],
    wargearOptions: [
      { description: "May replace Lascannon sponsons with Heavy Bolter sponsons." },
    ],
  },
  {
    id: "sm-vindicator",
    name: "Vindicator",
    role: "Vehicle",
    category: "Heavy Support",
    stats: { movement: '10"', toughness: 11, save: "3+", wounds: 12, leadership: "6+", oc: 3 },
    models: { min: 1, max: 1 },
    points: 185,
    weapons: [
      { name: "Demolisher Cannon", type: "Heavy", range: '24"', attacks: "D3", skill: "BS3+", strength: "14", ap: "-3", damage: "D6", keywords: ["Blast"] },
      { name: "Storm Bolter", type: "Rapid Fire", range: '24"', attacks: "2", skill: "BS3+", strength: "4", ap: "0", damage: "1" },
      { name: "Armoured Tracks", type: "Melee", attacks: "3", skill: "WS4+", strength: "7", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Smoke", description: "Once per battle, this model can use smoke launchers for cover benefit." },
    ],
    keywords: ["Vehicle", "Core", "Smoke", "Vindicator"],
    factionKeywords: ["Adeptus Astartes"],
  },
  {
    id: "sm-whirlwind",
    name: "Whirlwind",
    role: "Vehicle",
    category: "Heavy Support",
    stats: { movement: '10"', toughness: 10, save: "3+", wounds: 10, leadership: "6+", oc: 3 },
    models: { min: 1, max: 1 },
    points: 105,
    weapons: [
      { name: "Whirlwind Multiple Missile Launcher", type: "Heavy", range: '48"', attacks: "2D6", skill: "BS3+", strength: "6", ap: "-1", damage: "2", keywords: ["Indirect Fire", "Blast"] },
      { name: "Storm Bolter", type: "Rapid Fire", range: '24"', attacks: "2", skill: "BS3+", strength: "4", ap: "0", damage: "1" },
      { name: "Armoured Tracks", type: "Melee", attacks: "3", skill: "WS4+", strength: "7", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Smoke", description: "Once per battle, this model can use smoke launchers for cover benefit." },
      { name: "Indirect Fire", description: "This model's main weapon can target units not visible to it." },
    ],
    keywords: ["Vehicle", "Core", "Smoke", "Whirlwind"],
    factionKeywords: ["Adeptus Astartes"],
  },
  {
    id: "sm-hunter",
    name: "Hunter",
    role: "Vehicle",
    category: "Heavy Support",
    stats: { movement: '10"', toughness: 10, save: "3+", wounds: 10, leadership: "6+", oc: 3 },
    models: { min: 1, max: 1 },
    points: 95,
    weapons: [
      { name: "Skyspear Missile Launcher", type: "Heavy", range: '60"', attacks: "2", skill: "BS2+", strength: "14", ap: "-3", damage: "D6+2", keywords: ["Anti-Fly 2+"] },
      { name: "Armoured Tracks", type: "Melee", attacks: "3", skill: "WS4+", strength: "7", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Smoke", description: "Once per battle, this model can use smoke launchers for cover benefit." },
      { name: "Hunter-killer", description: "+1 to wound rolls against Fly units." },
    ],
    keywords: ["Vehicle", "Core", "Smoke", "Hunter"],
    factionKeywords: ["Adeptus Astartes"],
  },
  {
    id: "sm-stalker",
    name: "Stalker",
    role: "Vehicle",
    category: "Heavy Support",
    stats: { movement: '10"', toughness: 10, save: "3+", wounds: 10, leadership: "6+", oc: 3 },
    models: { min: 1, max: 1 },
    points: 90,
    weapons: [
      { name: "Icarus Stormcannon Array", type: "Heavy", range: '48"', attacks: "6", skill: "BS2+", strength: "8", ap: "-1", damage: "2", keywords: ["Anti-Fly 2+"] },
      { name: "Armoured Tracks", type: "Melee", attacks: "3", skill: "WS4+", strength: "7", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Smoke", description: "Once per battle, this model can use smoke launchers for cover benefit." },
      { name: "Targeting Array", description: "+1 to wound rolls against Fly units." },
    ],
    keywords: ["Vehicle", "Core", "Smoke", "Stalker"],
    factionKeywords: ["Adeptus Astartes"],
  },
  {
    id: "sm-dreadnought",
    name: "Dreadnought",
    role: "Vehicle",
    category: "Elites",
    stats: { movement: '6"', toughness: 9, save: "2+", wounds: 8, leadership: "6+", oc: 3 },
    models: { min: 1, max: 1 },
    points: 100,
    weapons: [
      { name: "Dreadnought Combat Weapon", type: "Melee", attacks: "5", skill: "WS3+", strength: "12", ap: "-2", damage: "3" },
      { name: "Multi-melta", type: "Heavy", range: '18"', attacks: "2", skill: "BS3+", strength: "9", ap: "-4", damage: "D6", keywords: ["Melta 2"] },
    ],
    abilities: [
      { name: "Smoke", description: "Once per battle, can use smoke launchers for cover benefit." },
    ],
    keywords: ["Vehicle", "Core", "Smoke", "Walker", "Dreadnought"],
    factionKeywords: ["Adeptus Astartes"],
    wargearOptions: [
      { description: "May replace Multi-melta with Assault Cannon, Heavy Plasma Cannon, or Twin Lascannon." },
      { description: "May replace Dreadnought Combat Weapon with Missile Launcher." },
    ],
  },
  {
    id: "sm-venerable-dreadnought",
    name: "Venerable Dreadnought",
    role: "Vehicle",
    category: "Elites",
    stats: { movement: '6"', toughness: 9, save: "2+", wounds: 8, leadership: "5+", oc: 3 },
    models: { min: 1, max: 1 },
    points: 155,
    weapons: [
      { name: "Dreadnought Combat Weapon", type: "Melee", attacks: "5", skill: "WS2+", strength: "12", ap: "-2", damage: "3" },
      { name: "Multi-melta", type: "Heavy", range: '18"', attacks: "2", skill: "BS2+", strength: "9", ap: "-4", damage: "D6", keywords: ["Melta 2"] },
    ],
    abilities: [
      { name: "Smoke", description: "Once per battle, can use smoke launchers for cover benefit." },
      { name: "Unyielding Ancient", description: "+1 to hit rolls for all weapons on this model." },
    ],
    keywords: ["Vehicle", "Core", "Smoke", "Walker", "Dreadnought", "Venerable"],
    factionKeywords: ["Adeptus Astartes"],
    wargearOptions: [
      { description: "May replace Multi-melta with Assault Cannon, Twin Lascannon, or Missile Launcher." },
    ],
  },
  {
    id: "sm-ballistus-dreadnought",
    name: "Ballistus Dreadnought",
    role: "Vehicle",
    category: "Elites",
    stats: { movement: '8"', toughness: 9, save: "3+", wounds: 9, leadership: "5+", oc: 3 },
    models: { min: 1, max: 1 },
    points: 130,
    weapons: [
      { name: "Ballistus Lascannon", type: "Heavy", range: '48"', attacks: "2", skill: "BS3+", strength: "12", ap: "-3", damage: "D6+2" },
      { name: "Ballistus Missile Launcher", type: "Heavy", range: '48"', attacks: "2D3", skill: "BS3+", strength: "5", ap: "-1", damage: "2", keywords: ["Blast"] },
      { name: "Twin Bolt Rifle", type: "Rapid Fire", range: '30"', attacks: "2", skill: "BS3+", strength: "4", ap: "-1", damage: "1" },
      { name: "Close Combat Weapon", type: "Melee", attacks: "5", skill: "WS3+", strength: "9", ap: "-1", damage: "2" },
    ],
    abilities: [
      { name: "Smoke", description: "Once per battle, can use smoke launchers for cover benefit." },
    ],
    keywords: ["Vehicle", "Core", "Smoke", "Walker", "Dreadnought"],
    factionKeywords: ["Adeptus Astartes"],
  },
  {
    id: "sm-ironclad-dreadnought",
    name: "Ironclad Dreadnought",
    role: "Vehicle",
    category: "Elites",
    stats: { movement: '6"', toughness: 10, save: "2+", wounds: 8, leadership: "6+", oc: 3 },
    models: { min: 1, max: 1 },
    points: 150,
    weapons: [
      { name: "Seismic Hammer", type: "Melee", attacks: "3", skill: "WS3+", strength: "14", ap: "-3", damage: "D6" },
      { name: "Dreadnought Combat Weapon", type: "Melee", attacks: "4", skill: "WS3+", strength: "12", ap: "-2", damage: "3" },
      { name: "Hurricane Bolter", type: "Rapid Fire", range: '24"', attacks: "6", skill: "BS3+", strength: "4", ap: "0", damage: "1" },
      { name: "Meltagun", type: "Assault", range: '12"', attacks: "1", skill: "BS3+", strength: "9", ap: "-4", damage: "D6", keywords: ["Melta 2"] },
    ],
    abilities: [
      { name: "Smoke", description: "Once per battle, can use smoke launchers for cover benefit." },
      { name: "Siege Breaker", description: "+1 to wound rolls against buildings and fortifications." },
    ],
    keywords: ["Vehicle", "Core", "Smoke", "Walker", "Dreadnought"],
    factionKeywords: ["Adeptus Astartes"],
  },
  {
    id: "sm-centurion-devastator",
    name: "Centurion Devastator Squad",
    role: "Infantry",
    category: "Heavy Support",
    stats: { movement: '5"', toughness: 6, save: "2+", wounds: 4, leadership: "6+", oc: 1 },
    models: { min: 3, max: 6 },
    points: 165,
    weapons: [
      { name: "Grav-cannon", type: "Heavy", range: '24"', attacks: "4", skill: "BS3+", strength: "6", ap: "-1", damage: "2", keywords: ["Devastating Wounds"] },
      { name: "Missile Launcher (Krak)", type: "Heavy", range: '48"', attacks: "1", skill: "BS3+", strength: "9", ap: "-2", damage: "D6" },
      { name: "Omniscope", type: "Melee", attacks: "2", skill: "WS4+", strength: "5", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Decimator Protocols", description: "This unit may shoot at units not visible to it at -1 to hit." },
    ],
    keywords: ["Infantry", "Core", "Centurions"],
    factionKeywords: ["Adeptus Astartes"],
    wargearOptions: [
      { description: "All models may replace Grav-cannons with Twin Heavy Bolters or Multi-meltas." },
    ],
  },
  // ─── DEDICATED TRANSPORTS ────────────────────────────────────────
  {
    id: "sm-rhino",
    name: "Rhino",
    role: "Vehicle",
    category: "Dedicated Transport",
    stats: { movement: '12"', toughness: 9, save: "3+", wounds: 10, leadership: "6+", oc: 2 },
    models: { min: 1, max: 1 },
    points: 75,
    weapons: [
      { name: "Storm Bolter", type: "Rapid Fire", range: '24"', attacks: "2", skill: "BS3+", strength: "4", ap: "0", damage: "1" },
      { name: "Armoured Tracks", type: "Melee", attacks: "3", skill: "WS4+", strength: "6", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Smoke", description: "Once per battle, can use smoke launchers for cover benefit." },
      { name: "Repair", description: "At the start of your Command Phase, this model regains 1 lost wound." },
    ],
    keywords: ["Vehicle", "Core", "Smoke", "Transport", "Rhino"],
    factionKeywords: ["Adeptus Astartes"],
  },
  {
    id: "sm-drop-pod",
    name: "Drop Pod",
    role: "Vehicle",
    category: "Dedicated Transport",
    canDeepStrike: true,
    stats: { movement: '0"', toughness: 9, save: "3+", wounds: 8, leadership: "6+", oc: 2 },
    models: { min: 1, max: 1 },
    points: 70,
    weapons: [
      { name: "Storm Bolter", type: "Rapid Fire", range: '24"', attacks: "2", skill: "BS3+", strength: "4", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Drop Pod Assault", description: "This model always starts in Deep Strike. It can arrive from reserves in any turn, deploying anywhere on the battlefield more than 9\" from enemy models. Units inside can immediately disembark." },
      { name: "Immobile", description: "This model cannot move for any reason." },
    ],
    keywords: ["Vehicle", "Transport", "Drop Pod"],
    factionKeywords: ["Adeptus Astartes"],
  },
  {
    id: "sm-impulsor",
    name: "Impulsor",
    role: "Vehicle",
    category: "Dedicated Transport",
    stats: { movement: '12"', toughness: 9, save: "3+", wounds: 9, leadership: "6+", oc: 2 },
    models: { min: 1, max: 1 },
    points: 85,
    weapons: [
      { name: "Storm Bolter", type: "Rapid Fire", range: '24"', attacks: "2", skill: "BS3+", strength: "4", ap: "0", damage: "1" },
      { name: "Armoured Tracks", type: "Melee", attacks: "3", skill: "WS4+", strength: "6", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Assault Vehicle", description: "Units can disembark from this model after it makes a Normal Move. Units that do so cannot Charge that turn." },
      { name: "Hover", description: "This model can move over models and terrain." },
    ],
    keywords: ["Vehicle", "Fly", "Smoke", "Transport", "Impulsor"],
    factionKeywords: ["Adeptus Astartes"],
    wargearOptions: [
      { description: "May take Shield Dome (2+ save aura) or Orbital Comms Array (once per game, call orbital strike)." },
    ],
  },
  {
    id: "sm-repulsor",
    name: "Repulsor",
    role: "Vehicle",
    category: "Dedicated Transport",
    stats: { movement: '10"', toughness: 12, save: "3+", wounds: 16, leadership: "6+", oc: 5 },
    models: { min: 1, max: 1 },
    points: 230,
    weapons: [
      { name: "Onslaught Gatling Cannon", type: "Heavy", range: '24"', attacks: "12", skill: "BS3+", strength: "6", ap: "-1", damage: "2" },
      { name: "Las-talon", type: "Heavy", range: '36"', attacks: "2", skill: "BS3+", strength: "14", ap: "-4", damage: "D6+2" },
      { name: "Twin Heavy Onslaught Gatling Cannon", type: "Heavy", range: '24"', attacks: "6", skill: "BS3+", strength: "6", ap: "-1", damage: "2" },
      { name: "Armoured Tracks", type: "Melee", attacks: "6", skill: "WS4+", strength: "8", ap: "-1", damage: "2" },
    ],
    abilities: [
      { name: "Hover", description: "This model can move over models and terrain." },
      { name: "Levitation Drive", description: "This model has the Fly keyword." },
    ],
    keywords: ["Vehicle", "Fly", "Smoke", "Transport", "Repulsor"],
    factionKeywords: ["Adeptus Astartes"],
  },
  {
    id: "sm-repulsor-executioner",
    name: "Repulsor Executioner",
    role: "Vehicle",
    category: "Dedicated Transport",
    stats: { movement: '10"', toughness: 12, save: "3+", wounds: 16, leadership: "6+", oc: 5 },
    models: { min: 1, max: 1 },
    points: 235,
    weapons: [
      { name: "Macro Plasma Incinerator (Standard)", type: "Heavy", range: '36"', attacks: "5", skill: "BS3+", strength: "8", ap: "-3", damage: "3" },
      { name: "Macro Plasma Incinerator (Supercharge)", type: "Heavy", range: '36"', attacks: "5", skill: "BS3+", strength: "9", ap: "-4", damage: "D3+3", keywords: ["Hazardous"] },
      { name: "Twin Heavy Bolter", type: "Heavy", range: '36"', attacks: "6", skill: "BS3+", strength: "5", ap: "-1", damage: "2" },
      { name: "Armoured Tracks", type: "Melee", attacks: "6", skill: "WS4+", strength: "8", ap: "-1", damage: "2" },
    ],
    abilities: [
      { name: "Hover", description: "This model can move over models and terrain." },
    ],
    keywords: ["Vehicle", "Fly", "Smoke", "Transport", "Repulsor Executioner"],
    factionKeywords: ["Adeptus Astartes"],
    wargearOptions: [
      { description: "May replace Macro Plasma Incinerator with Heavy Laser Destroyer (Heavy, R48\", A2, BS3+, S16, AP-4, D6+2)." },
    ],
  },
  {
    id: "sm-land-raider-main",
    name: "Land Raider",
    role: "Vehicle",
    category: "Dedicated Transport",
    stats: { movement: '10"', toughness: 13, save: "2+", wounds: 16, leadership: "6+", oc: 5 },
    models: { min: 1, max: 1 },
    points: 250,
    weapons: [
      { name: "Twin Lascannon", type: "Heavy", range: '48"', attacks: "2", skill: "BS3+", strength: "12", ap: "-3", damage: "D6+1" },
      { name: "Twin Heavy Bolter", type: "Heavy", range: '36"', attacks: "6", skill: "BS3+", strength: "5", ap: "-1", damage: "2" },
      { name: "Armoured Tracks", type: "Melee", attacks: "6", skill: "WS4+", strength: "9", ap: "-1", damage: "2" },
    ],
    abilities: [
      { name: "Assault Vehicle", description: "Units can disembark from this model after it makes a Normal Move." },
      { name: "Power of the Machine Spirit", description: "This model can shoot in the same turn it arrives from reserves." },
    ],
    keywords: ["Vehicle", "Core", "Smoke", "Transport", "Land Raider"],
    factionKeywords: ["Adeptus Astartes"],
  },
  {
    id: "sm-land-raider-crusader",
    name: "Land Raider Crusader",
    role: "Vehicle",
    category: "Dedicated Transport",
    stats: { movement: '10"', toughness: 13, save: "2+", wounds: 16, leadership: "6+", oc: 5 },
    models: { min: 1, max: 1 },
    points: 275,
    weapons: [
      { name: "Twin Assault Cannon", type: "Heavy", range: '24"', attacks: "12", skill: "BS3+", strength: "6", ap: "0", damage: "1" },
      { name: "Hurricane Bolter", type: "Rapid Fire", range: '24"', attacks: "6", skill: "BS3+", strength: "4", ap: "0", damage: "1" },
      { name: "Multi-melta", type: "Heavy", range: '18"', attacks: "2", skill: "BS3+", strength: "9", ap: "-4", damage: "D6", keywords: ["Melta 2"] },
      { name: "Armoured Tracks", type: "Melee", attacks: "6", skill: "WS4+", strength: "9", ap: "-1", damage: "2" },
    ],
    abilities: [
      { name: "Assault Vehicle", description: "Units can disembark from this model after it makes a Normal Move." },
      { name: "Frag Assault Launchers", description: "Enemy units that are charged by this model subtract 1 from their hit rolls until end of Fight phase." },
    ],
    keywords: ["Vehicle", "Core", "Smoke", "Transport", "Land Raider"],
    factionKeywords: ["Adeptus Astartes"],
  },
  {
    id: "sm-land-raider-redeemer",
    name: "Land Raider Redeemer",
    role: "Vehicle",
    category: "Dedicated Transport",
    stats: { movement: '10"', toughness: 13, save: "2+", wounds: 16, leadership: "6+", oc: 5 },
    models: { min: 1, max: 1 },
    points: 265,
    weapons: [
      { name: "Flamestorm Cannon", type: "Heavy", range: '12"', attacks: "D6", skill: "BS-", strength: "6", ap: "-2", damage: "2", keywords: ["Torrent"] },
      { name: "Multi-melta", type: "Heavy", range: '18"', attacks: "2", skill: "BS3+", strength: "9", ap: "-4", damage: "D6", keywords: ["Melta 2"] },
      { name: "Twin Heavy Bolter", type: "Heavy", range: '36"', attacks: "6", skill: "BS3+", strength: "5", ap: "-1", damage: "2" },
      { name: "Armoured Tracks", type: "Melee", attacks: "6", skill: "WS4+", strength: "9", ap: "-1", damage: "2" },
    ],
    abilities: [
      { name: "Assault Vehicle", description: "Units can disembark from this model after it makes a Normal Move." },
      { name: "Frag Assault Launchers", description: "Enemy units charged by this model subtract 1 from hit rolls until end of Fight phase." },
    ],
    keywords: ["Vehicle", "Core", "Smoke", "Transport", "Land Raider"],
    factionKeywords: ["Adeptus Astartes"],
  },
];

const GLADIUS_DETACHMENT: Detachment = {
  name: "Gladius Task Force",
  rule: {
    name: "Sons of the Primarch",
    description: "Each time an Adeptus Astartes CORE unit from this detachment shoots or fights, if it has not moved this turn, it gets +1 to all hit rolls. If also within 6\" of a friendly CHARACTER, re-roll wound rolls of 1.",
  },
  stratagems: [
    { name: "Honour the Chapter", cost: 1, phase: "Fight", description: "One friendly Adeptus Astartes unit within 6\" of a CHARACTER gets +1 Attack until end of the Fight phase." },
    { name: "Adaptive Strategy", cost: 1, phase: "Command", description: "One friendly CORE unit can discard its current doctrine and gain the benefits of any other doctrine." },
    { name: "Armour of Contempt", cost: 1, phase: "Any", description: "When a friendly Adeptus Astartes CORE unit takes a wound, roll D6; on a 5+ that wound is ignored." },
    { name: "Rapid Deployment", cost: 1, phase: "Movement", description: "One CORE unit that has not yet moved can immediately make a free 6\" Normal Move." },
    { name: "Fire Discipline", cost: 1, phase: "Shooting", description: "One CORE unit's Heavy weapons gain the benefit of cover for this Shooting phase." },
    { name: "Orbital Bombardment", cost: 2, phase: "Command", description: "Once per battle. Pick one point on the battlefield; until end of turn all enemy units within 6\" are -1 to hit with ranged weapons." },
  ],
  enhancements: [
    { name: "Artificer Armour", points: 10, description: "Bearer's Save improved by 1 (e.g. 3+ → 2+). Also gains a 5++ invulnerable save.", restriction: "Adeptus Astartes CHARACTER" },
    { name: "The Armour Indomitus", points: 20, description: "Bearer has 2+ Save and 4++ invulnerable save. Ranged attacks against bearer suffer -1 AP.", restriction: "Adeptus Astartes CHARACTER" },
    { name: "Seal of Oath", points: 15, description: "At start of each battle round, pick one enemy unit. Until next battle round, friendly Adeptus Astartes units re-roll wound rolls against it.", restriction: "Adeptus Astartes CHARACTER" },
    { name: "Storm of Fire", points: 0, description: "Once per battle, at start of Shooting phase, friendly Adeptus Astartes CORE units within 6\" may re-roll all hit rolls until end of phase.", restriction: "Adeptus Astartes CHARACTER" },
  ],
};

const IRONSTORM_DETACHMENT: Detachment = {
  name: "Ironstorm Spearhead",
  rule: {
    name: "Machine Wrath",
    description: "Each time a VEHICLE model from this detachment shoots, if it did not move in the preceding Movement phase, add 1 to all hit rolls made by that model.",
  },
  stratagems: [
    { name: "Steel Rain", cost: 1, phase: "Shooting", description: "One friendly Vehicle unit's ranged weapons gain the Devastating Wounds keyword until end of Shooting phase." },
    { name: "Point-blank Salvage", cost: 1, phase: "Fight", description: "One friendly Vehicle unit can shoot at Engagement Range enemy units with Pistol weapons at full ballistic skill." },
    { name: "Overcharged Engines", cost: 1, phase: "Movement", description: "One friendly Vehicle unit can Advance and still shoot this turn without penalty." },
    { name: "Emergency Repairs", cost: 1, phase: "Command", description: "One friendly Vehicle model regains D3+1 lost wounds at the start of your Command Phase." },
    { name: "Armoured Superiority", cost: 2, phase: "Any", description: "Use when a friendly Vehicle takes a wound from a melee weapon. Roll D6; on 3+ that wound is ignored." },
  ],
  enhancements: [
    { name: "Machine's Scorn", points: 15, description: "This model's vehicle gains +1 to hit rolls for all ranged weapons when it did not move.", restriction: "Adeptus Astartes CHARACTER riding a Vehicle" },
    { name: "Reliquary of Eons", points: 25, description: "Friendly Vehicles within 6\" of bearer gain a 5++ invulnerable save against ranged attacks.", restriction: "Adeptus Astartes CHARACTER" },
  ],
};

export const SPACE_MARINES_FACTION: Faction = {
  id: "space-marines",
  name: "Space Marines",
  shortName: "SM",
  description: "The Emperor's Angels of Death. Genetically-enhanced superhuman warriors clad in power armour, the Space Marines are humanity's greatest defenders.",
  accentColor: "#1e40af",
  units: SM_UNITS,
  detachments: [GLADIUS_DETACHMENT, IRONSTORM_DETACHMENT],
};
