import type { Unit, Faction, Detachment } from "./types";

export const NECRON_UNITS: Unit[] = [
  // ─── CHARACTERS ───────────────────────────────────────────────────
  {
    id: "nec-silent-king",
    name: "The Silent King",
    role: "Monster",
    category: "Lord of War",
    isEpicHero: true,
    isTitanic: false,
    stats: { movement: '8"', toughness: 12, save: "2+/4++", wounds: 18, leadership: "3+", oc: 5 },
    models: { min: 1, max: 1 },
    points: 440,
    weapons: [
      { name: "Sceptre of Eternal Glory", type: "Melee", attacks: "6", skill: "WS2+", strength: "16", ap: "-4", damage: "D6+2" },
      { name: "Annihilator Beam", type: "Heavy", range: '36"', attacks: "3", skill: "BS2+", strength: "16", ap: "-4", damage: "6" },
    ],
    abilities: [
      { name: "Lord of the Necrons", description: "Friendly Necron units on the board re-roll hit rolls of 1 and wound rolls of 1." },
      { name: "Triarch's Will", description: "At the start of your Command Phase, issue one Triarch's Command to any friendly Necron unit within 18\": either Advance and shoot, or fight twice." },
      { name: "Unstoppable Monolith", description: "Each time an attack is made against this model, that attack only wounds this model on an unmodified wound roll of 4+, regardless of the weapon's Strength." },
      { name: "Living Metal", description: "At the start of your Command Phase, this model regains 1 lost wound." },
    ],
    keywords: ["Monster", "Character", "Epic Hero", "Necron Royalty", "The Silent King"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-imotekh",
    name: "Imotekh the Stormlord",
    role: "Character",
    category: "HQ",
    isEpicHero: true,
    stats: { movement: '6"', toughness: 5, save: "2+/4++", wounds: 6, leadership: "3+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 95,
    weapons: [
      { name: "Staff of the Destroyer", type: "Melee", attacks: "5", skill: "WS2+", strength: "7", ap: "-2", damage: "3" },
      { name: "Gauntlet of Fire", type: "Pistol", range: '12"', attacks: "6", skill: "BS-", strength: "5", ap: "-1", damage: "1", keywords: ["Torrent"] },
    ],
    abilities: [
      { name: "Lord of the Sautekh", description: "Friendly Sautekh Necron CORE units within 6\" re-roll hit rolls of 1." },
      { name: "Hyperlogical Strategy", description: "While Imotekh is on the battlefield, all friendly Necron units get +1 to all hit rolls." },
      { name: "Living Metal", description: "At the start of your Command Phase, this model regains 1 lost wound." },
      { name: "Lord of the Storm", description: "Once per battle round, at the start of the Shooting phase, all enemy units on the battlefield suffer 1 mortal wound on a roll of 6+." },
    ],
    keywords: ["Infantry", "Character", "Epic Hero", "Necron Royalty", "Overlord", "Imotekh"],
    factionKeywords: ["Necrons", "Sautekh"],
  },
  {
    id: "nec-overlord",
    name: "Overlord",
    role: "Character",
    category: "HQ",
    stats: { movement: '6"', toughness: 5, save: "2+", wounds: 5, leadership: "3+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 80,
    weapons: [
      { name: "Tachyon Arrow", type: "Heavy", range: '120"', attacks: "1", skill: "BS2+", strength: "16", ap: "-5", damage: "D6+2", keywords: ["One Shot"] },
      { name: "Staff of Light (Ranged)", type: "Assault", range: '18"', attacks: "3", skill: "BS2+", strength: "5", ap: "-2", damage: "1" },
      { name: "Staff of Light (Melee)", type: "Melee", attacks: "3", skill: "WS2+", strength: "5", ap: "-2", damage: "1" },
      { name: "Voidscythe", type: "Melee", attacks: "3", skill: "WS2+", strength: "10", ap: "-3", damage: "3" },
    ],
    abilities: [
      { name: "My Will Be Done", description: "Re-roll hit rolls of 1 and wound rolls of 1 for one friendly Necron CORE unit within 6\" each Command Phase." },
      { name: "Living Metal", description: "At the start of your Command Phase, this model regains 1 lost wound." },
    ],
    keywords: ["Infantry", "Character", "Necron Royalty", "Overlord"],
    factionKeywords: ["Necrons"],
    wargearOptions: [
      { description: "May replace Staff of Light with a Voidscythe." },
      { description: "May take a Resurrection Orb (+15pts): once per battle, at the end of any phase, a friendly Necron INFANTRY unit within 6\" immediately triggers Reanimation Protocols." },
    ],
    weaponOptions: [
      {
        replaces: "Tachyon Arrow",
        options: [
          { name: "Voidscythe (Swap)", type: "Melee", attacks: "3", skill: "WS2+", strength: "10", ap: "-3", damage: "3" },
        ],
      },
    ],
  },
  {
    id: "nec-cryptek",
    name: "Cryptek",
    role: "Character",
    category: "HQ",
    stats: { movement: '6"', toughness: 4, save: "3+", wounds: 4, leadership: "3+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 55,
    weapons: [
      { name: "Arkana Conduit", type: "Melee", attacks: "3", skill: "WS3+", strength: "5", ap: "-2", damage: "1" },
    ],
    abilities: [
      { name: "Rites of Reanimation", description: "+1 to Reanimation Protocol rolls for a friendly Necron INFANTRY unit within 6\" at the end of each phase." },
      { name: "Technomancer Variant", description: "Friendly Necron VEHICLE units within 6\" regain D3 lost wounds at the start of your Command Phase instead of 1." },
      { name: "Living Metal", description: "At the start of your Command Phase, this model regains 1 lost wound." },
    ],
    keywords: ["Infantry", "Character", "Cryptek", "Technomancer"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-lokhust-lord",
    name: "Lokhust Lord",
    role: "Character",
    category: "HQ",
    canFly: true,
    stats: { movement: '10"', toughness: 6, save: "3+", wounds: 5, leadership: "3+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 75,
    weapons: [
      { name: "Staff of Light (Ranged)", type: "Assault", range: '18"', attacks: "3", skill: "BS2+", strength: "5", ap: "-2", damage: "1" },
      { name: "Warscythe", type: "Melee", attacks: "4", skill: "WS2+", strength: "7", ap: "-2", damage: "2" },
    ],
    abilities: [
      { name: "Relentless March", description: "Friendly Lokhust Destroyer units within 9\" can Advance and shoot as if they had not Advanced." },
      { name: "Fly", description: "This model can move over models and terrain." },
      { name: "Living Metal", description: "At the start of your Command Phase, this model regains 1 lost wound." },
    ],
    keywords: ["Infantry", "Character", "Fly", "Lokhust", "Overlord"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-royal-warden",
    name: "Royal Warden",
    role: "Character",
    category: "HQ",
    stats: { movement: '6"', toughness: 5, save: "2+", wounds: 4, leadership: "3+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 45,
    weapons: [
      { name: "Relic Gauss Blaster", type: "Assault", range: '30"', attacks: "3", skill: "BS2+", strength: "5", ap: "-2", damage: "2" },
      { name: "Close Combat Weapon", type: "Melee", attacks: "2", skill: "WS3+", strength: "5", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Adaptive Strategy", description: "A friendly unit led by the Royal Warden can either fire Pistols in the Fight phase OR make a 6\" Consolidation move after fighting." },
    ],
    keywords: ["Infantry", "Character", "Necron Royalty"],
    factionKeywords: ["Necrons"],
  },
  // ─── BATTLELINE ───────────────────────────────────────────────────
  {
    id: "nec-warriors-flayer",
    name: "Necron Warriors (Gauss Flayer)",
    role: "Infantry",
    category: "Battleline",
    stats: { movement: '6"', toughness: 4, save: "4+", wounds: 1, leadership: "7+", oc: 2 },
    models: { min: 10, max: 20 },
    points: 130,
    weapons: [
      { name: "Gauss Flayer", type: "Rapid Fire", range: '24"', attacks: "1", skill: "BS3+", strength: "4", ap: "-1", damage: "1" },
      { name: "Close Combat Weapon", type: "Melee", attacks: "1", skill: "WS3+", strength: "4", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Reanimation Protocols", description: "At the end of any phase, roll a D6 for each model destroyed. On a 5+, that model is returned with 1 wound remaining. On a 3+, if a friendly CRYPTEK is within 6\"." },
      { name: "Living Metal", description: "At the start of your Command Phase, this unit regains 1 lost wound (one model heals or is partially restored)." },
    ],
    keywords: ["Infantry", "Core", "Battleline", "Necron Warriors"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-warriors-reaper",
    name: "Necron Warriors (Gauss Reaper)",
    role: "Infantry",
    category: "Battleline",
    stats: { movement: '6"', toughness: 4, save: "4+", wounds: 1, leadership: "7+", oc: 2 },
    models: { min: 10, max: 20 },
    points: 130,
    weapons: [
      { name: "Gauss Reaper", type: "Assault", range: '18"', attacks: "2", skill: "BS3+", strength: "5", ap: "-2", damage: "1" },
      { name: "Close Combat Weapon", type: "Melee", attacks: "1", skill: "WS3+", strength: "4", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Reanimation Protocols", description: "At the end of any phase, roll a D6 for each model destroyed. On a 5+, that model is returned with 1 wound remaining. On a 3+, if a friendly CRYPTEK is within 6\"." },
      { name: "Living Metal", description: "At the start of your Command Phase, this unit regains 1 lost wound." },
    ],
    keywords: ["Infantry", "Core", "Battleline", "Necron Warriors"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-immortals-blaster",
    name: "Immortals (Gauss Blaster)",
    role: "Infantry",
    category: "Battleline",
    stats: { movement: '6"', toughness: 4, save: "3+", wounds: 1, leadership: "7+", oc: 1 },
    models: { min: 5, max: 10 },
    points: 85,
    weapons: [
      { name: "Gauss Blaster", type: "Rapid Fire", range: '24"', attacks: "1", skill: "BS3+", strength: "5", ap: "-2", damage: "2" },
      { name: "Close Combat Weapon", type: "Melee", attacks: "1", skill: "WS3+", strength: "4", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Reanimation Protocols", description: "At the end of any phase, roll a D6 for each model destroyed. On a 5+, that model is returned." },
      { name: "Living Metal", description: "Regains 1 wound per Command Phase." },
    ],
    keywords: ["Infantry", "Core", "Battleline", "Immortals"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-immortals-tesla",
    name: "Immortals (Tesla Carbine)",
    role: "Infantry",
    category: "Battleline",
    stats: { movement: '6"', toughness: 4, save: "3+", wounds: 1, leadership: "7+", oc: 1 },
    models: { min: 5, max: 10 },
    points: 85,
    weapons: [
      { name: "Tesla Carbine", type: "Assault", range: '24"', attacks: "2", skill: "BS3+", strength: "5", ap: "0", damage: "1", keywords: ["Sustained Hits 2"] },
      { name: "Close Combat Weapon", type: "Melee", attacks: "1", skill: "WS3+", strength: "4", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Reanimation Protocols", description: "At the end of any phase, roll a D6 for each model destroyed. On a 5+, that model is returned." },
      { name: "Living Metal", description: "Regains 1 wound per Command Phase." },
    ],
    keywords: ["Infantry", "Core", "Battleline", "Immortals"],
    factionKeywords: ["Necrons"],
  },
  // ─── ELITES ───────────────────────────────────────────────────────
  {
    id: "nec-lychguard-warscythes",
    name: "Lychguard (Warscythes)",
    role: "Infantry",
    category: "Elites",
    stats: { movement: '6"', toughness: 5, save: "3+", wounds: 2, leadership: "6+", oc: 1 },
    models: { min: 5, max: 10 },
    points: 95,
    weapons: [
      { name: "Warscythe", type: "Melee", attacks: "3", skill: "WS3+", strength: "7", ap: "-2", damage: "2" },
    ],
    abilities: [
      { name: "Reanimation Protocols", description: "At the end of any phase, roll a D6 for each destroyed model; on a 5+, it is returned." },
      { name: "Living Metal", description: "Regains 1 wound per Command Phase." },
    ],
    keywords: ["Infantry", "Core", "Lychguard", "Deep Strike"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-lychguard-shields",
    name: "Lychguard (Hyperphase Swords & Dispersion Shields)",
    role: "Infantry",
    category: "Elites",
    stats: { movement: '6"', toughness: 5, save: "3+/4++", wounds: 2, leadership: "6+", oc: 1 },
    models: { min: 5, max: 10 },
    points: 105,
    weapons: [
      { name: "Hyperphase Sword", type: "Melee", attacks: "3", skill: "WS3+", strength: "5", ap: "-2", damage: "1" },
    ],
    abilities: [
      { name: "Dispersion Shield", description: "This unit has a 4++ invulnerable save from Dispersion Shields." },
      { name: "Reanimation Protocols", description: "At the end of any phase, roll a D6 for each destroyed model; on a 5+, it is returned." },
      { name: "Living Metal", description: "Regains 1 wound per Command Phase." },
    ],
    keywords: ["Infantry", "Core", "Lychguard", "Deep Strike"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-deathmarks",
    name: "Deathmarks",
    role: "Infantry",
    category: "Elites",
    canDeepStrike: true,
    stats: { movement: '6"', toughness: 4, save: "3+", wounds: 1, leadership: "7+", oc: 1 },
    models: { min: 5, max: 10 },
    points: 75,
    weapons: [
      { name: "Synaptic Disintegrator", type: "Heavy", range: '36"', attacks: "1", skill: "BS3+", strength: "5", ap: "-2", damage: "2", keywords: ["Precision"] },
    ],
    abilities: [
      { name: "Ethereal Interception", description: "This unit can be placed in Hyperspace instead of deploying normally. At the start of any turn (including turn 1), they can arrive anywhere on the battlefield more than 9\" from enemy models." },
      { name: "Hunter's Mark", description: "When deployed or at the start of your Shooting phase, choose one visible enemy unit. Until end of phase, this unit's attacks get +1 to wound against that unit." },
      { name: "Reanimation Protocols", description: "At the end of any phase, roll D6 for each destroyed model; on 5+, returned." },
    ],
    keywords: ["Infantry", "Core", "Deathmarks", "Deep Strike"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-flayed-ones",
    name: "Flayed Ones",
    role: "Infantry",
    category: "Elites",
    canDeepStrike: true,
    stats: { movement: '6"', toughness: 4, save: "4+", wounds: 2, leadership: "7+", oc: 1 },
    models: { min: 5, max: 20 },
    points: 60,
    weapons: [
      { name: "Flayer Claws", type: "Melee", attacks: "4", skill: "WS3+", strength: "4", ap: "-1", damage: "1" },
    ],
    abilities: [
      { name: "Infiltrators", description: "Before the first battle round, this unit can be set up anywhere on the battlefield more than 9\" from the enemy deployment zone and any enemy models." },
      { name: "Terrifying", description: "Enemy units within 3\" of this unit are -1 to hit in the Fight phase." },
      { name: "Reanimation Protocols", description: "At the end of any phase, roll D6 for each destroyed model; on 5+, returned." },
    ],
    keywords: ["Infantry", "Core", "Infiltrators", "Flayed Ones"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-triarch-praetorians",
    name: "Triarch Praetorians (Rods of Covenant)",
    role: "Infantry",
    category: "Elites",
    canFly: true,
    stats: { movement: '8"', toughness: 5, save: "3+/4++", wounds: 2, leadership: "5+", oc: 1 },
    models: { min: 5, max: 10 },
    points: 100,
    weapons: [
      { name: "Rod of Covenant (Ranged)", type: "Assault", range: '12"', attacks: "2", skill: "BS3+", strength: "6", ap: "-2", damage: "2" },
      { name: "Rod of Covenant (Melee)", type: "Melee", attacks: "2", skill: "WS3+", strength: "6", ap: "-2", damage: "2" },
    ],
    abilities: [
      { name: "Fly", description: "This unit can move over models and terrain." },
      { name: "Eternal Covenant", description: "This unit can Heroically Intervene up to 6\" (instead of 3\") and fights before non-Fights First units." },
      { name: "Reanimation Protocols", description: "At the end of any phase, roll D6 for each destroyed model; on 5+, returned." },
    ],
    keywords: ["Infantry", "Core", "Fly", "Triarch Praetorians"],
    factionKeywords: ["Necrons"],
  },
  // ─── HEAVY SUPPORT ────────────────────────────────────────────────
  {
    id: "nec-doomsday-ark",
    name: "Doomsday Ark",
    role: "Vehicle",
    category: "Heavy Support",
    canFly: true,
    stats: { movement: '8"', toughness: 11, save: "3+", wounds: 12, leadership: "6+", oc: 3 },
    models: { min: 1, max: 1 },
    points: 195,
    weapons: [
      { name: "Doomsday Cannon (Stationary)", type: "Heavy", range: '72"', attacks: "1", skill: "BS3+", strength: "20", ap: "-5", damage: "7" },
      { name: "Doomsday Cannon (Moved)", type: "Heavy", range: '72"', attacks: "1", skill: "BS4+", strength: "14", ap: "-4", damage: "5" },
      { name: "Gauss Flayer Arrays", type: "Heavy", range: '24"', attacks: "5", skill: "BS3+", strength: "4", ap: "-1", damage: "1" },
    ],
    abilities: [
      { name: "Hovering", description: "This model can move over models and terrain as if it had the Fly keyword." },
      { name: "Living Metal", description: "At the start of your Command Phase, this model regains 1 lost wound." },
    ],
    keywords: ["Vehicle", "Core", "Fly", "Hover", "Doomsday Ark"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-annihilation-barge",
    name: "Annihilation Barge",
    role: "Vehicle",
    category: "Heavy Support",
    canFly: true,
    stats: { movement: '12"', toughness: 9, save: "3+", wounds: 8, leadership: "6+", oc: 3 },
    models: { min: 1, max: 1 },
    points: 115,
    weapons: [
      { name: "Tesla Destructor", type: "Heavy", range: '24"', attacks: "6", skill: "BS3+", strength: "7", ap: "-2", damage: "2", keywords: ["Sustained Hits 2"] },
      { name: "Gauss Cannon", type: "Heavy", range: '24"', attacks: "2", skill: "BS3+", strength: "6", ap: "-2", damage: "3" },
    ],
    abilities: [
      { name: "Living Metal", description: "At the start of your Command Phase, this model regains 1 lost wound." },
      { name: "Fly", description: "This model can move over models and terrain." },
    ],
    keywords: ["Vehicle", "Core", "Fly", "Annihilation Barge"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-monolith",
    name: "Monolith",
    role: "Vehicle",
    category: "Lord of War",
    isTitanic: true,
    stats: { movement: '5"', toughness: 12, save: "2+", wounds: 20, leadership: "4+", oc: 8 },
    models: { min: 1, max: 1 },
    points: 400,
    weapons: [
      { name: "Death Ray", type: "Heavy", range: '36"', attacks: "3", skill: "BS3+", strength: "16", ap: "-4", damage: "D3+3" },
      { name: "Gauss Flux Arc ×4", type: "Heavy", range: '24"', attacks: "6", skill: "BS3+", strength: "5", ap: "-2", damage: "1" },
    ],
    abilities: [
      { name: "Titanic", description: "This model is a Titanic unit and cannot have Stratagems used to target it." },
      { name: "Living Metal", description: "At the start of your Command Phase, this model regains D3 lost wounds." },
      { name: "Eternity Gate", description: "Once per turn, in the Movement phase, one friendly Necron INFANTRY unit anywhere on the battlefield can teleport, removing it from the board and placing it within 3\" of this model and more than 9\" from enemy models." },
      { name: "Loom of the Gods", description: "At the start of the enemy Shooting phase, all enemy units within 12\" of this model must take a Battleshock test." },
    ],
    keywords: ["Vehicle", "Titanic", "Monolith"],
    factionKeywords: ["Necrons"],
  },
];

const AWAKENED_DYNASTY: Detachment = {
  name: "Awakened Dynasty",
  rule: {
    name: "Dynastic Protocols",
    description:
      "All Necron units get +1 to Reanimation Protocol rolls. Necron CORE units within 6\" of a friendly OVERLORD gain the Lethal Hits keyword on all unmodified hit rolls of 6.",
  },
  stratagems: [
    {
      name: "Disruption Fields",
      cost: 1,
      phase: "Fight",
      description: "Use at the start of the Fight phase. A friendly Necron CORE unit's melee attacks gain the Sustained Hits 1 keyword until end of phase.",
    },
    {
      name: "Quantum Deflection",
      cost: 1,
      phase: "Any",
      description: "Use when a friendly Necron unit is selected as the target of a ranged attack. Until end of that Shooting phase, that unit has a 5++ invulnerable save against those attacks.",
    },
    {
      name: "Entropic Strike",
      cost: 1,
      phase: "Any",
      description: "Use in the Shooting or Fight phase. A friendly Necron unit's weapons with AP -1 or better gain an additional -1 AP until end of that phase.",
    },
    {
      name: "Emergency Invasion Beam",
      cost: 1,
      phase: "Any",
      description: "Use at the end of any phase. Remove one friendly Necron INFANTRY unit from the battlefield and add it to Strategic Reserves. It may redeploy from reserves next turn using Tactical Reserves rules.",
    },
    {
      name: "Hand of the Phaeron",
      cost: 2,
      phase: "Command",
      description: "Use in the Command Phase. One friendly Necron VEHICLE within 12\" of a friendly OVERLORD automatically passes its Reanimation Protocol roll this turn, restoring it to 1 wound remaining if destroyed.",
    },
    {
      name: "Voltaic Staff",
      cost: 1,
      phase: "Shooting",
      description: "Use at the start of the Shooting phase. A friendly CRYPTEK unit can target enemy units not visible to it with its shooting attacks this phase.",
    },
  ],
  enhancements: [
    {
      name: "Sempiternal Weave",
      points: 20,
      description: "The bearer's Sv characteristic is improved by 1. Additionally, the bearer has a 4+++ Feel No Pain save against mortal wounds.",
      restriction: "Necrons CHARACTER",
    },
    {
      name: "Nanoscarab Casket",
      points: 15,
      description: "The bearer heals 2 wounds from Living Metal instead of 1, and their Reanimation Protocol roll succeeds on a 4+.",
      restriction: "Necrons CHARACTER",
    },
    {
      name: "Voltaic Staff",
      points: 10,
      description: "All of the bearer's shooting weapons gain the Devastating Wounds keyword.",
      restriction: "Necrons CHARACTER",
    },
    {
      name: "The Sovereign Coronal",
      points: 30,
      description: "Aura: Friendly Necron CORE units within 6\" of this model get +1 to their Attacks characteristic in the Fight phase.",
      restriction: "Necrons CHARACTER",
    },
  ],
};

export const NECRONS_FACTION: Faction = {
  id: "necrons",
  name: "Necrons",
  shortName: "Nec",
  description: "Ancient machine-warriors who slumbered in tombs for sixty million years. The Necrons have awoken to reclaim their galaxy, armed with deathless bodies and hyper-advanced technology.",
  accentColor: "#15803d",
  units: NECRON_UNITS,
  detachments: [AWAKENED_DYNASTY],
};
