import type { Unit, Faction, Detachment } from "./types";

export const NECRON_UNITS: Unit[] = [
  // ─── CHARACTERS ───────────────────────────────────────────────────
  {
    id: "nec-silent-king",
    name: "The Silent King",
    role: "Monster",
    category: "Lord of War",
    isEpicHero: true,
    isTitanic: false,
    stats: { movement: '8"', toughness: 12, save: "2+/4++", wounds: 18, leadership: "3+", oc: 5 },
    models: { min: 1, max: 1 },
    points: 440,
    weapons: [
      { name: "Sceptre of Eternal Glory", type: "Melee", attacks: "6", skill: "WS2+", strength: "16", ap: "-4", damage: "D6+2" },
      { name: "Annihilator Beam", type: "Heavy", range: '36"', attacks: "3", skill: "BS2+", strength: "16", ap: "-4", damage: "6" },
    ],
    abilities: [
      { name: "Lord of the Necrons", description: "Friendly Necron units on the board re-roll hit rolls of 1 and wound rolls of 1." },
      { name: "Triarch's Will", description: "At the start of your Command Phase, issue one Triarch's Command to any friendly Necron unit within 18\": either Advance and shoot, or fight twice." },
      { name: "Unstoppable Monolith", description: "Each time an attack is made against this model, that attack only wounds this model on an unmodified wound roll of 4+, regardless of the weapon's Strength." },
      { name: "Living Metal", description: "At the start of your Command Phase, this model regains 1 lost wound." },
    ],
    keywords: ["Monster", "Character", "Epic Hero", "Necron Royalty", "The Silent King"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-imotekh",
    name: "Imotekh the Stormlord",
    role: "Character",
    category: "HQ",
    isEpicHero: true,
    stats: { movement: '6"', toughness: 5, save: "2+/4++", wounds: 6, leadership: "3+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 95,
    weapons: [
      { name: "Staff of the Destroyer", type: "Melee", attacks: "5", skill: "WS2+", strength: "7", ap: "-2", damage: "3" },
      { name: "Gauntlet of Fire", type: "Pistol", range: '12"', attacks: "6", skill: "BS-", strength: "5", ap: "-1", damage: "1", keywords: ["Torrent"] },
    ],
    abilities: [
      { name: "Lord of the Sautekh", description: "Friendly Sautekh Necron CORE units within 6\" re-roll hit rolls of 1." },
      { name: "Hyperlogical Strategy", description: "While Imotekh is on the battlefield, all friendly Necron units get +1 to all hit rolls." },
      { name: "Living Metal", description: "At the start of your Command Phase, this model regains 1 lost wound." },
      { name: "Lord of the Storm", description: "Once per battle round, at the start of the Shooting phase, all enemy units on the battlefield suffer 1 mortal wound on a roll of 6+." },
    ],
    keywords: ["Infantry", "Character", "Epic Hero", "Necron Royalty", "Overlord", "Imotekh"],
    factionKeywords: ["Necrons", "Sautekh"],
  },
  {
    id: "nec-overlord",
    name: "Overlord",
    role: "Character",
    category: "HQ",
    stats: { movement: '6"', toughness: 5, save: "2+", wounds: 5, leadership: "3+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 80,
    weapons: [
      { name: "Tachyon Arrow", type: "Heavy", range: '120"', attacks: "1", skill: "BS2+", strength: "16", ap: "-5", damage: "D6+2", keywords: ["One Shot"] },
      { name: "Staff of Light (Ranged)", type: "Assault", range: '18"', attacks: "3", skill: "BS2+", strength: "5", ap: "-2", damage: "1" },
      { name: "Staff of Light (Melee)", type: "Melee", attacks: "3", skill: "WS2+", strength: "5", ap: "-2", damage: "1" },
      { name: "Voidscythe", type: "Melee", attacks: "3", skill: "WS2+", strength: "10", ap: "-3", damage: "3" },
      { name: "Voidreaper", type: "Melee", attacks: "5", skill: "WS2+", strength: "8", ap: "-4", damage: "2", keywords: ["Devastating Wounds"] },
    ],
    abilities: [
      { name: "My Will Be Done", description: "Re-roll hit rolls of 1 and wound rolls of 1 for one friendly Necron CORE unit within 6\" each Command Phase." },
      { name: "Living Metal", description: "At the start of your Command Phase, this model regains 1 lost wound." },
    ],
    keywords: ["Infantry", "Character", "Necron Royalty", "Overlord"],
    factionKeywords: ["Necrons"],
    wargearOptions: [
      { description: "May replace Staff of Light with a Voidscythe or Voidreaper." },
      { description: "May take a Resurrection Orb (+15pts): once per battle, at the end of any phase, a friendly Necron INFANTRY unit within 6\" immediately triggers Reanimation Protocols." },
    ],
    weaponOptions: [
      {
        replaces: "Tachyon Arrow",
        options: [
          { name: "Voidscythe (Swap)", type: "Melee", attacks: "3", skill: "WS2+", strength: "10", ap: "-3", damage: "3" },
          { name: "Voidreaper", type: "Melee", attacks: "5", skill: "WS2+", strength: "8", ap: "-4", damage: "2", keywords: ["Devastating Wounds"] },
        ],
      },
    ],
  },
  {
    id: "nec-cryptek",
    name: "Cryptek",
    role: "Character",
    category: "HQ",
    stats: { movement: '6"', toughness: 4, save: "3+", wounds: 4, leadership: "3+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 55,
    weapons: [
      { name: "Arkana Conduit", type: "Melee", attacks: "3", skill: "WS3+", strength: "5", ap: "-2", damage: "1" },
    ],
    abilities: [
      { name: "Rites of Reanimation", description: "+1 to Reanimation Protocol rolls for a friendly Necron INFANTRY unit within 6\" at the end of each phase." },
      { name: "Technomancer Variant", description: "Friendly Necron VEHICLE units within 6\" regain D3 lost wounds at the start of your Command Phase instead of 1." },
      { name: "Living Metal", description: "At the start of your Command Phase, this model regains 1 lost wound." },
    ],
    keywords: ["Infantry", "Character", "Cryptek", "Technomancer"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-lokhust-lord",
    name: "Lokhust Lord",
    role: "Character",
    category: "HQ",
    canFly: true,
    stats: { movement: '10"', toughness: 6, save: "3+", wounds: 5, leadership: "3+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 75,
    weapons: [
      { name: "Staff of Light (Ranged)", type: "Assault", range: '18"', attacks: "3", skill: "BS2+", strength: "5", ap: "-2", damage: "1" },
      { name: "Warscythe", type: "Melee", attacks: "4", skill: "WS2+", strength: "7", ap: "-2", damage: "2" },
    ],
    abilities: [
      { name: "Relentless March", description: "Friendly Lokhust Destroyer units within 9\" can Advance and shoot as if they had not Advanced." },
      { name: "Fly", description: "This model can move over models and terrain." },
      { name: "Living Metal", description: "At the start of your Command Phase, this model regains 1 lost wound." },
    ],
    keywords: ["Infantry", "Character", "Fly", "Lokhust", "Overlord"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-royal-warden",
    name: "Royal Warden",
    role: "Character",
    category: "HQ",
    stats: { movement: '6"', toughness: 5, save: "2+", wounds: 4, leadership: "3+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 45,
    weapons: [
      { name: "Relic Gauss Blaster", type: "Assault", range: '30"', attacks: "3", skill: "BS2+", strength: "5", ap: "-2", damage: "2" },
      { name: "Close Combat Weapon", type: "Melee", attacks: "2", skill: "WS3+", strength: "5", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Adaptive Strategy", description: "A friendly unit led by the Royal Warden can either fire Pistols in the Fight phase OR make a 6\" Consolidation move after fighting." },
    ],
    keywords: ["Infantry", "Character", "Necron Royalty"],
    factionKeywords: ["Necrons"],
  },
  // ─── BATTLELINE ───────────────────────────────────────────────────
  {
    id: "nec-warriors-flayer",
    name: "Necron Warriors (Gauss Flayer)",
    role: "Infantry",
    category: "Battleline",
    stats: { movement: '6"', toughness: 4, save: "4+", wounds: 1, leadership: "7+", oc: 2 },
    models: { min: 10, max: 20 },
    points: 130,
    pointsPerModel: 13,
    weapons: [
      { name: "Gauss Flayer", type: "Rapid Fire", range: '24"', attacks: "1", skill: "BS3+", strength: "4", ap: "-1", damage: "1" },
      { name: "Close Combat Weapon", type: "Melee", attacks: "1", skill: "WS3+", strength: "4", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Reanimation Protocols", description: "At the end of any phase, roll a D6 for each model destroyed. On a 5+, that model is returned with 1 wound remaining. On a 3+, if a friendly CRYPTEK is within 6\"." },
      { name: "Living Metal", description: "At the start of your Command Phase, this unit regains 1 lost wound (one model heals or is partially restored)." },
    ],
    keywords: ["Infantry", "Core", "Battleline", "Necron Warriors"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-warriors-reaper",
    name: "Necron Warriors (Gauss Reaper)",
    role: "Infantry",
    category: "Battleline",
    stats: { movement: '6"', toughness: 4, save: "4+", wounds: 1, leadership: "7+", oc: 2 },
    models: { min: 10, max: 20 },
    points: 130,
    pointsPerModel: 13,
    weapons: [
      { name: "Gauss Reaper", type: "Assault", range: '18"', attacks: "2", skill: "BS3+", strength: "5", ap: "-2", damage: "1", keywords: ["Lethal Hits"] },
      { name: "Close Combat Weapon", type: "Melee", attacks: "1", skill: "WS3+", strength: "4", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Reanimation Protocols", description: "At the end of any phase, roll a D6 for each model destroyed. On a 5+, that model is returned with 1 wound remaining. On a 3+, if a friendly CRYPTEK is within 6\"." },
      { name: "Living Metal", description: "At the start of your Command Phase, this unit regains 1 lost wound." },
    ],
    keywords: ["Infantry", "Core", "Battleline", "Necron Warriors"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-immortals-blaster",
    name: "Immortals (Gauss Blaster)",
    role: "Infantry",
    category: "Battleline",
    stats: { movement: '6"', toughness: 4, save: "3+", wounds: 1, leadership: "7+", oc: 1 },
    models: { min: 5, max: 10 },
    points: 85,
    pointsPerModel: 17,
    weapons: [
      { name: "Gauss Blaster", type: "Rapid Fire", range: '24"', attacks: "1", skill: "BS3+", strength: "5", ap: "-2", damage: "2" },
      { name: "Close Combat Weapon", type: "Melee", attacks: "1", skill: "WS3+", strength: "4", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Reanimation Protocols", description: "At the end of any phase, roll a D6 for each model destroyed. On a 5+, that model is returned." },
      { name: "Living Metal", description: "Regains 1 wound per Command Phase." },
    ],
    keywords: ["Infantry", "Core", "Battleline", "Immortals"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-immortals-tesla",
    name: "Immortals (Tesla Carbine)",
    role: "Infantry",
    category: "Battleline",
    stats: { movement: '6"', toughness: 4, save: "3+", wounds: 1, leadership: "7+", oc: 1 },
    models: { min: 5, max: 10 },
    points: 85,
    pointsPerModel: 17,
    weapons: [
      { name: "Tesla Carbine", type: "Assault", range: '24"', attacks: "2", skill: "BS3+", strength: "5", ap: "0", damage: "1", keywords: ["Sustained Hits 2"] },
      { name: "Close Combat Weapon", type: "Melee", attacks: "1", skill: "WS3+", strength: "4", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Reanimation Protocols", description: "At the end of any phase, roll a D6 for each model destroyed. On a 5+, that model is returned." },
      { name: "Living Metal", description: "Regains 1 wound per Command Phase." },
    ],
    keywords: ["Infantry", "Core", "Battleline", "Immortals"],
    factionKeywords: ["Necrons"],
  },
  // ─── ELITES ───────────────────────────────────────────────────────
  {
    id: "nec-lychguard-warscythes",
    name: "Lychguard (Warscythes)",
    role: "Infantry",
    category: "Elites",
    stats: { movement: '6"', toughness: 5, save: "3+", wounds: 2, leadership: "6+", oc: 1 },
    models: { min: 5, max: 10 },
    points: 95,
    weapons: [
      { name: "Warscythe", type: "Melee", attacks: "3", skill: "WS3+", strength: "7", ap: "-2", damage: "2" },
    ],
    abilities: [
      { name: "Reanimation Protocols", description: "At the end of any phase, roll a D6 for each destroyed model; on a 5+, it is returned." },
      { name: "Living Metal", description: "Regains 1 wound per Command Phase." },
    ],
    keywords: ["Infantry", "Core", "Lychguard", "Deep Strike"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-lychguard-shields",
    name: "Lychguard (Hyperphase Swords & Dispersion Shields)",
    role: "Infantry",
    category: "Elites",
    stats: { movement: '6"', toughness: 5, save: "3+/4++", wounds: 2, leadership: "6+", oc: 1 },
    models: { min: 5, max: 10 },
    points: 105,
    weapons: [
      { name: "Hyperphase Sword", type: "Melee", attacks: "3", skill: "WS3+", strength: "5", ap: "-2", damage: "1" },
    ],
    abilities: [
      { name: "Dispersion Shield", description: "This unit has a 4++ invulnerable save from Dispersion Shields." },
      { name: "Reanimation Protocols", description: "At the end of any phase, roll a D6 for each destroyed model; on a 5+, it is returned." },
      { name: "Living Metal", description: "Regains 1 wound per Command Phase." },
    ],
    keywords: ["Infantry", "Core", "Lychguard", "Deep Strike"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-deathmarks",
    name: "Deathmarks",
    role: "Infantry",
    category: "Elites",
    canDeepStrike: true,
    stats: { movement: '6"', toughness: 4, save: "3+", wounds: 1, leadership: "7+", oc: 1 },
    models: { min: 5, max: 10 },
    points: 75,
    weapons: [
      { name: "Synaptic Disintegrator", type: "Heavy", range: '36"', attacks: "1", skill: "BS3+", strength: "5", ap: "-2", damage: "2", keywords: ["Precision"] },
    ],
    abilities: [
      { name: "Ethereal Interception", description: "This unit can be placed in Hyperspace instead of deploying normally. At the start of any turn (including turn 1), they can arrive anywhere on the battlefield more than 9\" from enemy models." },
      { name: "Hunter's Mark", description: "When deployed or at the start of your Shooting phase, choose one visible enemy unit. Until end of phase, this unit's attacks get +1 to wound against that unit." },
      { name: "Reanimation Protocols", description: "At the end of any phase, roll D6 for each destroyed model; on 5+, returned." },
    ],
    keywords: ["Infantry", "Core", "Deathmarks", "Deep Strike"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-flayed-ones",
    name: "Flayed Ones",
    role: "Infantry",
    category: "Elites",
    canDeepStrike: true,
    stats: { movement: '6"', toughness: 4, save: "4+", wounds: 2, leadership: "7+", oc: 1 },
    models: { min: 5, max: 20 },
    points: 60,
    weapons: [
      { name: "Flayer Claws", type: "Melee", attacks: "4", skill: "WS3+", strength: "4", ap: "-1", damage: "1" },
    ],
    abilities: [
      { name: "Infiltrators", description: "Before the first battle round, this unit can be set up anywhere on the battlefield more than 9\" from the enemy deployment zone and any enemy models." },
      { name: "Terrifying", description: "Enemy units within 3\" of this unit are -1 to hit in the Fight phase." },
      { name: "Reanimation Protocols", description: "At the end of any phase, roll D6 for each destroyed model; on 5+, returned." },
    ],
    keywords: ["Infantry", "Core", "Infiltrators", "Flayed Ones"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-triarch-praetorians",
    name: "Triarch Praetorians (Rods of Covenant)",
    role: "Infantry",
    category: "Elites",
    canFly: true,
    stats: { movement: '8"', toughness: 5, save: "3+/4++", wounds: 2, leadership: "5+", oc: 1 },
    models: { min: 5, max: 10 },
    points: 100,
    weapons: [
      { name: "Rod of Covenant (Ranged)", type: "Assault", range: '12"', attacks: "2", skill: "BS3+", strength: "6", ap: "-2", damage: "2" },
      { name: "Rod of Covenant (Melee)", type: "Melee", attacks: "2", skill: "WS3+", strength: "6", ap: "-2", damage: "2" },
    ],
    abilities: [
      { name: "Fly", description: "This unit can move over models and terrain." },
      { name: "Eternal Covenant", description: "This unit can Heroically Intervene up to 6\" (instead of 3\") and fights before non-Fights First units." },
      { name: "Reanimation Protocols", description: "At the end of any phase, roll D6 for each destroyed model; on 5+, returned." },
    ],
    keywords: ["Infantry", "Core", "Fly", "Triarch Praetorians"],
    factionKeywords: ["Necrons"],
  },
  // ─── CHARACTERS (continued) ───────────────────────────────────────
  {
    id: "nec-chronomancer",
    name: "Chronomancer",
    role: "Character",
    category: "HQ",
    stats: { movement: '6"', toughness: 5, save: "3+", wounds: 4, leadership: "3+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 70,
    weapons: [
      { name: "Aeonstave (Ranged)", type: "Assault", range: '18"', attacks: "1", skill: "BS2+", strength: "8", ap: "-2", damage: "3" },
      { name: "Aeonstave (Melee)", type: "Melee", attacks: "3", skill: "WS3+", strength: "6", ap: "-2", damage: "2" },
    ],
    abilities: [
      { name: "Chronometron", description: "Once per battle round, when a friendly Necron unit within 6\" fails a Reanimation Protocol roll, re-roll it." },
      { name: "Living Metal", description: "At the start of your Command Phase, this model regains 1 lost wound." },
    ],
    keywords: ["Infantry", "Character", "Cryptek", "Chronomancer"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-plasmancer",
    name: "Plasmancer",
    role: "Character",
    category: "HQ",
    stats: { movement: '6"', toughness: 5, save: "3+/5++", wounds: 4, leadership: "3+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 70,
    weapons: [
      { name: "Plasmic Lance (Ranged)", type: "Assault", range: '18"', attacks: "3", skill: "BS2+", strength: "9", ap: "-3", damage: "D3", keywords: ["Hazardous"] },
      { name: "Plasmic Lance (Melee)", type: "Melee", attacks: "3", skill: "WS3+", strength: "6", ap: "-2", damage: "1" },
    ],
    abilities: [
      { name: "Crackling Aura", description: "Each time an enemy unit ends a Normal or Advance move within 6\" of this model, that unit suffers D3 mortal wounds." },
      { name: "Living Metal", description: "At the start of your Command Phase, this model regains 1 lost wound." },
    ],
    keywords: ["Infantry", "Character", "Cryptek", "Plasmancer"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-psychomancer",
    name: "Psychomancer",
    role: "Character",
    category: "HQ",
    stats: { movement: '6"', toughness: 5, save: "3+", wounds: 4, leadership: "3+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 65,
    weapons: [
      { name: "Abyssal Lance", type: "Assault", range: '18"', attacks: "3", skill: "BS2+", strength: "6", ap: "-2", damage: "2", keywords: ["Psychic"] },
      { name: "Close Combat Weapon", type: "Melee", attacks: "3", skill: "WS3+", strength: "5", ap: "-1", damage: "1" },
    ],
    abilities: [
      { name: "Atavindicator", description: "At the start of your Command Phase, choose one enemy unit within 12\" — until the start of your next Command Phase, that unit is -1 to its Leadership." },
      { name: "Living Metal", description: "At the start of your Command Phase, this model regains 1 lost wound." },
    ],
    keywords: ["Infantry", "Character", "Cryptek", "Psychomancer"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-technomancer",
    name: "Technomancer",
    role: "Character",
    category: "HQ",
    stats: { movement: '6"', toughness: 5, save: "3+", wounds: 4, leadership: "3+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 65,
    weapons: [
      { name: "Canoptek Cloak Blades", type: "Melee", attacks: "4", skill: "WS3+", strength: "5", ap: "-1", damage: "1" },
      { name: "Staff of Light (Ranged)", type: "Assault", range: '18"', attacks: "3", skill: "BS2+", strength: "5", ap: "-2", damage: "1" },
    ],
    abilities: [
      { name: "Canoptek Cloak", description: "This model can FLY and has a 5++ invulnerable save from the Canoptek cloak's force field." },
      { name: "Rites of Reanimation", description: "+1 to Reanimation Protocol rolls for a friendly Necron INFANTRY unit within 6\" at the end of each phase." },
      { name: "Living Metal", description: "At the start of your Command Phase, this model regains 1 lost wound." },
    ],
    keywords: ["Infantry", "Character", "Cryptek", "Technomancer", "Fly"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-skorpekh-lord",
    name: "Skorpekh Lord",
    role: "Character",
    category: "HQ",
    stats: { movement: '8"', toughness: 6, save: "3+", wounds: 6, leadership: "3+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 90,
    weapons: [
      { name: "Flensing Claw", type: "Melee", attacks: "5", skill: "WS2+", strength: "7", ap: "-2", damage: "2" },
      { name: "Hyperphase Harvester", type: "Melee", attacks: "3", skill: "WS2+", strength: "10", ap: "-3", damage: "3" },
    ],
    abilities: [
      { name: "Hardwired for Destruction", description: "Re-roll hit rolls and wound rolls of 1 for this model's melee attacks." },
      { name: "Living Metal", description: "At the start of your Command Phase, this model regains 1 lost wound." },
    ],
    keywords: ["Infantry", "Character", "Skorpekh", "Destroyer Cult"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-hexmark-destroyer",
    name: "Hexmark Destroyer",
    role: "Character",
    category: "HQ",
    canFly: true,
    canDeepStrike: true,
    stats: { movement: '10"', toughness: 6, save: "3+", wounds: 4, leadership: "3+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 75,
    weapons: [
      { name: "Enmitic Disintegrator Pistols ×6", type: "Pistol", range: '12"', attacks: "6", skill: "BS2+", strength: "5", ap: "-2", damage: "1", keywords: ["Precision"] },
      { name: "Close Combat Weapon", type: "Melee", attacks: "3", skill: "WS3+", strength: "5", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Interlocked Targeting", description: "At the start of any phase, if this model is within 1\" of any enemy unit, it may shoot its pistols even while in engagement range." },
      { name: "Fly", description: "This model can move over models and terrain." },
      { name: "Deep Strike", description: "This unit can be placed in Reserve and set up anywhere more than 9\" from enemy models." },
      { name: "Living Metal", description: "At the start of your Command Phase, this model regains 1 lost wound." },
    ],
    keywords: ["Infantry", "Character", "Fly", "Deep Strike", "Lokhust", "Destroyer Cult"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-catacomb-command-barge",
    name: "Catacomb Command Barge",
    role: "Vehicle",
    category: "HQ",
    canFly: true,
    stats: { movement: '12"', toughness: 10, save: "3+", wounds: 11, leadership: "3+", oc: 3 },
    models: { min: 1, max: 1 },
    points: 130,
    weapons: [
      { name: "Tesla Cannon", type: "Heavy", range: '24"', attacks: "4", skill: "BS2+", strength: "7", ap: "-2", damage: "2", keywords: ["Sustained Hits 2"] },
      { name: "Gauss Cannon", type: "Heavy", range: '24"', attacks: "2", skill: "BS2+", strength: "6", ap: "-2", damage: "3" },
      { name: "Warscythe", type: "Melee", attacks: "4", skill: "WS2+", strength: "7", ap: "-2", damage: "2" },
    ],
    abilities: [
      { name: "Fly", description: "This model can move over models and terrain." },
      { name: "My Will Be Done", description: "Re-roll hit rolls of 1 and wound rolls of 1 for one friendly Necron CORE unit within 6\" each Command Phase." },
      { name: "Living Metal", description: "At the start of your Command Phase, this model regains 1 lost wound." },
    ],
    keywords: ["Vehicle", "Character", "Fly", "Necron Royalty", "Overlord"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-illuminor-szeras",
    name: "Illuminor Szeras",
    role: "Character",
    category: "HQ",
    isEpicHero: true,
    stats: { movement: '6"', toughness: 5, save: "3+/4++", wounds: 6, leadership: "3+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 100,
    weapons: [
      { name: "Eldritch Lance", type: "Heavy", range: '36"', attacks: "2", skill: "BS2+", strength: "10", ap: "-3", damage: "D3+3" },
      { name: "Mechanical Limbs", type: "Melee", attacks: "4", skill: "WS2+", strength: "6", ap: "-2", damage: "2" },
    ],
    abilities: [
      { name: "Arcane Construct", description: "Once per battle round at the start of your Command Phase, pick one friendly Necron INFANTRY unit within 6\" — until the start of your next Command Phase, add 1 to that unit's save rolls." },
      { name: "Living Metal", description: "At the start of your Command Phase, this model regains 1 lost wound." },
    ],
    keywords: ["Infantry", "Character", "Epic Hero", "Cryptek", "Szeras"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-trazyn",
    name: "Trazyn the Infinite",
    role: "Character",
    category: "HQ",
    isEpicHero: true,
    stats: { movement: '6"', toughness: 5, save: "3+", wounds: 5, leadership: "3+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 80,
    weapons: [
      { name: "Empathic Obliterator", type: "Melee", attacks: "5", skill: "WS2+", strength: "6", ap: "-2", damage: "2", keywords: ["Devastating Wounds"] },
    ],
    abilities: [
      { name: "Prismatic Gallery", description: "Once per battle, when a CHARACTER model is destroyed within 6\" of this model, add 1 to this model's Attacks for the rest of the game." },
      { name: "Surrogate Hosts", description: "Once per battle, if this model is destroyed, roll a D6; on a 4+ set it back up with D3 wounds instead of removing it." },
      { name: "Living Metal", description: "At the start of your Command Phase, this model regains 1 lost wound." },
    ],
    keywords: ["Infantry", "Character", "Epic Hero", "Necron Royalty", "Overlord", "Trazyn"],
    factionKeywords: ["Necrons", "Nihilakh"],
  },
  {
    id: "nec-zahndrekh",
    name: "Nemesor Zahndrekh",
    role: "Character",
    category: "HQ",
    isEpicHero: true,
    stats: { movement: '6"', toughness: 6, save: "2+", wounds: 5, leadership: "3+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 85,
    weapons: [
      { name: "Warscythe", type: "Melee", attacks: "4", skill: "WS2+", strength: "7", ap: "-2", damage: "2" },
      { name: "Voidblade", type: "Melee", attacks: "3", skill: "WS2+", strength: "6", ap: "-4", damage: "1" },
    ],
    abilities: [
      { name: "Adaptive Strategy", description: "Once per battle round, at the start of any phase, pick one friendly Necron CORE unit within 6\" — until the end of the phase, that unit re-rolls all hit rolls of 1." },
      { name: "Living Metal", description: "At the start of your Command Phase, this model regains 1 lost wound." },
    ],
    keywords: ["Infantry", "Character", "Epic Hero", "Necron Royalty", "Overlord", "Zahndrekh"],
    factionKeywords: ["Necrons", "Sautekh"],
  },
  {
    id: "nec-obyron",
    name: "Vargard Obyron",
    role: "Character",
    category: "Elites",
    isEpicHero: true,
    stats: { movement: '6"', toughness: 6, save: "3+", wounds: 4, leadership: "3+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 80,
    weapons: [
      { name: "Ghostwalk Blade", type: "Melee", attacks: "5", skill: "WS2+", strength: "7", ap: "-3", damage: "2" },
    ],
    abilities: [
      { name: "Cleaving Strikes", description: "Each time this model makes an attack with the Ghostwalk Blade, an unmodified hit roll of 6 scores 1 additional hit." },
      { name: "The Vargard's Will", description: "While this model is within 3\" of Nemesor Zahndrekh, both models gain +1 Attack." },
      { name: "Living Metal", description: "At the start of your Command Phase, this model regains 1 lost wound." },
    ],
    keywords: ["Infantry", "Character", "Epic Hero", "Lychguard", "Obyron"],
    factionKeywords: ["Necrons", "Sautekh"],
  },
  {
    id: "nec-anrakyr",
    name: "Anrakyr the Traveller",
    role: "Character",
    category: "HQ",
    isEpicHero: true,
    canFly: true,
    stats: { movement: '8"', toughness: 6, save: "3+", wounds: 6, leadership: "3+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 90,
    weapons: [
      { name: "Tachyon Arrow", type: "Heavy", range: '120"', attacks: "1", skill: "BS2+", strength: "16", ap: "-5", damage: "D6+2", keywords: ["One Shot"] },
      { name: "Warscythe", type: "Melee", attacks: "4", skill: "WS2+", strength: "7", ap: "-2", damage: "2" },
    ],
    abilities: [
      { name: "Pyrrhian Eternals", description: "Once per battle round, in the Shooting phase, pick one friendly Necron VEHICLE within 12\" — that unit can shoot as if it were your Shooting phase (bonus shooting)." },
      { name: "Fly", description: "This model can move over models and terrain." },
      { name: "Living Metal", description: "At the start of your Command Phase, this model regains 1 lost wound." },
    ],
    keywords: ["Infantry", "Character", "Epic Hero", "Fly", "Necron Royalty", "Overlord", "Anrakyr"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-orikan",
    name: "Orikan the Diviner",
    role: "Character",
    category: "HQ",
    isEpicHero: true,
    stats: { movement: '6"', toughness: 5, save: "3+/4++", wounds: 5, leadership: "3+", oc: 1 },
    models: { min: 1, max: 1 },
    points: 95,
    weapons: [
      { name: "The Staff of Tomorrow", type: "Melee", attacks: "4", skill: "WS2+", strength: "6", ap: "-2", damage: "2" },
    ],
    abilities: [
      { name: "Temporal Snare", description: "Once per battle round, at the start of the enemy Movement phase, choose one enemy unit visible to this model — until end of phase, that unit moves as if its Move characteristic were halved (round up)." },
      { name: "Empyric Reversion", description: "At the end of any phase, if this model has taken any wounds since last Command Phase, roll D6; on a 5+ restore 1 lost wound." },
      { name: "Living Metal", description: "At the start of your Command Phase, this model regains 1 lost wound." },
    ],
    keywords: ["Infantry", "Character", "Epic Hero", "Cryptek", "Orikan"],
    factionKeywords: ["Necrons"],
  },
  // ─── ELITES (additional) ──────────────────────────────────────────
  {
    id: "nec-cryptothralls",
    name: "Cryptothralls",
    role: "Infantry",
    category: "Elites",
    stats: { movement: '6"', toughness: 5, save: "4+", wounds: 2, leadership: "7+", oc: 1 },
    models: { min: 2, max: 2 },
    points: 40,
    weapons: [
      { name: "Scouring Eye", type: "Assault", range: '12"', attacks: "2", skill: "BS3+", strength: "4", ap: "-1", damage: "1" },
      { name: "Scything Tendrils", type: "Melee", attacks: "3", skill: "WS4+", strength: "5", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Bodyguard", description: "While this unit is within 3\" of a friendly CRYPTEK, each time that CRYPTEK model is selected as the target of an attack, you can roll a D6 — on a 2+ redirect the attack to this unit instead." },
      { name: "Reanimation Protocols", description: "At the end of any phase, roll D6 for each destroyed model; on a 5+, returned." },
    ],
    keywords: ["Infantry", "Cryptothralls"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-ophydian-destroyers",
    name: "Ophydian Destroyers",
    role: "Infantry",
    category: "Elites",
    canFly: true,
    canDeepStrike: true,
    stats: { movement: '8"', toughness: 5, save: "3+", wounds: 3, leadership: "6+", oc: 1 },
    models: { min: 3, max: 6 },
    points: 90,
    weapons: [
      { name: "Ophydian Claws", type: "Melee", attacks: "4", skill: "WS3+", strength: "7", ap: "-2", damage: "2" },
      { name: "Enmitic Exterminator", type: "Assault", range: '18"', attacks: "2", skill: "BS3+", strength: "5", ap: "-2", damage: "1", keywords: ["Rapid Fire 1"] },
    ],
    abilities: [
      { name: "Burrowing", description: "At the start of your Movement phase, this unit can go underground and enter Strategic Reserves (if not already there). When it surfaces, place it anywhere on the battlefield more than 9\" from any enemy models." },
      { name: "Reanimation Protocols", description: "At the end of any phase, roll D6 for each destroyed model; on a 5+, returned." },
    ],
    keywords: ["Infantry", "Core", "Fly", "Deep Strike", "Destroyer Cult", "Ophydian Destroyers"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-triarch-stalker",
    name: "Triarch Stalker",
    role: "Vehicle",
    category: "Elites",
    stats: { movement: '8"', toughness: 10, save: "3+", wounds: 10, leadership: "6+", oc: 3 },
    models: { min: 1, max: 1 },
    points: 120,
    weapons: [
      { name: "Heat Ray (Focused)", type: "Heavy", range: '12"', attacks: "3", skill: "BS3+", strength: "9", ap: "-4", damage: "D6" },
      { name: "Heat Ray (Dispersed)", type: "Heavy", range: '12"', attacks: "D6+2", skill: "BS3+", strength: "5", ap: "-1", damage: "1", keywords: ["Torrent"] },
      { name: "Massive Forelimbs", type: "Melee", attacks: "4", skill: "WS3+", strength: "10", ap: "-3", damage: "3" },
    ],
    abilities: [
      { name: "Targeting Relay", description: "Each time this model is targeted by a Shooting phase attack from a friendly Necron CORE unit, that unit's attack gains +1 to hit against targets visible to this model." },
      { name: "Living Metal", description: "At the start of your Command Phase, this model regains 1 lost wound." },
    ],
    keywords: ["Vehicle", "Walker", "Triarch Stalker"],
    factionKeywords: ["Necrons"],
  },
  // ─── FAST ATTACK ──────────────────────────────────────────────────
  {
    id: "nec-canoptek-wraiths",
    name: "Canoptek Wraiths",
    role: "Beast",
    category: "Fast Attack",
    canFly: true,
    stats: { movement: '12"', toughness: 5, save: "4+/4++", wounds: 3, leadership: "7+", oc: 1 },
    models: { min: 3, max: 6 },
    points: 105,
    weapons: [
      { name: "Vicious Claws", type: "Melee", attacks: "4", skill: "WS3+", strength: "6", ap: "-2", damage: "2" },
      { name: "Transdimensional Beamer", type: "Assault", range: '12"', attacks: "1", skill: "BS3+", strength: "4", ap: "-3", damage: "1" },
    ],
    abilities: [
      { name: "Wraith Form", description: "This unit has a 4++ invulnerable save and can move through terrain without penalty." },
      { name: "Fly", description: "This unit can move over models and terrain." },
    ],
    keywords: ["Beast", "Core", "Fly", "Canoptek", "Canoptek Wraiths"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-lokhust-destroyers",
    name: "Lokhust Destroyers",
    role: "Infantry",
    category: "Fast Attack",
    canFly: true,
    stats: { movement: '10"', toughness: 6, save: "3+", wounds: 3, leadership: "7+", oc: 1 },
    models: { min: 3, max: 6 },
    points: 90,
    weapons: [
      { name: "Gauss Cannon", type: "Heavy", range: '24"', attacks: "2", skill: "BS3+", strength: "6", ap: "-2", damage: "3" },
      { name: "Close Combat Weapon", type: "Melee", attacks: "1", skill: "WS4+", strength: "5", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Fly", description: "This unit can move over models and terrain." },
      { name: "Reanimation Protocols", description: "At the end of any phase, roll D6 for each destroyed model; on a 5+, returned." },
    ],
    keywords: ["Infantry", "Core", "Fly", "Destroyer Cult", "Lokhust Destroyers"],
    factionKeywords: ["Necrons"],
    wargearOptions: [
      { description: "Any number of models may replace Gauss Cannon with Enmitic Exterminator (Assault 2, S5, AP-2, D1, Rapid Fire 1)." },
    ],
  },
  {
    id: "nec-tomb-blades",
    name: "Tomb Blades",
    role: "Mounted",
    category: "Fast Attack",
    canFly: true,
    stats: { movement: '14"', toughness: 5, save: "3+/4++", wounds: 2, leadership: "7+", oc: 1 },
    models: { min: 3, max: 6 },
    points: 75,
    weapons: [
      { name: "Twin Gauss Blaster", type: "Rapid Fire", range: '24"', attacks: "2", skill: "BS3+", strength: "5", ap: "-2", damage: "2", keywords: ["Twin-linked"] },
      { name: "Close Combat Weapon", type: "Melee", attacks: "1", skill: "WS4+", strength: "4", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Fly", description: "This unit can move over models and terrain." },
      { name: "Evasion Engrams", description: "Enemies targeting this unit from more than 12\" away suffer -1 to their hit rolls." },
      { name: "Reanimation Protocols", description: "At the end of any phase, roll D6 for each destroyed model; on a 5+, returned." },
    ],
    keywords: ["Mounted", "Core", "Fly", "Tomb Blades"],
    factionKeywords: ["Necrons"],
  },
  // ─── HEAVY SUPPORT (additional) ───────────────────────────────────
  {
    id: "nec-lokhust-heavy-destroyers",
    name: "Lokhust Heavy Destroyers",
    role: "Infantry",
    category: "Heavy Support",
    canFly: true,
    stats: { movement: '10"', toughness: 7, save: "3+", wounds: 4, leadership: "7+", oc: 1 },
    models: { min: 1, max: 3 },
    points: 60,
    weapons: [
      { name: "Enmitic Annihilator", type: "Heavy", range: '36"', attacks: "1", skill: "BS3+", strength: "12", ap: "-3", damage: "D6+2", keywords: ["Blast"] },
      { name: "Close Combat Weapon", type: "Melee", attacks: "1", skill: "WS4+", strength: "6", ap: "0", damage: "1" },
    ],
    abilities: [
      { name: "Fly", description: "This unit can move over models and terrain." },
      { name: "Reanimation Protocols", description: "At the end of any phase, roll D6 for each destroyed model; on a 5+, returned." },
    ],
    keywords: ["Infantry", "Core", "Fly", "Destroyer Cult", "Lokhust Heavy Destroyers"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-canoptek-doomstalker",
    name: "Canoptek Doomstalker",
    role: "Vehicle",
    category: "Heavy Support",
    stats: { movement: '8"', toughness: 11, save: "3+", wounds: 10, leadership: "7+", oc: 3 },
    models: { min: 1, max: 1 },
    points: 160,
    weapons: [
      { name: "Doomsday Blaster (Stationary)", type: "Heavy", range: '48"', attacks: "1", skill: "BS3+", strength: "14", ap: "-4", damage: "D6+2" },
      { name: "Doomsday Blaster (Moved)", type: "Heavy", range: '48"', attacks: "1", skill: "BS4+", strength: "10", ap: "-3", damage: "D3+1" },
      { name: "Twin Gauss Flayer", type: "Rapid Fire", range: '24"', attacks: "2", skill: "BS3+", strength: "4", ap: "-1", damage: "1", keywords: ["Twin-linked"] },
    ],
    abilities: [
      { name: "Disruption Fields", description: "When this model charges or is charged, add 1 to Damage for each of its attacks this Fight phase." },
      { name: "Living Metal", description: "At the start of your Command Phase, this model regains 1 lost wound." },
    ],
    keywords: ["Vehicle", "Canoptek", "Canoptek Doomstalker"],
    factionKeywords: ["Necrons"],
  },
  // ─── OTHER ────────────────────────────────────────────────────────
  {
    id: "nec-canoptek-spyder",
    name: "Canoptek Spyder",
    role: "Monster",
    category: "Elites",
    stats: { movement: '8"', toughness: 9, save: "3+", wounds: 7, leadership: "7+", oc: 2 },
    models: { min: 1, max: 3 },
    points: 75,
    weapons: [
      { name: "Automaton Claws", type: "Melee", attacks: "4", skill: "WS4+", strength: "8", ap: "-2", damage: "2" },
      { name: "Particle Beamer", type: "Heavy", range: '18"', attacks: "D3", skill: "BS4+", strength: "6", ap: "0", damage: "1", keywords: ["Blast"] },
    ],
    abilities: [
      { name: "Repair Subroutines", description: "At the start of your Command Phase, this model repairs one friendly Necron VEHICLE within 3\", restoring D3 lost wounds." },
      { name: "Fabricator Claw Array", description: "Friendly Canoptek units within 6\" of this model add +1 to their Reanimation Protocol rolls." },
      { name: "Living Metal", description: "At the start of your Command Phase, this model regains 1 lost wound." },
    ],
    keywords: ["Monster", "Canoptek", "Canoptek Spyder"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-canoptek-reanimator",
    name: "Canoptek Reanimator",
    role: "Vehicle",
    category: "Elites",
    stats: { movement: '8"', toughness: 9, save: "3+", wounds: 8, leadership: "7+", oc: 2 },
    models: { min: 1, max: 1 },
    points: 80,
    weapons: [
      { name: "Atomiser Beam", type: "Heavy", range: '18"', attacks: "D6", skill: "BS3+", strength: "6", ap: "-2", damage: "1", keywords: ["Torrent"] },
      { name: "Reanimation Claws", type: "Melee", attacks: "4", skill: "WS4+", strength: "8", ap: "-1", damage: "2" },
    ],
    abilities: [
      { name: "Reanimation Protocols Enhancement", description: "Friendly Necron INFANTRY units within 6\" of this model may re-roll their Reanimation Protocol dice results of 1." },
      { name: "Living Metal", description: "At the start of your Command Phase, this model regains 1 lost wound." },
    ],
    keywords: ["Vehicle", "Canoptek", "Canoptek Reanimator"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-doom-scythe",
    name: "Doom Scythe",
    role: "Vehicle",
    category: "Fast Attack",
    canFly: true,
    stats: { movement: '20"', toughness: 9, save: "3+", wounds: 9, leadership: "7+", oc: 0 },
    models: { min: 1, max: 1 },
    points: 155,
    weapons: [
      { name: "Death Ray", type: "Heavy", range: '36"', attacks: "3", skill: "BS3+", strength: "16", ap: "-4", damage: "D3+3", keywords: ["Devastating Wounds"] },
      { name: "Twin Heavy Gauss Cannon", type: "Heavy", range: '24"', attacks: "4", skill: "BS3+", strength: "9", ap: "-4", damage: "D3+3", keywords: ["Twin-linked"] },
    ],
    abilities: [
      { name: "Aircraft", description: "This model is an Aircraft. It must move at least 20\" every Movement phase and cannot be charged unless it hovers." },
      { name: "Hover Jets", description: "When this model uses its Hover Jets, it has a Move of 20\" and loses the Aircraft keyword until end of turn." },
      { name: "Living Metal", description: "At the start of your Command Phase, this model regains 1 lost wound." },
    ],
    keywords: ["Vehicle", "Aircraft", "Fly", "Doom Scythe"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-ctan-nightbringer",
    name: "C'tan Shard of the Nightbringer",
    role: "Monster",
    category: "Lord of War",
    stats: { movement: '8"', toughness: 12, save: "2+/4++", wounds: 20, leadership: "4+", oc: 5 },
    models: { min: 1, max: 1 },
    points: 370,
    weapons: [
      { name: "Gaze of Death", type: "Heavy", range: '18"', attacks: "D3+3", skill: "BS2+", strength: "12", ap: "-3", damage: "3", keywords: ["Devastating Wounds"] },
      { name: "Scythe of the Nightbringer", type: "Melee", attacks: "6", skill: "WS2+", strength: "14", ap: "-4", damage: "D6+2", keywords: ["Devastating Wounds"] },
    ],
    abilities: [
      { name: "Necrodermis", description: "This model has a 4++ invulnerable save. Additionally, this model cannot lose more than 6 wounds in any single phase." },
      { name: "Lord of Terror", description: "Enemy units within 12\" must subtract 1 from their Leadership characteristic." },
      { name: "Star God", description: "This model cannot be affected by psychic powers and is immune to mortal wounds caused by psychic powers." },
    ],
    keywords: ["Monster", "C'tan Shard", "Nightbringer"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-ctan-deceiver",
    name: "C'tan Shard of the Deceiver",
    role: "Monster",
    category: "Lord of War",
    stats: { movement: '8"', toughness: 12, save: "2+/4++", wounds: 20, leadership: "4+", oc: 5 },
    models: { min: 1, max: 1 },
    points: 300,
    weapons: [
      { name: "Grand Illusion", type: "Heavy", range: '24"', attacks: "6", skill: "BS2+", strength: "8", ap: "-2", damage: "2", keywords: ["Psychic"] },
      { name: "Blades of Trickery", type: "Melee", attacks: "8", skill: "WS2+", strength: "10", ap: "-3", damage: "3" },
    ],
    abilities: [
      { name: "Necrodermis", description: "This model has a 4++ invulnerable save. Cannot lose more than 6 wounds in any single phase." },
      { name: "Grand Illusion", description: "Once per battle, at the end of your opponent's Deployment step, you may redeploy up to 3 friendly Necron units." },
      { name: "Star God", description: "This model cannot be affected by psychic powers and is immune to mortal wounds from psychic sources." },
    ],
    keywords: ["Monster", "C'tan Shard", "Deceiver"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-ctan-void-dragon",
    name: "C'tan Shard of the Void Dragon",
    role: "Monster",
    category: "Lord of War",
    stats: { movement: '8"', toughness: 12, save: "2+/4++", wounds: 20, leadership: "4+", oc: 5 },
    models: { min: 1, max: 1 },
    points: 310,
    weapons: [
      { name: "Voltaic Storm", type: "Heavy", range: '24"', attacks: "12", skill: "BS2+", strength: "5", ap: "-1", damage: "1", keywords: ["Sustained Hits 1"] },
      { name: "Crackling Tendrils", type: "Melee", attacks: "8", skill: "WS2+", strength: "12", ap: "-3", damage: "D3+3" },
    ],
    abilities: [
      { name: "Necrodermis", description: "This model has a 4++ invulnerable save. Cannot lose more than 6 wounds in any single phase." },
      { name: "Machine God", description: "Once per battle round, at the end of the Fight phase, pick one enemy VEHICLE within 6\" — it suffers D6 mortal wounds." },
      { name: "Star God", description: "This model cannot be affected by psychic powers and is immune to mortal wounds from psychic sources." },
    ],
    keywords: ["Monster", "C'tan Shard", "Void Dragon"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-seraptek",
    name: "Seraptek Heavy Construct",
    role: "Vehicle",
    category: "Lord of War",
    isTitanic: true,
    stats: { movement: '8"', toughness: 14, save: "2+", wounds: 35, leadership: "4+", oc: 8 },
    models: { min: 1, max: 1 },
    points: 520,
    weapons: [
      { name: "Synaptic Obliterators ×2", type: "Heavy", range: '36"', attacks: "6", skill: "BS3+", strength: "12", ap: "-3", damage: "D3+3" },
      { name: "Enmitic Annihilator ×2", type: "Heavy", range: '36"', attacks: "2", skill: "BS3+", strength: "14", ap: "-4", damage: "D6+2" },
      { name: "Massive Forelimbs", type: "Melee", attacks: "10", skill: "WS3+", strength: "16", ap: "-4", damage: "D6+4" },
    ],
    abilities: [
      { name: "Titanic", description: "This model is a Titanic unit. It cannot benefit from cover and Stratagems cannot target it." },
      { name: "Living Metal", description: "At the start of your Command Phase, this model regains D3 lost wounds." },
      { name: "Macro-extinction Targeting", description: "Ranged attacks from this model have the Devastating Wounds keyword against MONSTER and VEHICLE targets." },
    ],
    keywords: ["Vehicle", "Titanic", "Seraptek Heavy Construct"],
    factionKeywords: ["Necrons"],
  },
  // ─── HEAVY SUPPORT ────────────────────────────────────────────────
  {
    id: "nec-doomsday-ark",
    name: "Doomsday Ark",
    role: "Vehicle",
    category: "Heavy Support",
    canFly: true,
    stats: { movement: '8"', toughness: 11, save: "3+", wounds: 12, leadership: "6+", oc: 3 },
    models: { min: 1, max: 1 },
    points: 195,
    weapons: [
      { name: "Doomsday Cannon (Stationary)", type: "Heavy", range: '72"', attacks: "1", skill: "BS3+", strength: "20", ap: "-5", damage: "7" },
      { name: "Doomsday Cannon (Moved)", type: "Heavy", range: '72"', attacks: "1", skill: "BS4+", strength: "14", ap: "-4", damage: "5" },
      { name: "Gauss Flayer Arrays", type: "Heavy", range: '24"', attacks: "5", skill: "BS3+", strength: "4", ap: "-1", damage: "1" },
    ],
    abilities: [
      { name: "Hovering", description: "This model can move over models and terrain as if it had the Fly keyword." },
      { name: "Living Metal", description: "At the start of your Command Phase, this model regains 1 lost wound." },
    ],
    keywords: ["Vehicle", "Core", "Fly", "Hover", "Doomsday Ark"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-annihilation-barge",
    name: "Annihilation Barge",
    role: "Vehicle",
    category: "Heavy Support",
    canFly: true,
    stats: { movement: '12"', toughness: 9, save: "3+", wounds: 8, leadership: "6+", oc: 3 },
    models: { min: 1, max: 1 },
    points: 115,
    weapons: [
      { name: "Tesla Destructor", type: "Heavy", range: '24"', attacks: "6", skill: "BS3+", strength: "7", ap: "-2", damage: "2", keywords: ["Sustained Hits 2"] },
      { name: "Gauss Cannon", type: "Heavy", range: '24"', attacks: "2", skill: "BS3+", strength: "6", ap: "-2", damage: "3" },
    ],
    abilities: [
      { name: "Living Metal", description: "At the start of your Command Phase, this model regains 1 lost wound." },
      { name: "Fly", description: "This model can move over models and terrain." },
    ],
    keywords: ["Vehicle", "Core", "Fly", "Annihilation Barge"],
    factionKeywords: ["Necrons"],
  },
  {
    id: "nec-monolith",
    name: "Monolith",
    role: "Vehicle",
    category: "Lord of War",
    isTitanic: true,
    stats: { movement: '5"', toughness: 12, save: "2+", wounds: 20, leadership: "4+", oc: 8 },
    models: { min: 1, max: 1 },
    points: 400,
    weapons: [
      { name: "Death Ray", type: "Heavy", range: '36"', attacks: "3", skill: "BS3+", strength: "16", ap: "-4", damage: "D3+3" },
      { name: "Gauss Flux Arc ×4", type: "Heavy", range: '24"', attacks: "6", skill: "BS3+", strength: "5", ap: "-2", damage: "1" },
    ],
    abilities: [
      { name: "Titanic", description: "This model is a Titanic unit and cannot have Stratagems used to target it." },
      { name: "Living Metal", description: "At the start of your Command Phase, this model regains D3 lost wounds." },
      { name: "Eternity Gate", description: "Once per turn, in the Movement phase, one friendly Necron INFANTRY unit anywhere on the battlefield can teleport, removing it from the board and placing it within 3\" of this model and more than 9\" from enemy models." },
      { name: "Loom of the Gods", description: "At the start of the enemy Shooting phase, all enemy units within 12\" of this model must take a Battleshock test." },
    ],
    keywords: ["Vehicle", "Titanic", "Monolith"],
    factionKeywords: ["Necrons"],
  },
];

const AWAKENED_DYNASTY: Detachment = {
  name: "Awakened Dynasty",
  rule: {
    name: "Dynastic Protocols",
    description:
      "All Necron units get +1 to Reanimation Protocol rolls. Necron CORE units within 6\" of a friendly OVERLORD gain the Lethal Hits keyword on all unmodified hit rolls of 6.",
  },
  stratagems: [
    {
      name: "Disruption Fields",
      cost: 1,
      phase: "Fight",
      description: "Use at the start of the Fight phase. A friendly Necron CORE unit's melee attacks gain the Sustained Hits 1 keyword until end of phase.",
    },
    {
      name: "Quantum Deflection",
      cost: 1,
      phase: "Any",
      description: "Use when a friendly Necron unit is selected as the target of a ranged attack. Until end of that Shooting phase, that unit has a 5++ invulnerable save against those attacks.",
    },
    {
      name: "Entropic Strike",
      cost: 1,
      phase: "Any",
      description: "Use in the Shooting or Fight phase. A friendly Necron unit's weapons with AP -1 or better gain an additional -1 AP until end of that phase.",
    },
    {
      name: "Emergency Invasion Beam",
      cost: 1,
      phase: "Any",
      description: "Use at the end of any phase. Remove one friendly Necron INFANTRY unit from the battlefield and add it to Strategic Reserves. It may redeploy from reserves next turn using Tactical Reserves rules.",
    },
    {
      name: "Hand of the Phaeron",
      cost: 2,
      phase: "Command",
      description: "Use in the Command Phase. One friendly Necron VEHICLE within 12\" of a friendly OVERLORD automatically passes its Reanimation Protocol roll this turn, restoring it to 1 wound remaining if destroyed.",
    },
    {
      name: "Voltaic Staff",
      cost: 1,
      phase: "Shooting",
      description: "Use at the start of the Shooting phase. A friendly CRYPTEK unit can target enemy units not visible to it with its shooting attacks this phase.",
    },
  ],
  enhancements: [
    {
      name: "Sempiternal Weave",
      points: 20,
      description: "The bearer's Sv characteristic is improved by 1. Additionally, the bearer has a 4+++ Feel No Pain save against mortal wounds.",
      restriction: "Necrons CHARACTER",
    },
    {
      name: "Nanoscarab Casket",
      points: 15,
      description: "The bearer heals 2 wounds from Living Metal instead of 1, and their Reanimation Protocol roll succeeds on a 4+.",
      restriction: "Necrons CHARACTER",
    },
    {
      name: "Voltaic Staff",
      points: 10,
      description: "All of the bearer's shooting weapons gain the Devastating Wounds keyword.",
      restriction: "Necrons CHARACTER",
    },
    {
      name: "The Sovereign Coronal",
      points: 30,
      description: "Aura: Friendly Necron CORE units within 6\" of this model get +1 to their Attacks characteristic in the Fight phase.",
      restriction: "Necrons CHARACTER",
    },
  ],
};

export const NECRONS_FACTION: Faction = {
  id: "necrons",
  name: "Necrons",
  shortName: "Nec",
  description: "Ancient machine-warriors who slumbered in tombs for sixty million years. The Necrons have awoken to reclaim their galaxy, armed with deathless bodies and hyper-advanced technology.",
  accentColor: "#15803d",
  units: NECRON_UNITS,
  detachments: [AWAKENED_DYNASTY],
};
